Repository WISE-Community/WISE, pull requests merged in 2018-11, with the labels that each got.

#1596 Made site work in AOT mode
  angular.json
  src/main/webapp/site/src/app/app-routing.module.ts
  src/main/webapp/site/src/app/news/news.component.ts
Labels: 1 point, High

#1582 Issue 1573 shared legacy project not authorable
  src/main/java/org/wise/portal/dao/project/ProjectDao.java
  src/main/java/org/wise/portal/dao/project/impl/HibernateProjectDao.java
  src/main/java/org/wise/portal/presentation/web/controllers/admin/UpdateProjectSharedPermissionsAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/admin/UpdateSharedProjectsController.java
  src/main/java/org/wise/portal/service/project/ProjectService.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/resources/i18n/i18n.properties
  src/main/webapp/portal/admin/index.jsp
  src/main/webapp/portal/admin/project/updatesharedprojects.jsp
Labels: 0 points

#1599 Fixed a dead link when trying to recover a student username in the legacy site
  src/main/java/org/wise/portal/presentation/web/controllers/forgotaccount/student/SearchForStudentUserNameController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/resources/i18n/i18n.properties
Labels: 0 points

#1600 Added the progress bar on the submit button for the create student ac…
  src/main/webapp/site/src/app/register/register-student-form/register-student-form.component.html
  src/main/webapp/site/src/app/register/register-student-form/register-student-form.component.ts
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.html
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.ts
  src/main/webapp/site/src/app/register/register.module.ts
Labels: 0 points

#1609 Fixed a constraint bug that was constraining the step the constraint was created on when it should have only been constraining steps after it
  src/main/webapp/wise5/services/projectService.es6
  src/main/webapp/wise5/services/projectService.js
  src/main/webapp/wise5/services/projectService.js.map
Labels: 0 points

#1611 Fixed a problem with not being able to create a student account
  src/main/java/org/wise/portal/domain/AccountQuestion.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentForgotAccountAPIController.java
Labels: 0 points

#1613 Fix for previewing copied wise4 project in new site
  src/main/java/org/wise/portal/presentation/web/controllers/project/ProjectAPIController.java
Labels: Bug, High

#1610 Issue 1601 add note constraint
  src/main/webapp/wise5/authoringTool/i18n/i18n_en.json
  src/main/webapp/wise5/authoringTool/node/node.html
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.es6
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.js
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.js.map
  src/main/webapp/wise5/services/projectService.es6
  src/main/webapp/wise5/services/projectService.js
  src/main/webapp/wise5/services/projectService.js.map
  src/main/webapp/wise5/services/studentDataService.es6
  src/main/webapp/wise5/services/studentDataService.js
  src/main/webapp/wise5/services/studentDataService.js.map
  src/main/webapp/wise5/vle/i18n/i18n_en.json
Labels: 0 points

#1615 Added banner to beta site
  src/main/webapp/site/src/app/announcement-dialog.component.html
  src/main/webapp/site/src/app/announcement/announcement.component.html
  src/main/webapp/site/src/app/announcement/announcement.component.scss
  src/main/webapp/site/src/app/announcement/announcement.component.spec.ts
  src/main/webapp/site/src/app/announcement/announcement.component.ts
  src/main/webapp/site/src/app/app.component.html
  src/main/webapp/site/src/app/app.component.scss
  src/main/webapp/site/src/app/app.component.spec.ts
  src/main/webapp/site/src/app/app.component.ts
  src/main/webapp/site/src/app/app.module.ts
  src/main/webapp/site/src/style/abstracts/_mixins.scss
  src/main/webapp/site/src/style/layout/_main.scss
  src/main/webapp/site/src/style/themes/_dark.scss
  src/main/webapp/site/src/style/themes/_default.scss
Labels: 0 points

#1621 Added authoring for the Open Response numRows
  src/main/webapp/wise5/components/openResponse/authoring.html
  src/main/webapp/wise5/components/openResponse/i18n/i18n_en.json
Labels: 0 points

#1622 Remove CA implementation model select from library
  src/main/java/org/wise/portal/presentation/web/controllers/admin/ManagePortalController.java
  src/main/webapp/site/src/app/modules/library/home-page-project-library/home-page-project-library.component.html
  src/main/webapp/site/src/app/modules/library/library/library.component.ts
  src/main/webapp/site/src/app/modules/library/official-library/official-library.component.html
  src/main/webapp/site/src/app/modules/library/official-library/official-library.component.ts
  src/main/webapp/site/src/app/services/library.service.ts
  src/main/webapp/site/src/style/abstracts/_mixins.scss
  src/test/java/org/wise/portal/presentation/web/controllers/admin/ManagePortalControllerTest.java
  src/test/resources/projectLibraryGroupSample.json
Labels: 0 points

#1625 Fixed NGSS broken links
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.html
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.spec.ts
Labels: 0 points

#1633 Fixed blank pages on ios devices
  src/main/webapp/site/src/app/app.component.html
  src/main/webapp/site/src/app/app.component.ts
  src/main/webapp/site/src/app/app.module.ts
  src/main/webapp/site/src/app/login/login.component.html
  src/main/webapp/site/src/app/register/register.component.html
Labels: 0 points

#1602 sort run by start date and scroll to new run on creating a new run
  src/main/webapp/site/src/app/features/features.component.html
  src/main/webapp/site/src/app/forgot/forgot-home/forgot-home.component.html
  src/main/webapp/site/src/app/forgot/student/forgot-student-password-change/forgot-student-password-change.component.html
  src/main/webapp/site/src/app/forgot/student/forgot-student-password-complete/forgot-student-password-complete.component.html
  src/main/webapp/site/src/app/forgot/student/forgot-student-password-security/forgot-student-password-security.component.html
  src/main/webapp/site/src/app/forgot/student/forgot-student-password/forgot-student-password.component.html
  src/main/webapp/site/src/app/forgot/student/forgot-student-username/forgot-student-username.component.html
  src/main/webapp/site/src/app/forgot/student/forgot-student/forgot-student.component.html
  src/main/webapp/site/src/app/forgot/teacher/forgot-teacher-password-change/forgot-teacher-password-change.component.html
  src/main/webapp/site/src/app/forgot/teacher/forgot-teacher-password-complete/forgot-teacher-password-complete.component.html
  src/main/webapp/site/src/app/forgot/teacher/forgot-teacher-password-verify/forgot-teacher-password-verify.component.html
  src/main/webapp/site/src/app/forgot/teacher/forgot-teacher-password/forgot-teacher-password.component.html
  src/main/webapp/site/src/app/forgot/teacher/forgot-teacher-username-complete/forgot-teacher-username-complete.component.html
  src/main/webapp/site/src/app/forgot/teacher/forgot-teacher-username/forgot-teacher-username.component.html
  src/main/webapp/site/src/app/forgot/teacher/forgot-teacher/forgot-teacher.component.html
  src/main/webapp/site/src/app/help/getting-started/getting-started.component.html
  src/main/webapp/site/src/app/help/student-faq/student-faq.component.html
  src/main/webapp/site/src/app/help/teacher-faq/teacher-faq.component.html
  src/main/webapp/site/src/app/teacher/teacher-run-list/teacher-run-list.component.html
  src/main/webapp/site/src/app/teacher/teacher-run-list/teacher-run-list.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list/teacher-run-list.component.ts
  src/main/webapp/site/src/messages.xmb
Labels: 0 points

#1568 issue #1552 - Spring Upgrade
  pom.xml
Labels: 0 points

#1639 Fixed issue where admin could not add news item
  src/main/java/org/wise/portal/presentation/web/controllers/admin/NewsItemController.java
  src/main/webapp/portal/admin/index.jsp
  src/main/webapp/portal/admin/news/addnewsitem.jsp
  src/main/webapp/portal/admin/news/editnewsitem.jsp
  src/main/webapp/portal/admin/news/managenewsitems.jsp
Labels: 0 points

#1641 Added content to site footer
  src/main/webapp/site/src/app/app.component.ts
  src/main/webapp/site/src/app/modules/footer/footer.component.html
  src/main/webapp/site/src/app/modules/footer/footer.component.scss
  src/main/webapp/site/src/app/modules/footer/footer.component.spec.ts
  src/main/webapp/site/src/app/modules/footer/footer.module.ts
  src/main/webapp/site/src/assets/img/footer/cc-logo.png
  src/main/webapp/site/src/assets/img/footer/nsf-logo.png
  src/main/webapp/site/src/assets/img/footer/sail-logo.png
  src/main/webapp/site/src/assets/img/footer/uc-berkeley-logo.png
  src/main/webapp/site/src/assets/img/icons/facebook-ffffff.svg
  src/main/webapp/site/src/assets/img/icons/twitter-ffffff.svg
Labels: 0 points

#1644 Styled news
  src/main/webapp/site/src/app/news/news.component.html
  src/main/webapp/site/src/app/news/news.component.scss
Labels: 0 points

#1634 Styled the contact form
  src/main/webapp/site/src/app/app.component.ts
  src/main/webapp/site/src/app/contact/contact-complete/contact-complete.component.html
  src/main/webapp/site/src/app/contact/contact-complete/contact-complete.component.scss
  src/main/webapp/site/src/app/contact/contact-complete/contact-complete.component.spec.ts
  src/main/webapp/site/src/app/contact/contact-complete/contact-complete.component.ts
  src/main/webapp/site/src/app/contact/contact-form/contact-form.component.html
  src/main/webapp/site/src/app/contact/contact-form/contact-form.component.ts
  src/main/webapp/site/src/app/contact/contact-routing.module.ts
  src/main/webapp/site/src/app/contact/contact.module.ts
  src/main/webapp/site/src/messages.xmb
Labels: 0 points

#1632 Updated banner text
  src/main/webapp/site/src/app/announcement-dialog.component.html
  src/main/webapp/site/src/app/announcement/announcement.component.html
  src/main/webapp/site/src/app/app.component.html
Labels: 0 points

#1645 i18n ng-container tags need a space
  src/main/webapp/site/src/app/features/features.component.html
  src/main/webapp/site/src/app/help/getting-started/getting-started.component.html
  src/main/webapp/site/src/app/help/student-faq/student-faq.component.html
  src/main/webapp/site/src/app/help/teacher-faq/teacher-faq.component.html
  src/main/webapp/site/src/app/login/login-google-user-not-found/login-google-user-not-found.component.html
  src/main/webapp/site/src/app/login/login-home/login-home.component.html
  src/main/webapp/site/src/app/privacy/privacy.component.html
  src/main/webapp/site/src/app/register/register-student-form/register-student-form.component.html
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.html
  src/main/webapp/site/src/messages.xmb
Labels: 0 points

#1648 Temporarily hid links to missing features on the new site
  src/main/webapp/site/src/app/features/features.component.html
  src/main/webapp/site/src/app/features/features.component.scss
  src/main/webapp/site/src/app/modules/footer/footer.component.html
  src/main/webapp/site/src/app/modules/header/header-links/header-links.component.html
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.html
  src/main/webapp/site/src/app/modules/mobile-menu/mobile-menu.component.html
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.html
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.html
  src/main/webapp/site/src/assets/img/icons/twitter.svg
  src/main/webapp/site/src/messages.xmb
Labels: 0 points

#1649 Issue 1640 pre commit hook
  pre-commit
Labels: 0 points

#1657 Added About Us page
  src/main/webapp/site/src/app/about/about-routing.module.ts
  src/main/webapp/site/src/app/about/about.component.css
  src/main/webapp/site/src/app/about/about.component.html
  src/main/webapp/site/src/app/about/about.component.scss
  src/main/webapp/site/src/app/about/about.component.spec.ts
  src/main/webapp/site/src/app/about/about.component.ts
  src/main/webapp/site/src/app/about/about.module.ts
  src/main/webapp/site/src/app/app-routing.module.ts
  src/main/webapp/site/src/app/app.module.ts
  src/main/webapp/site/src/app/features/features.component.html
  src/main/webapp/site/src/app/modules/footer/footer.component.html
  src/main/webapp/site/src/app/modules/header/header-links/header-links.component.html
  src/main/webapp/site/src/app/modules/mobile-menu/mobile-menu.component.html
  src/main/webapp/site/src/assets/img/about/marcia-wise-workshop.jpg
  src/main/webapp/site/src/assets/img/about/wise-student-and-teacher.jpg
  src/main/webapp/site/src/assets/img/about/wise-students-add-note.jpg
  src/main/webapp/site/src/assets/img/about/wise-teacher-workshop-design.jpg
  src/main/webapp/site/src/assets/img/about/wise-teachers-researcher.jpg
  src/main/webapp/site/src/assets/img/about/wise-tech-teacher-workshop.jpg
  src/main/webapp/site/src/assets/img/about/wise-workshop-group-2018-fun.jpg
  src/main/webapp/site/src/assets/img/about/wise-workshop-researcher.jpg
  src/main/webapp/site/src/messages.xmb
  src/main/webapp/site/src/style/abstracts/_mixins.scss
Labels: 0 points

#1653 Issue 1530 and 1531 refactor concept map
  src/main/webapp/wise5/components/animation/animationAuthoringController.es6
  src/main/webapp/wise5/components/animation/animationAuthoringController.js
  src/main/webapp/wise5/components/animation/animationAuthoringController.js.map
  src/main/webapp/wise5/components/animation/animationController.es6
  src/main/webapp/wise5/components/animation/animationController.js
  src/main/webapp/wise5/components/animation/animationController.js.map
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.es6
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.js
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.js.map
  src/main/webapp/wise5/components/componentController.es6
  src/main/webapp/wise5/components/componentController.js
  src/main/webapp/wise5/components/componentController.js.map
  src/main/webapp/wise5/components/conceptMap/authoring.html
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.js.map
  src/main/webapp/wise5/components/conceptMap/conceptMapController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js.map
  src/main/webapp/wise5/components/conceptMap/conceptMapService.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapService.js
  src/main/webapp/wise5/components/conceptMap/conceptMapService.js.map
  src/main/webapp/wise5/services/utilService.es6
  src/main/webapp/wise5/services/utilService.js
  src/main/webapp/wise5/services/utilService.js.map
  src/main/webapp/wise5/test-unit/components/conceptMap/conceptMapAuthoringController.spec.es6
  src/main/webapp/wise5/test-unit/components/conceptMap/conceptMapAuthoringController.spec.js
  src/main/webapp/wise5/test-unit/components/conceptMap/conceptMapAuthoringController.spec.js.map
  src/main/webapp/wise5/test-unit/components/conceptMap/conceptMapController.spec.es6
  src/main/webapp/wise5/test-unit/components/conceptMap/conceptMapController.spec.js
  src/main/webapp/wise5/test-unit/components/conceptMap/conceptMapController.spec.js.map
  src/main/webapp/wise5/test-unit/components/conceptMap/conceptMapService.spec.es6
  src/main/webapp/wise5/test-unit/components/conceptMap/conceptMapService.spec.js
  src/main/webapp/wise5/test-unit/components/conceptMap/conceptMapService.spec.js.map
Labels: 0 points

#1664 Fixed a problem with project names in foreign languages showing up as ?????. Also added the fix to other server requests that have the potential to respond with foreign language text.
  src/main/java/org/wise/portal/presentation/web/controllers/news/NewsAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/project/ProjectAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentForgotAccountAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
Labels: 0 points

#1654 Implemented ending run from teacher run listing page.
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/webapp/site/src/app/teacher/end-run-dialog/end-run-dialog.component.html
  src/main/webapp/site/src/app/teacher/end-run-dialog/end-run-dialog.component.scss
  src/main/webapp/site/src/app/teacher/end-run-dialog/end-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/end-run-dialog/end-run-dialog.component.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.html
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.ts
  src/main/webapp/site/src/app/teacher/teacher.module.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
  src/main/webapp/site/src/messages.xmb
Labels: 0 points

#1658 Runs that have 1 student per team no longer show the team sign in page
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentAPIController.java
  src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.ts
  src/main/webapp/site/src/app/student/student-run.ts
  src/main/webapp/site/src/messages.xmb
Labels: 0 points

#1669 Fixed a problem with an error displaying when a user changed their password
  src/main/java/org/wise/portal/presentation/web/controllers/news/NewsAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/project/ProjectAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentForgotAccountAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
Labels: 0 points
