Repository WISE-Community/WISE, pull requests merged in 2018-06, with the labels that each got.

#1224 Issue 777 concept map allow hide node titles
  src/main/webapp/wise5/components/conceptMap/conceptMapController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js.map
  src/main/webapp/wise5/components/conceptMap/conceptMapService.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapService.js
  src/main/webapp/wise5/components/conceptMap/conceptMapService.js.map
  src/main/webapp/wise5/components/conceptMap/i18n/i18n_en.json
  src/main/webapp/wise5/components/conceptMap/index.html
Labels: Improvement

#1234 Show logged in user's name on student home
  src/main/webapp/site/src/app/modules/header/header.component.scss
  src/main/webapp/site/src/app/modules/library/library.component.scss
  src/main/webapp/site/src/app/modules/library/library.module.ts
  src/main/webapp/site/src/app/modules/shared/shared.module.ts
  src/main/webapp/site/src/app/student/student-home/student-home.component.html
  src/main/webapp/site/src/app/student/student-home/student-home.component.spec.ts
  src/main/webapp/site/src/app/student/student-home/student-home.component.ts
  src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.html
  src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.scss
  src/main/webapp/site/src/app/student/student-run-list/student-run-list.component.ts
Labels: Feature Request

#1238 Refactored MatchController and MatchService
  src/main/webapp/wise5/components/match/index.html
  src/main/webapp/wise5/components/match/matchController.es6
  src/main/webapp/wise5/components/match/matchController.js
  src/main/webapp/wise5/components/match/matchController.js.map
  src/main/webapp/wise5/components/match/matchService.es6
  src/main/webapp/wise5/components/match/matchService.js
  src/main/webapp/wise5/components/match/matchService.js.map
  src/main/webapp/wise5/services/studentDataService.es6
  src/main/webapp/wise5/services/studentDataService.js
  src/main/webapp/wise5/services/studentDataService.js.map
Labels: Improvement

#1244 Import private notes into match
  src/main/webapp/wise5/classroomMonitor/main.es6
  src/main/webapp/wise5/classroomMonitor/main.js
  src/main/webapp/wise5/classroomMonitor/main.js.map
  src/main/webapp/wise5/components/match/i18n/i18n_en.json
  src/main/webapp/wise5/components/match/index.html
  src/main/webapp/wise5/components/match/matchController.es6
  src/main/webapp/wise5/components/match/matchController.js
  src/main/webapp/wise5/components/match/matchController.js.map
  src/main/webapp/wise5/services/notebookService.es6
  src/main/webapp/wise5/services/notebookService.js
  src/main/webapp/wise5/services/notebookService.js.map
Labels: Feature Request

#1249 Components can now individually enable or disable the "Add to Notebook" button
  src/main/webapp/wise5/components/componentController.es6
  src/main/webapp/wise5/components/componentController.js
  src/main/webapp/wise5/components/componentController.js.map
  src/main/webapp/wise5/components/conceptMap/conceptMapController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js.map
  src/main/webapp/wise5/components/conceptMap/index.html
  src/main/webapp/wise5/components/draw/drawController.es6
  src/main/webapp/wise5/components/draw/drawController.js
  src/main/webapp/wise5/components/draw/drawController.js.map
  src/main/webapp/wise5/components/draw/index.html
  src/main/webapp/wise5/components/embedded/embeddedController.es6
  src/main/webapp/wise5/components/embedded/embeddedController.js
  src/main/webapp/wise5/components/embedded/embeddedController.js.map
  src/main/webapp/wise5/components/embedded/index.html
  src/main/webapp/wise5/components/graph/graphController.es6
  src/main/webapp/wise5/components/graph/graphController.js
  src/main/webapp/wise5/components/graph/graphController.js.map
  src/main/webapp/wise5/components/graph/index.html
  src/main/webapp/wise5/components/label/index.html
  src/main/webapp/wise5/components/label/labelController.es6
  src/main/webapp/wise5/components/label/labelController.js
  src/main/webapp/wise5/components/label/labelController.js.map
  src/main/webapp/wise5/components/match/matchController.es6
  src/main/webapp/wise5/components/match/matchController.js
  src/main/webapp/wise5/components/match/matchController.js.map
  src/main/webapp/wise5/components/openResponse/index.html
  src/main/webapp/wise5/components/openResponse/openResponseController.es6
  src/main/webapp/wise5/components/openResponse/openResponseController.js
  src/main/webapp/wise5/components/openResponse/openResponseController.js.map
  src/main/webapp/wise5/components/table/index.html
  src/main/webapp/wise5/components/table/tableController.es6
  src/main/webapp/wise5/components/table/tableController.js
  src/main/webapp/wise5/components/table/tableController.js.map
  src/main/webapp/wise5/i18n/i18n_en.json
  src/main/webapp/wise5/services/notebookService.es6
  src/main/webapp/wise5/services/notebookService.js
  src/main/webapp/wise5/services/notebookService.js.map
Labels: Feature Request

#1245 Fixed a problem with components not loading if they referenced a file name that contained an apostrophe
  src/main/webapp/wise5/services/projectService.es6
  src/main/webapp/wise5/services/projectService.js
  src/main/webapp/wise5/services/projectService.js.map
Labels: Bug

#1254 HTML Component: Moved authoring html and controller functions to separate authoring files
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/components/html/authoring.html
  src/main/webapp/wise5/components/html/htmlAuthoringComponentModule.es6
  src/main/webapp/wise5/components/html/htmlAuthoringComponentModule.js
  src/main/webapp/wise5/components/html/htmlAuthoringComponentModule.js.map
  src/main/webapp/wise5/components/html/htmlAuthoringController.es6
  src/main/webapp/wise5/components/html/htmlAuthoringController.js
  src/main/webapp/wise5/components/html/htmlAuthoringController.js.map
  src/main/webapp/wise5/components/html/htmlController.es6
  src/main/webapp/wise5/components/html/htmlController.js
  src/main/webapp/wise5/components/html/htmlController.js.map
  src/main/webapp/wise5/components/html/index.html
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
  src/main/webapp/wise5/services/nodeService.es6
  src/main/webapp/wise5/services/nodeService.js
  src/main/webapp/wise5/services/nodeService.js.map
Labels: Improvement

#1259 Editing project library groups for admin users
  src/main/java/org/wise/portal/domain/portal/Portal.java
  src/main/java/org/wise/portal/domain/portal/impl/PortalImpl.java
  src/main/java/org/wise/portal/presentation/web/controllers/admin/ManagePortalController.java
  src/main/java/org/wise/portal/service/portal/PortalService.java
  src/main/java/org/wise/portal/service/portal/impl/PortalServiceImpl.java
  src/main/webapp/portal/admin/portal/manage.jsp
Labels: Feature Request

#1258 Image added in a new note now appears immediately
  src/main/webapp/wise5/services/notebookService.es6
  src/main/webapp/wise5/services/notebookService.js
  src/main/webapp/wise5/services/notebookService.js.map
  src/main/webapp/wise5/themes/default/notebook/editNotebookItemController.es6
  src/main/webapp/wise5/themes/default/notebook/editNotebookItemController.js
  src/main/webapp/wise5/themes/default/notebook/editNotebookItemController.js.map
Labels: Bug

#1263 Moved cache busting code to a separate file.
  src/main/webapp/portal/author.jsp
  src/main/webapp/portal/classroomMonitor.jsp
  src/main/webapp/portal/student.jsp
  src/main/webapp/wise5/cacheBuster.js
  src/main/webapp/wise5/config.js
  versionBump.sh
Labels: Bug

#1264 Concept Map: Moved authoring html and controller functions to separate authoring files
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/components/conceptMap/authoring.html
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringComponentModule.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringComponentModule.js
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringComponentModule.js.map
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.js.map
  src/main/webapp/wise5/components/conceptMap/conceptMapController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js.map
  src/main/webapp/wise5/components/conceptMap/index.html
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement

#1272 Fixed a bug that prevented Discussion from loading. #Closes 1271
  src/main/webapp/wise5/components/discussion/discussionController.es6
  src/main/webapp/wise5/components/discussion/discussionController.js
  src/main/webapp/wise5/components/discussion/discussionController.js.map
Labels: Bug

#1275 Issue 1274 move draw authoring functions
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/components/draw/authoring.html
  src/main/webapp/wise5/components/draw/drawAuthoringComponentModule.es6
  src/main/webapp/wise5/components/draw/drawAuthoringComponentModule.js
  src/main/webapp/wise5/components/draw/drawAuthoringComponentModule.js.map
  src/main/webapp/wise5/components/draw/drawAuthoringController.es6
  src/main/webapp/wise5/components/draw/drawAuthoringController.js
  src/main/webapp/wise5/components/draw/drawAuthoringController.js.map
  src/main/webapp/wise5/components/draw/drawController.es6
  src/main/webapp/wise5/components/draw/drawController.js
  src/main/webapp/wise5/components/draw/drawController.js.map
  src/main/webapp/wise5/components/draw/index.html
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement

#1294 Fixed issue inserting note into report
  src/main/webapp/wise5/themes/default/notebook/notebook/notebook.es6
  src/main/webapp/wise5/themes/default/notebook/notebook/notebook.js
  src/main/webapp/wise5/themes/default/notebook/notebook/notebook.js.map
Labels: Bug, High

#1273 Issue 1265 move discussion authoring functions
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/components/componentController.es6
  src/main/webapp/wise5/components/componentController.js
  src/main/webapp/wise5/components/componentController.js.map
  src/main/webapp/wise5/components/discussion/authoring.html
  src/main/webapp/wise5/components/discussion/discussionAuthoringComponentModule.es6
  src/main/webapp/wise5/components/discussion/discussionAuthoringComponentModule.js
  src/main/webapp/wise5/components/discussion/discussionAuthoringComponentModule.js.map
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.es6
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.js
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.js.map
  src/main/webapp/wise5/components/discussion/discussionController.es6
  src/main/webapp/wise5/components/discussion/discussionController.js
  src/main/webapp/wise5/components/discussion/discussionController.js.map
  src/main/webapp/wise5/components/discussion/i18n/i18n_en.json
  src/main/webapp/wise5/components/discussion/index.html
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement

#1279 Issue 1278 move label authoring functions
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/components/label/authoring.html
  src/main/webapp/wise5/components/label/index.html
  src/main/webapp/wise5/components/label/labelAuthoringComponentModule.es6
  src/main/webapp/wise5/components/label/labelAuthoringComponentModule.js
  src/main/webapp/wise5/components/label/labelAuthoringComponentModule.js.map
  src/main/webapp/wise5/components/label/labelAuthoringController.es6
  src/main/webapp/wise5/components/label/labelAuthoringController.js
  src/main/webapp/wise5/components/label/labelAuthoringController.js.map
  src/main/webapp/wise5/components/label/labelController.es6
  src/main/webapp/wise5/components/label/labelController.js
  src/main/webapp/wise5/components/label/labelController.js.map
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement

#1283 Issue 1282 move open response authoring functions
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/components/openResponse/authoring.html
  src/main/webapp/wise5/components/openResponse/index.html
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringComponentModule.es6
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringComponentModule.js
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringComponentModule.js.map
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.es6
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.js
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.js.map
  src/main/webapp/wise5/components/openResponse/openResponseController.es6
  src/main/webapp/wise5/components/openResponse/openResponseController.js
  src/main/webapp/wise5/components/openResponse/openResponseController.js.map
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement

#1285 Issue 1284 move table authoring functions
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/components/table/authoring.html
  src/main/webapp/wise5/components/table/index.html
  src/main/webapp/wise5/components/table/tableAuthoringComponentModule.es6
  src/main/webapp/wise5/components/table/tableAuthoringComponentModule.js
  src/main/webapp/wise5/components/table/tableAuthoringComponentModule.js.map
  src/main/webapp/wise5/components/table/tableAuthoringController.es6
  src/main/webapp/wise5/components/table/tableAuthoringController.js
  src/main/webapp/wise5/components/table/tableAuthoringController.js.map
  src/main/webapp/wise5/components/table/tableController.es6
  src/main/webapp/wise5/components/table/tableController.js
  src/main/webapp/wise5/components/table/tableController.js.map
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement

#1287 Issue 1286 move outside url authoring functions
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/components/outsideURL/authoring.html
  src/main/webapp/wise5/components/outsideURL/index.html
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringComponentModule.es6
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringComponentModule.js
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringComponentModule.js.map
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringController.es6
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringController.js
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringController.js.map
  src/main/webapp/wise5/components/outsideURL/outsideURLController.es6
  src/main/webapp/wise5/components/outsideURL/outsideURLController.js
  src/main/webapp/wise5/components/outsideURL/outsideURLController.js.map
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement

#1289 Issue 1288 move multiple choice authoring functions
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/components/multipleChoice/authoring.html
  src/main/webapp/wise5/components/multipleChoice/index.html
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringComponentModule.es6
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringComponentModule.js
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringComponentModule.js.map
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.es6
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.js
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.js.map
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.es6
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.js
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.js.map
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement

#1303 Added unit test for graphService.hasTrialData
  src/main/webapp/wise5/components/graph/graphService.es6
  src/main/webapp/wise5/components/graph/graphService.js
  src/main/webapp/wise5/components/graph/graphService.js.map
  src/main/webapp/wise5/test-unit/components/graph/graphService.spec.es6
  src/main/webapp/wise5/test-unit/components/graph/graphService.spec.js
  src/main/webapp/wise5/test-unit/components/graph/graphService.spec.js.map
Labels: Improvement, Test

#1291 Issue 1290 move embedded authoring functions
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/components/embedded/authoring.html
  src/main/webapp/wise5/components/embedded/embeddedAuthoringComponentModule.es6
  src/main/webapp/wise5/components/embedded/embeddedAuthoringComponentModule.js
  src/main/webapp/wise5/components/embedded/embeddedAuthoringComponentModule.js.map
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.es6
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.js
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.js.map
  src/main/webapp/wise5/components/embedded/embeddedController.es6
  src/main/webapp/wise5/components/embedded/embeddedController.js
  src/main/webapp/wise5/components/embedded/embeddedController.js.map
  src/main/webapp/wise5/components/embedded/index.html
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement

#1295 Issue 1292 move audio oscillator authoring functions
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringComponentModule.es6
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringComponentModule.js
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringComponentModule.js.map
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.es6
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.js
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.js.map
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.es6
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.js
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.js.map
  src/main/webapp/wise5/components/audioOscillator/authoring.html
  src/main/webapp/wise5/components/audioOscillator/index.html
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement

#1315 Added "Loading Project" message when opening a project from the Authoring Tool project list
  src/main/webapp/wise5/authoringTool/i18n/i18n_en.json
  src/main/webapp/wise5/authoringTool/main/authoringToolMainController.es6
  src/main/webapp/wise5/authoringTool/main/authoringToolMainController.js
  src/main/webapp/wise5/authoringTool/main/authoringToolMainController.js.map
  src/main/webapp/wise5/authoringTool/project/projectController.es6
  src/main/webapp/wise5/authoringTool/project/projectController.js
  src/main/webapp/wise5/authoringTool/project/projectController.js.map
Labels: Improvement

#1312 Reset graph bug
  src/main/webapp/wise5/components/componentController.js
  src/main/webapp/wise5/components/componentController.js.map
  src/main/webapp/wise5/components/graph/graphController.es6
  src/main/webapp/wise5/components/graph/graphController.js
  src/main/webapp/wise5/components/graph/graphController.js.map
Labels: Bug

#1317 Match: Added authoring for horizontal mode where the source bucket shows up on the left and the target buckets show up on the right
  src/main/webapp/wise5/components/match/authoring.html
  src/main/webapp/wise5/components/match/i18n/i18n_en.json
  src/main/webapp/wise5/components/match/matchAuthoringController.es6
  src/main/webapp/wise5/components/match/matchAuthoringController.js
  src/main/webapp/wise5/components/match/matchAuthoringController.js.map
Labels: Feature Request

#1320 Issue 1319 add source bucket target bucket terminology
  src/main/webapp/wise5/components/match/authoring.html
  src/main/webapp/wise5/components/match/i18n/i18n_en.json
Labels: Improvement

#1318 Removed opencpu code
  src/main/java/org/wise/portal/presentation/web/controllers/InformationController.java
  src/main/resources/wise_sample.properties
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.es6
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.js
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.js.map
  src/main/webapp/wise5/services/configService.es6
  src/main/webapp/wise5/services/configService.js
  src/main/webapp/wise5/services/configService.js.map
  src/main/webapp/wise5/themes/default/vle.html
  src/main/webapp/wise5/vle/navigation/navigationController.es6
  src/main/webapp/wise5/vle/navigation/navigationController.js
  src/main/webapp/wise5/vle/navigation/navigationController.js.map
Labels: Improvement

#1322 AT "Go Home" should properly remove from current authors list
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/WISE5AuthorProjectController.java
  src/main/webapp/wise5/authoringTool/components/shared/topBar/topBar.es6
  src/main/webapp/wise5/authoringTool/components/shared/topBar/topBar.js
  src/main/webapp/wise5/authoringTool/components/shared/topBar/topBar.js.map
  src/main/webapp/wise5/authoringTool/main/authoringToolMainController.es6
  src/main/webapp/wise5/authoringTool/main/authoringToolMainController.js
  src/main/webapp/wise5/authoringTool/main/authoringToolMainController.js.map
  src/main/webapp/wise5/services/sessionService.es6
  src/main/webapp/wise5/services/sessionService.js
  src/main/webapp/wise5/services/sessionService.js.map
Labels: Bug

#1326 Match: Fixed a problem with not being able to choose an image for a target bucket
  src/main/webapp/wise5/components/match/authoring.html
Labels: Bug

#1327 Removed references to importPreviousWorkNodeId and importPreviousWorkComponentId in the code
  src/main/webapp/wise5/components/animation/animationController.es6
  src/main/webapp/wise5/components/animation/animationController.js
  src/main/webapp/wise5/components/animation/animationController.js.map
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.es6
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.js
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.js.map
  src/main/webapp/wise5/components/conceptMap/conceptMapController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js.map
  src/main/webapp/wise5/components/discussion/discussionController.es6
  src/main/webapp/wise5/components/discussion/discussionController.js
  src/main/webapp/wise5/components/discussion/discussionController.js.map
  src/main/webapp/wise5/components/draw/drawController.es6
  src/main/webapp/wise5/components/draw/drawController.js
  src/main/webapp/wise5/components/draw/drawController.js.map
  src/main/webapp/wise5/components/graph/graphController.es6
  src/main/webapp/wise5/components/graph/graphController.js
  src/main/webapp/wise5/components/graph/graphController.js.map
  src/main/webapp/wise5/components/label/labelController.es6
  src/main/webapp/wise5/components/label/labelController.js
  src/main/webapp/wise5/components/label/labelController.js.map
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.es6
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.js
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.js.map
  src/main/webapp/wise5/components/openResponse/openResponseController.es6
  src/main/webapp/wise5/components/openResponse/openResponseController.js
  src/main/webapp/wise5/components/openResponse/openResponseController.js.map
  src/main/webapp/wise5/components/table/tableController.es6
  src/main/webapp/wise5/components/table/tableController.js
  src/main/webapp/wise5/components/table/tableController.js.map
Labels: Improvement

#1330 Moved tag authoring functions to the parent componentController.es6
  src/main/webapp/wise5/components/animation/animationAuthoringController.es6
  src/main/webapp/wise5/components/animation/animationAuthoringController.js
  src/main/webapp/wise5/components/animation/animationAuthoringController.js.map
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.es6
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.js
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.js.map
  src/main/webapp/wise5/components/componentController.es6
  src/main/webapp/wise5/components/componentController.js
  src/main/webapp/wise5/components/componentController.js.map
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.js.map
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.es6
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.js
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.js.map
  src/main/webapp/wise5/components/draw/drawAuthoringController.es6
  src/main/webapp/wise5/components/draw/drawAuthoringController.js
  src/main/webapp/wise5/components/draw/drawAuthoringController.js.map
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.es6
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.js
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.js.map
  src/main/webapp/wise5/components/graph/graphAuthoringController.es6
  src/main/webapp/wise5/components/graph/graphAuthoringController.js
  src/main/webapp/wise5/components/graph/graphAuthoringController.js.map
  src/main/webapp/wise5/components/label/labelAuthoringController.es6
  src/main/webapp/wise5/components/label/labelAuthoringController.js
  src/main/webapp/wise5/components/label/labelAuthoringController.js.map
  src/main/webapp/wise5/components/match/matchAuthoringController.es6
  src/main/webapp/wise5/components/match/matchAuthoringController.js
  src/main/webapp/wise5/components/match/matchAuthoringController.js.map
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.es6
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.js
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.js.map
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.es6
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.js
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.js.map
  src/main/webapp/wise5/components/table/tableAuthoringController.es6
  src/main/webapp/wise5/components/table/tableAuthoringController.js
  src/main/webapp/wise5/components/table/tableAuthoringController.js.map
Labels: Improvement

#1321 Multiple Choice: When adding a multiple choice connected component, we now automatically copy the choices from the connected component
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.es6
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.js
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.js.map
Labels: Improvement

#1332 Removed originalComponentContent from the code
  src/main/webapp/wise5/components/animation/animationController.es6
  src/main/webapp/wise5/components/animation/animationController.js
  src/main/webapp/wise5/components/animation/animationController.js.map
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.es6
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.js
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.js.map
  src/main/webapp/wise5/components/conceptMap/conceptMapController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js.map
  src/main/webapp/wise5/components/discussion/discussionController.es6
  src/main/webapp/wise5/components/discussion/discussionController.js
  src/main/webapp/wise5/components/discussion/discussionController.js.map
  src/main/webapp/wise5/components/draw/drawController.es6
  src/main/webapp/wise5/components/draw/drawController.js
  src/main/webapp/wise5/components/draw/drawController.js.map
  src/main/webapp/wise5/components/embedded/embeddedController.es6
  src/main/webapp/wise5/components/embedded/embeddedController.js
  src/main/webapp/wise5/components/embedded/embeddedController.js.map
  src/main/webapp/wise5/components/graph/graphController.es6
  src/main/webapp/wise5/components/graph/graphController.js
  src/main/webapp/wise5/components/graph/graphController.js.map
  src/main/webapp/wise5/components/html/htmlController.es6
  src/main/webapp/wise5/components/html/htmlController.js
  src/main/webapp/wise5/components/html/htmlController.js.map
  src/main/webapp/wise5/components/label/labelController.es6
  src/main/webapp/wise5/components/label/labelController.js
  src/main/webapp/wise5/components/label/labelController.js.map
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.es6
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.js
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.js.map
  src/main/webapp/wise5/components/openResponse/openResponseController.es6
  src/main/webapp/wise5/components/openResponse/openResponseController.js
  src/main/webapp/wise5/components/openResponse/openResponseController.js.map
  src/main/webapp/wise5/components/outsideURL/outsideURLController.es6
  src/main/webapp/wise5/components/outsideURL/outsideURLController.js
  src/main/webapp/wise5/components/outsideURL/outsideURLController.js.map
  src/main/webapp/wise5/components/table/tableController.es6
  src/main/webapp/wise5/components/table/tableController.js
  src/main/webapp/wise5/components/table/tableController.js.map
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement

#1337 Moved common authoring functions to parent
  src/main/webapp/wise5/components/animation/animationAuthoringController.es6
  src/main/webapp/wise5/components/animation/animationAuthoringController.js
  src/main/webapp/wise5/components/animation/animationAuthoringController.js.map
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.es6
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.js
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.js.map
  src/main/webapp/wise5/components/componentController.es6
  src/main/webapp/wise5/components/componentController.js
  src/main/webapp/wise5/components/componentController.js.map
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.js.map
  src/main/webapp/wise5/components/conceptMap/index.html
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.es6
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.js
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.js.map
  src/main/webapp/wise5/components/draw/drawAuthoringController.es6
  src/main/webapp/wise5/components/draw/drawAuthoringController.js
  src/main/webapp/wise5/components/draw/drawAuthoringController.js.map
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.es6
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.js
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.js.map
  src/main/webapp/wise5/components/graph/graphAuthoringController.es6
  src/main/webapp/wise5/components/graph/graphAuthoringController.js
  src/main/webapp/wise5/components/graph/graphAuthoringController.js.map
  src/main/webapp/wise5/components/html/htmlAuthoringController.es6
  src/main/webapp/wise5/components/html/htmlAuthoringController.js
  src/main/webapp/wise5/components/html/htmlAuthoringController.js.map
  src/main/webapp/wise5/components/label/labelAuthoringController.es6
  src/main/webapp/wise5/components/label/labelAuthoringController.js
  src/main/webapp/wise5/components/label/labelAuthoringController.js.map
  src/main/webapp/wise5/components/match/matchAuthoringController.es6
  src/main/webapp/wise5/components/match/matchAuthoringController.js
  src/main/webapp/wise5/components/match/matchAuthoringController.js.map
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.es6
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.js
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.js.map
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.es6
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.js
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.js.map
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringController.es6
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringController.js
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringController.js.map
  src/main/webapp/wise5/components/table/tableAuthoringController.es6
  src/main/webapp/wise5/components/table/tableAuthoringController.js
  src/main/webapp/wise5/components/table/tableAuthoringController.js.map
  src/main/webapp/wise5/directives/component/component.es6
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/directives/component/component.js.map
Labels: Improvement
