Repository WISE-Community/WISE, pull requests merged in 2018-08, with the labels that each got.

#1382 Refactored AudioOscillatorService
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorService.es6
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorService.js
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorService.js.map
  src/main/webapp/wise5/test-unit/components/audioOscillator/audioOscillatorService.spec.es6
  src/main/webapp/wise5/test-unit/components/audioOscillator/audioOscillatorService.spec.js
  src/main/webapp/wise5/test-unit/components/audioOscillator/audioOscillatorService.spec.js.map
Labels: Improvement

#1374 Runs that starts in the future will not allow student to launch it
  src/main/java/org/wise/portal/presentation/web/controllers/student/StartProjectController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/TeamSignInController.java
  src/main/webapp/site/src/app/domain/config.ts
  src/main/webapp/site/src/app/student/student-home/student-home.component.spec.ts
  src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.html
  src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.spec.ts
  src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.ts
  src/main/webapp/site/src/app/student/student-run-list/student-run-list.component.spec.ts
Labels: Feature Request

#1394 Register teacher with google
  package.json
  pom.xml
  src/main/java/org/wise/portal/dao/authentication/UserDetailsDao.java
  src/main/java/org/wise/portal/dao/authentication/impl/HibernateUserDetailsDao.java
  src/main/java/org/wise/portal/dao/user/UserDao.java
  src/main/java/org/wise/portal/dao/user/impl/HibernateUserDao.java
  src/main/java/org/wise/portal/domain/authentication/impl/PersistentUserDetails.java
  src/main/java/org/wise/portal/presentation/web/config/GoogleOpenIdConnectConfig.java
  src/main/java/org/wise/portal/presentation/web/controllers/admin/SiteController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/java/org/wise/portal/presentation/web/filters/GoogleOpenIdConnectFilter.java
  src/main/java/org/wise/portal/presentation/web/filters/WISEAuthenticationSuccessHandler.java
  src/main/java/org/wise/portal/service/authentication/UserDetailsService.java
  src/main/java/org/wise/portal/service/authentication/impl/UserDetailsServiceImpl.java
  src/main/java/org/wise/portal/service/user/UserService.java
  src/main/java/org/wise/portal/service/user/impl/UserServiceImpl.java
  src/main/java/org/wise/portal/spring/impl/CustomDispatcherServlet.java
  src/main/resources/configurations/applicationContexts.xml
  src/main/resources/wise_db_init.sql
  src/main/resources/wise_sample.properties
  src/main/webapp/WEB-INF/web.xml
  src/main/webapp/site/src/app/app-routing.module.ts
  src/main/webapp/site/src/app/app.module.ts
  src/main/webapp/site/src/app/domain/config.ts
  src/main/webapp/site/src/app/domain/teacher.ts
  src/main/webapp/site/src/app/login/login.component.html
  src/main/webapp/site/src/app/login/login.component.ts
  src/main/webapp/site/src/app/register/register-home/register-home.component.html
  src/main/webapp/site/src/app/register/register-home/register-home.component.scss
  src/main/webapp/site/src/app/register/register-home/register-home.component.spec.ts
  src/main/webapp/site/src/app/register/register-home/register-home.component.ts
  src/main/webapp/site/src/app/register/register-routing.module.ts
  src/main/webapp/site/src/app/register/register-teacher-complete/register-teacher-complete.component.html
  src/main/webapp/site/src/app/register/register-teacher-complete/register-teacher-complete.component.scss
  src/main/webapp/site/src/app/register/register-teacher-complete/register-teacher-complete.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher-complete/register-teacher-complete.component.ts
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.html
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.scss
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.ts
  src/main/webapp/site/src/app/register/register-teacher-google-user-already-exists/register-teacher-google-user-already-exists.component.html
  src/main/webapp/site/src/app/register/register-teacher-google-user-already-exists/register-teacher-google-user-already-exists.component.scss
  src/main/webapp/site/src/app/register/register-teacher-google-user-already-exists/register-teacher-google-user-already-exists.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher-google-user-already-exists/register-teacher-google-user-already-exists.component.ts
  src/main/webapp/site/src/app/register/register-teacher/register-teacher.component.html
  src/main/webapp/site/src/app/register/register-teacher/register-teacher.component.scss
  src/main/webapp/site/src/app/register/register-teacher/register-teacher.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher/register-teacher.component.ts
  src/main/webapp/site/src/app/register/register.component.html
  src/main/webapp/site/src/app/register/register.component.scss
  src/main/webapp/site/src/app/register/register.component.spec.ts
  src/main/webapp/site/src/app/register/register.component.ts
  src/main/webapp/site/src/app/register/register.module.ts
  src/main/webapp/site/src/app/services/config.service.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
  src/test/resources/wise.properties
Labels: Feature Request

#1397 Added side-by-side layout to homepage library; Updated to angular 6
  .angular-cli.json
  angular.json
  package.json
  src/main/webapp/site/karma.conf.js
  src/main/webapp/site/src/app/app-routing.module.ts
  src/main/webapp/site/src/app/app.module.ts
  src/main/webapp/site/src/app/home/home.component.html
  src/main/webapp/site/src/app/home/home.component.scss
  src/main/webapp/site/src/app/login/login.component.spec.ts
  src/main/webapp/site/src/app/modules/header/header.component.ts
  src/main/webapp/site/src/app/modules/library/library-project/library-project.component.scss
  src/main/webapp/site/src/app/modules/library/library.component.html
  src/main/webapp/site/src/app/modules/library/library.component.scss
  src/main/webapp/site/src/app/modules/library/library.component.ts
  src/main/webapp/site/src/app/modules/library/library.module.ts
  src/main/webapp/site/src/app/modules/shared/blurb/blurb.component.html
  src/main/webapp/site/src/app/modules/shared/blurb/blurb.component.scss
  src/main/webapp/site/src/app/modules/shared/call-to-action/call-to-action.component.html
  src/main/webapp/site/src/app/modules/shared/call-to-action/call-to-action.component.scss
  src/main/webapp/site/src/app/modules/shared/hero-section/hero-section.component.scss
  src/main/webapp/site/src/app/modules/shared/search-bar/search-bar.component.html
  src/main/webapp/site/src/app/modules/shared/search-bar/search-bar.component.scss
  src/main/webapp/site/src/app/modules/shared/search-bar/search-bar.component.ts
  src/main/webapp/site/src/app/modules/shared/select-menu/select-menu.component.html
  src/main/webapp/site/src/app/modules/shared/select-menu/select-menu.component.scss
  src/main/webapp/site/src/app/modules/shared/select-menu/select-menu.component.ts
  src/main/webapp/site/src/app/modules/shared/shared.module.ts
  src/main/webapp/site/src/app/register/register-student-form/register-student-form.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher/register-teacher.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher/register-teacher.component.ts
  src/main/webapp/site/src/app/services/config.service.ts
  src/main/webapp/site/src/app/services/library.service.ts
  src/main/webapp/site/src/app/services/user.service.ts
  src/main/webapp/site/src/app/student/add-project-dialog/add-project-dialog.component.spec.ts
  src/main/webapp/site/src/app/student/auth.guard.ts
  src/main/webapp/site/src/app/student/student-home/student-home.component.spec.ts
  src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.spec.ts
  src/main/webapp/site/src/app/student/student-run-list/student-run-list.component.spec.ts
  src/main/webapp/site/src/app/student/student.module.ts
  src/main/webapp/site/src/app/student/student.service.spec.ts
  src/main/webapp/site/src/app/student/student.service.ts
  src/main/webapp/site/src/app/teacher/auth.guard.ts
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/project-run-menu/project-run-menu.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-project-list-item/teacher-project-list-item.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-project-list/teacher-project-list.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher.module.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
  src/main/webapp/site/src/style/abstracts/_mixins.scss
  src/main/webapp/site/src/style/abstracts/_variables.scss
  src/main/webapp/site/src/style/components/_content-block.scss
  src/main/webapp/site/src/style/components/_expansion-panel.scss
  src/main/webapp/site/src/style/components/_info-block.scss
  src/main/webapp/site/src/style/layout/_content.scss
  src/main/webapp/site/src/style/themes/_dark.scss
  src/main/webapp/site/src/style/themes/_default.scss
  src/main/webapp/site/src/tsconfig.spec.json
Labels: Feature Request

#1401 Site: Styled the Sign in with Google button and login form
  package.json
  src/main/webapp/site/src/app/features/features.component.html
  src/main/webapp/site/src/app/home/home.component.html
  src/main/webapp/site/src/app/login/login.component.html
  src/main/webapp/site/src/app/login/login.component.scss
  src/main/webapp/site/src/app/login/login.component.ts
  src/main/webapp/site/src/app/login/login.module.ts
  src/main/webapp/site/src/app/modules/library/library.component.html
  src/main/webapp/site/src/app/modules/library/library.component.scss
  src/main/webapp/site/src/app/modules/shared/search-bar/search-bar.component.html
  src/main/webapp/site/src/app/modules/shared/search-bar/search-bar.component.scss
  src/main/webapp/site/src/app/modules/shared/search-bar/search-bar.component.ts
  src/main/webapp/site/src/app/modules/shared/select-menu/select-menu.component.html
  src/main/webapp/site/src/app/modules/shared/select-menu/select-menu.component.scss
  src/main/webapp/site/src/app/modules/shared/select-menu/select-menu.component.ts
  src/main/webapp/site/src/app/student/student-home/student-home.component.html
  src/main/webapp/site/src/app/student/student.component.html
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.html
  src/main/webapp/site/src/app/teacher/teacher.component.html
  src/main/webapp/site/src/assets/img/icons/g-logo.png
  src/main/webapp/site/src/index.html
  src/main/webapp/site/src/style/abstracts/_mixins.scss
  src/main/webapp/site/src/style/components/_buttons.scss
  src/main/webapp/site/src/style/components/_inputs.scss
  src/main/webapp/site/src/style/layout/_content.scss
  src/main/webapp/site/src/style/layout/_main.scss
  src/main/webapp/site/src/style/layout/_section.scss
  src/main/webapp/site/src/style/styles.scss
Labels: Feature Request

#1402 Refactored AuthorProject.saveProjectAsset. Closes #997
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/WISE5AuthorProjectController.java
Labels: Improvement

#1406 Issue 1395 share run dialog
  package-lock.json
  package.json
  src/main/java/org/wise/portal/domain/project/impl/ProjectPermission.java
  src/main/java/org/wise/portal/domain/run/impl/RunPermission.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherProjectPermissionsAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherRunPermissionsAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/run/ShareProjectRunController.java
  src/main/java/org/wise/portal/presentation/web/exception/TeacherAlreadySharedWithProjectException.java
  src/main/java/org/wise/portal/presentation/web/exception/TeacherAlreadySharedWithRunException.java
  src/main/java/org/wise/portal/presentation/web/response/SharedOwner.java
  src/main/java/org/wise/portal/presentation/web/response/SimpleResponse.java
  src/main/java/org/wise/portal/service/project/ProjectService.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/java/org/wise/portal/service/run/RunService.java
  src/main/java/org/wise/portal/service/run/impl/RunServiceImpl.java
  src/main/webapp/site/src/app/domain/run.ts
  src/main/webapp/site/src/app/teacher/project-run-menu/project-run-menu.component.html
  src/main/webapp/site/src/app/teacher/project-run-menu/project-run-menu.component.ts
  src/main/webapp/site/src/app/teacher/project.ts
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.html
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.scss
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.ts
  src/main/webapp/site/src/app/teacher/teacher.module.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
  src/test/java/org/wise/portal/presentation/web/controllers/teacher/run/ShareProjectRunControllerTest.java
Labels: Bug

#1410 Implemented showing manage my students view inside classroom manager
  gulpfile.js
  package.json
  src/main/webapp/wise5/classroomMonitor/classroomMonitorController.es6
  src/main/webapp/wise5/classroomMonitor/classroomMonitorController.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorController.js.map
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
  src/main/webapp/wise5/classroomMonitor/main.es6
  src/main/webapp/wise5/classroomMonitor/main.js
  src/main/webapp/wise5/classroomMonitor/main.js.map
  src/main/webapp/wise5/classroomMonitor/manageStudents/ManageStudentsController.es6
  src/main/webapp/wise5/classroomMonitor/manageStudents/ManageStudentsController.js
  src/main/webapp/wise5/classroomMonitor/manageStudents/ManageStudentsController.js.map
  src/main/webapp/wise5/classroomMonitor/manageStudents/manageStudents.html
Labels: Feature Request

#1415 Fixed unit tests in PortalRedesignAngular branch
  src/main/webapp/site/src/app/app.component.spec.ts
  src/main/webapp/site/src/app/home/home.component.spec.ts
  src/main/webapp/site/src/app/login/login.component.spec.ts
  src/main/webapp/site/src/app/modules/footer/footer.component.spec.ts
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.spec.ts
  src/main/webapp/site/src/app/modules/header/header-links/header-links.component.spec.ts
  src/main/webapp/site/src/app/modules/header/header-signin/header-signin.component.spec.ts
  src/main/webapp/site/src/app/modules/header/header.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-group-thumbs/library-group-thumbs.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-project-discipline-icon/library-project-discipline-icon.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-project/library-project.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library.component.spec.ts
  src/main/webapp/site/src/app/modules/shared/blurb/blurb.component.spec.ts
  src/main/webapp/site/src/app/modules/shared/call-to-action/call-to-action.component.spec.ts
  src/main/webapp/site/src/app/modules/shared/hero-section/hero-section.component.spec.ts
  src/main/webapp/site/src/app/modules/shared/search-bar/search-bar.component.spec.ts
  src/main/webapp/site/src/app/modules/shared/select-menu/select-menu.component.spec.ts
  src/main/webapp/site/src/app/register/register-student-complete/register-student-complete.component.spec.ts
  src/main/webapp/site/src/app/register/register-student-form/register-student-form.component.spec.ts
  src/main/webapp/site/src/app/register/register-student/register-student.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher-complete/register-teacher-complete.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher/register-teacher.component.spec.ts
  src/main/webapp/site/src/app/register/register.component.spec.ts
  src/main/webapp/site/src/app/services/util.service.spec.ts
  src/main/webapp/site/src/app/student/add-project-dialog/add-project-dialog.component.spec.ts
  src/main/webapp/site/src/app/student/auth.guard.spec.ts
  src/main/webapp/site/src/app/student/student-edit-profile/student-edit-profile.component.spec.ts
  src/main/webapp/site/src/app/student/student-home/student-home.component.spec.ts
  src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.spec.ts
  src/main/webapp/site/src/app/student/student-run-list/student-run-list.component.html
  src/main/webapp/site/src/app/student/student-run-list/student-run-list.component.spec.ts
  src/main/webapp/site/src/app/student/student.component.spec.ts
  src/main/webapp/site/src/app/student/student.service.spec.ts
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.spec.ts
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.ts
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list/teacher-run-list.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher.component.spec.ts
Labels: Test

#1417 Site: Styled registration pages
  package-lock.json
  package.json
  src/main/webapp/site/src/app/app.component.ts
  src/main/webapp/site/src/app/home/home.component.html
  src/main/webapp/site/src/app/home/home.component.scss
  src/main/webapp/site/src/app/home/home.component.ts
  src/main/webapp/site/src/app/login/login.component.html
  src/main/webapp/site/src/app/login/login.component.scss
  src/main/webapp/site/src/app/modules/shared/blurb/blurb.component.html
  src/main/webapp/site/src/app/modules/shared/call-to-action/call-to-action.component.html
  src/main/webapp/site/src/app/modules/shared/call-to-action/call-to-action.component.scss
  src/main/webapp/site/src/app/modules/shared/search-bar/search-bar.component.scss
  src/main/webapp/site/src/app/modules/shared/select-menu/select-menu.component.scss
  src/main/webapp/site/src/app/register/register-google-user-already-exists/register-google-user-already-exists.component.html
  src/main/webapp/site/src/app/register/register-google-user-already-exists/register-google-user-already-exists.component.spec.ts
  src/main/webapp/site/src/app/register/register-home/register-home.component.html
  src/main/webapp/site/src/app/register/register-home/register-home.component.scss
  src/main/webapp/site/src/app/register/register-home/register-home.component.spec.ts
  src/main/webapp/site/src/app/register/register-home/register-home.component.ts
  src/main/webapp/site/src/app/register/register-routing.module.ts
  src/main/webapp/site/src/app/register/register-student-complete/register-student-complete.component.html
  src/main/webapp/site/src/app/register/register-student-form/register-student-form.component.html
  src/main/webapp/site/src/app/register/register-student-form/register-student-form.component.ts
  src/main/webapp/site/src/app/register/register-student/register-student.component.html
  src/main/webapp/site/src/app/register/register-teacher-complete/register-teacher-complete.component.html
  src/main/webapp/site/src/app/register/register-teacher-complete/register-teacher-complete.component.scss
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.html
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.ts
  src/main/webapp/site/src/app/register/register-teacher-google-user-already-exists/register-teacher-google-user-already-exists.component.html
  src/main/webapp/site/src/app/register/register-teacher-google-user-already-exists/register-teacher-google-user-already-exists.component.scss
  src/main/webapp/site/src/app/register/register-teacher-google-user-already-exists/register-teacher-google-user-already-exists.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher-google-user-already-exists/register-teacher-google-user-already-exists.component.ts
  src/main/webapp/site/src/app/register/register-teacher/register-teacher.component.html
  src/main/webapp/site/src/app/register/register.component.html
  src/main/webapp/site/src/app/register/register.module.ts
  src/main/webapp/site/src/style/abstracts/_mixins.scss
  src/main/webapp/site/src/style/components/_content-block.scss
  src/main/webapp/site/src/style/components/_inputs.scss
  src/main/webapp/site/src/style/components/_notice.scss
  src/main/webapp/site/src/style/layout/_section.scss
  src/main/webapp/site/src/style/layout/_standalone.scss
  src/main/webapp/site/src/style/styles.scss
Labels: Feature Request, High

#1421 Fixed PortalRedesignAngular tests and removed some unused imports
  src/main/webapp/site/src/app/register/register-student-complete/register-student-complete.component.spec.ts
  src/main/webapp/site/src/app/register/register-student/register-student.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher-complete/register-teacher-complete.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher/register-teacher.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher.component.spec.ts
Labels: Bug
