Repository WISE-Community/WISE, pull requests merged in 2018-09, with the labels that each got.

#1404 Added the Privacy Policy & Terms of Use page
  src/main/java/org/wise/portal/presentation/web/controllers/admin/SiteController.java
  src/main/webapp/site/src/app/app-routing.module.ts
  src/main/webapp/site/src/app/app.module.ts
  src/main/webapp/site/src/app/privacy/privacy.component.html
  src/main/webapp/site/src/app/privacy/privacy.component.scss
  src/main/webapp/site/src/app/privacy/privacy.component.spec.ts
  src/main/webapp/site/src/app/privacy/privacy.component.ts
Labels: Feature Request

#1426 Implemented the teacher library with tabs
  src/main/java/org/wise/portal/dao/project/ProjectDao.java
  src/main/java/org/wise/portal/dao/project/impl/HibernateProjectDao.java
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/WISE5AuthorProjectController.java
  src/main/java/org/wise/portal/presentation/web/controllers/project/ProjectAPIController.java
  src/main/java/org/wise/portal/service/project/ProjectService.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/webapp/site/src/app/domain/projectFilterOptions.ts
  src/main/webapp/site/src/app/home/home.component.html
  src/main/webapp/site/src/app/home/home.component.spec.ts
  src/main/webapp/site/src/app/modules/library/community-library/community-library.component.html
  src/main/webapp/site/src/app/modules/library/community-library/community-library.component.scss
  src/main/webapp/site/src/app/modules/library/community-library/community-library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/community-library/community-library.component.ts
  src/main/webapp/site/src/app/modules/library/home-page-project-library/home-page-project-library.component.html
  src/main/webapp/site/src/app/modules/library/home-page-project-library/home-page-project-library.component.scss
  src/main/webapp/site/src/app/modules/library/home-page-project-library/home-page-project-library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/home-page-project-library/home-page-project-library.component.ts
  src/main/webapp/site/src/app/modules/library/library-filters/library-filters.component.html
  src/main/webapp/site/src/app/modules/library/library-filters/library-filters.component.scss
  src/main/webapp/site/src/app/modules/library/library-filters/library-filters.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-filters/library-filters.component.ts
  src/main/webapp/site/src/app/modules/library/library-project-discipline-icon/library-project-discipline-icon.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-project/library-project-details.component.html
  src/main/webapp/site/src/app/modules/library/library-project/library-project.component.html
  src/main/webapp/site/src/app/modules/library/library-project/library-project.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-project/library-project.component.ts
  src/main/webapp/site/src/app/modules/library/library.component.html
  src/main/webapp/site/src/app/modules/library/library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library.module.ts
  src/main/webapp/site/src/app/modules/library/library/library.component.html
  src/main/webapp/site/src/app/modules/library/library/library.component.scss
  src/main/webapp/site/src/app/modules/library/library/library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library/library.component.ts
  src/main/webapp/site/src/app/modules/library/libraryProject.ts
  src/main/webapp/site/src/app/modules/library/official-library/official-library.component.html
  src/main/webapp/site/src/app/modules/library/official-library/official-library.component.scss
  src/main/webapp/site/src/app/modules/library/official-library/official-library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/official-library/official-library.component.ts
  src/main/webapp/site/src/app/modules/library/personal-library/personal-library.component.html
  src/main/webapp/site/src/app/modules/library/personal-library/personal-library.component.scss
  src/main/webapp/site/src/app/modules/library/personal-library/personal-library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/personal-library/personal-library.component.ts
  src/main/webapp/site/src/app/modules/library/sampleLibraryGroups.ts
  src/main/webapp/site/src/app/modules/library/sampleLibraryProjects.ts
  src/main/webapp/site/src/app/modules/library/select-menu-test.helper.ts
  src/main/webapp/site/src/app/modules/library/teacher-project-library/teacher-project-library.component.html
  src/main/webapp/site/src/app/modules/library/teacher-project-library/teacher-project-library.component.scss
  src/main/webapp/site/src/app/modules/library/teacher-project-library/teacher-project-library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/teacher-project-library/teacher-project-library.component.ts
  src/main/webapp/site/src/app/services/library.service.ts
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.html
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.ts
  src/main/webapp/site/src/app/teacher/project.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.html
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.ts
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.html
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
Labels: Feature Request

#1416 Teacher edit profile
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/java/org/wise/portal/presentation/web/exception/IncorrectPasswordException.java
  src/main/java/org/wise/portal/service/user/UserService.java
  src/main/java/org/wise/portal/service/user/impl/UserServiceImpl.java
  src/main/webapp/site/src/app/domain/teacher.ts
  src/main/webapp/site/src/app/domain/user.ts
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.html
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.ts
  src/main/webapp/site/src/app/services/user.service.ts
  src/main/webapp/site/src/app/student/account/edit-password/edit-password.component.html
  src/main/webapp/site/src/app/student/account/edit-password/edit-password.component.scss
  src/main/webapp/site/src/app/student/account/edit-password/edit-password.component.spec.ts
  src/main/webapp/site/src/app/student/account/edit-password/edit-password.component.ts
  src/main/webapp/site/src/app/student/account/edit-profile/edit-profile.component.html
  src/main/webapp/site/src/app/student/account/edit-profile/edit-profile.component.scss
  src/main/webapp/site/src/app/student/account/edit-profile/edit-profile.component.spec.ts
  src/main/webapp/site/src/app/student/account/edit-profile/edit-profile.component.ts
  src/main/webapp/site/src/app/student/account/edit/edit.component.html
  src/main/webapp/site/src/app/student/account/edit/edit.component.scss
  src/main/webapp/site/src/app/student/account/edit/edit.component.spec.ts
  src/main/webapp/site/src/app/student/account/edit/edit.component.ts
  src/main/webapp/site/src/app/student/student-routing.module.ts
  src/main/webapp/site/src/app/student/student.module.ts
  src/main/webapp/site/src/app/student/student.service.ts
  src/main/webapp/site/src/app/teacher/account/edit-password/edit-password.component.html
  src/main/webapp/site/src/app/teacher/account/edit-password/edit-password.component.scss
  src/main/webapp/site/src/app/teacher/account/edit-password/edit-password.component.spec.ts
  src/main/webapp/site/src/app/teacher/account/edit-password/edit-password.component.ts
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.html
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.scss
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.spec.ts
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.ts
  src/main/webapp/site/src/app/teacher/account/edit/edit.component.html
  src/main/webapp/site/src/app/teacher/account/edit/edit.component.scss
  src/main/webapp/site/src/app/teacher/account/edit/edit.component.spec.ts
  src/main/webapp/site/src/app/teacher/account/edit/edit.component.ts
  src/main/webapp/site/src/app/teacher/teacher-routing.module.ts
  src/main/webapp/site/src/app/teacher/teacher.module.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
Labels: Feature Request

#1427 Added timeline view to the teacher class schedule
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/webapp/site/src/app/domain/run.ts
  src/main/webapp/site/src/app/home/home.component.scss
  src/main/webapp/site/src/app/modules/header/header-links/header-links.component.scss
  src/main/webapp/site/src/app/modules/header/header.component.ts
  src/main/webapp/site/src/app/modules/library/library.module.ts
  src/main/webapp/site/src/app/modules/shared/call-to-action/call-to-action.component.scss
  src/main/webapp/site/src/app/modules/timeline/timeline-item/timeline-item.component.html
  src/main/webapp/site/src/app/modules/timeline/timeline-item/timeline-item.component.scss
  src/main/webapp/site/src/app/modules/timeline/timeline-item/timeline-item.component.spec.ts
  src/main/webapp/site/src/app/modules/timeline/timeline-item/timeline-item.component.ts
  src/main/webapp/site/src/app/modules/timeline/timeline.module.spec.ts
  src/main/webapp/site/src/app/modules/timeline/timeline.module.ts
  src/main/webapp/site/src/app/modules/timeline/timeline/timeline.component.html
  src/main/webapp/site/src/app/modules/timeline/timeline/timeline.component.scss
  src/main/webapp/site/src/app/modules/timeline/timeline/timeline.component.spec.ts
  src/main/webapp/site/src/app/modules/timeline/timeline/timeline.component.ts
  src/main/webapp/site/src/app/student/student-run.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.html
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.scss
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.spec.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.ts
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.html
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.html
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.scss
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list/teacher-run-list.component.html
  src/main/webapp/site/src/app/teacher/teacher-run-list/teacher-run-list.component.scss
  src/main/webapp/site/src/app/teacher/teacher-run-list/teacher-run-list.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list/teacher-run-list.component.ts
  src/main/webapp/site/src/app/teacher/teacher-run.ts
  src/main/webapp/site/src/app/teacher/teacher.module.ts
  src/main/webapp/site/src/style/abstracts/_mixins.scss
  src/main/webapp/site/src/style/base/_base.scss
  src/main/webapp/site/src/style/components/_buttons.scss
  src/main/webapp/site/src/style/components/_card.scss
  src/main/webapp/site/src/style/components/_dialog.scss
  src/main/webapp/site/src/style/components/_expansion-panel.scss
  src/main/webapp/site/src/style/components/_info-block.scss
  src/main/webapp/site/src/style/layout/_content.scss
  src/main/webapp/site/src/style/styles.scss
  src/main/webapp/site/src/style/themes/_dark.scss
  src/main/webapp/site/src/style/themes/_default.scss
Labels: Feature Request

#1432 Populate language field
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
Labels: Bug

#1435 Fixed a problem with the Animation component throwing an error when it tries to import work from a connected component
  src/main/webapp/wise5/components/componentController.es6
  src/main/webapp/wise5/components/componentController.js
  src/main/webapp/wise5/components/componentController.js.map
Labels: Bug

#1436 Fixed a problem with the draw component not keeping its background when it imported work from another draw component
  src/main/webapp/wise5/components/draw/drawController.es6
  src/main/webapp/wise5/components/draw/drawController.js
  src/main/webapp/wise5/components/draw/drawController.js.map
Labels: Bug

#1468 Styled the project library and updated Site header and account menu links
  package-lock.json
  package.json
  src/main/java/org/wise/portal/presentation/web/controllers/project/ProjectAPIController.java
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.html
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.scss
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.spec.ts
  src/main/webapp/site/src/app/modules/header/header-links/header-links.component.html
  src/main/webapp/site/src/app/modules/header/header-links/header-links.component.scss
  src/main/webapp/site/src/app/modules/header/header-links/header-links.component.spec.ts
  src/main/webapp/site/src/app/modules/header/header-links/header-links.component.ts
  src/main/webapp/site/src/app/modules/header/header.component.ts
  src/main/webapp/site/src/app/modules/library/community-library/community-library.component.html
  src/main/webapp/site/src/app/modules/library/home-page-project-library/home-page-project-library.component.html
  src/main/webapp/site/src/app/modules/library/home-page-project-library/home-page-project-library.component.scss
  src/main/webapp/site/src/app/modules/library/home-page-project-library/home-page-project-library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/home-page-project-library/home-page-project-library.component.ts
  src/main/webapp/site/src/app/modules/library/library-filters/library-filters.component.html
  src/main/webapp/site/src/app/modules/library/library-filters/library-filters.component.scss
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.html
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.scss
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.ts
  src/main/webapp/site/src/app/modules/library/library-project/library-project-details.component.html
  src/main/webapp/site/src/app/modules/library/library-project/library-project.component.ts
  src/main/webapp/site/src/app/modules/library/library.module.ts
  src/main/webapp/site/src/app/modules/library/library/library.component.scss
  src/main/webapp/site/src/app/modules/library/library/library.component.ts
  src/main/webapp/site/src/app/modules/library/official-library/official-library.component.html
  src/main/webapp/site/src/app/modules/library/official-library/official-library.component.scss
  src/main/webapp/site/src/app/modules/library/official-library/official-library.component.ts
  src/main/webapp/site/src/app/modules/library/personal-library/personal-library.component.html
  src/main/webapp/site/src/app/modules/library/personal-library/personal-library.component.ts
  src/main/webapp/site/src/app/modules/library/teacher-project-library/teacher-project-library.component.html
  src/main/webapp/site/src/app/modules/library/teacher-project-library/teacher-project-library.component.scss
  src/main/webapp/site/src/app/modules/library/teacher-project-library/teacher-project-library.component.ts
  src/main/webapp/site/src/app/modules/timeline/timeline-item/timeline-item.component.scss
  src/main/webapp/site/src/app/services/library.service.ts
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.html
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.html
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.html
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.scss
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.html
  src/main/webapp/site/src/style/abstracts/_mixins.scss
  src/main/webapp/site/src/style/components/_card.scss
  src/main/webapp/site/src/style/components/_dialog.scss
  src/main/webapp/site/src/style/styles.scss
  src/main/webapp/site/src/style/themes/_dark.scss
Labels: 0 points

#1474 Show unit info for teacher run items
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/webapp/site/src/app/domain/project.ts
  src/main/webapp/site/src/app/domain/run.ts
  src/main/webapp/site/src/app/modules/library/community-library/community-library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.html
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.scss
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.ts
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.ts
  src/main/webapp/site/src/app/modules/library/library-project/library-project.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-project/library-project.component.ts
  src/main/webapp/site/src/app/modules/library/library.module.ts
  src/main/webapp/site/src/app/modules/library/libraryProject.ts
  src/main/webapp/site/src/app/modules/library/official-library/official-library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/personal-library/personal-library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/teacher-project-library/teacher-project-library.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.spec.ts
  src/main/webapp/site/src/app/services/library.service.ts
  src/main/webapp/site/src/app/student/account/edit-profile/edit-profile.component.spec.ts
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.spec.ts
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.ts
  src/main/webapp/site/src/app/teacher/project.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.html
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.spec.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.ts
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.html
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list/teacher-run-list.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
Labels: 0 points

#1462 Show shared library projects
  src/main/java/org/wise/portal/presentation/web/controllers/project/ProjectAPIController.java
  src/main/webapp/site/src/app/modules/library/library-project/library-project.component.html
  src/main/webapp/site/src/app/modules/library/library-project/library-project.component.scss
  src/main/webapp/site/src/app/modules/library/libraryProject.ts
  src/main/webapp/site/src/app/modules/library/official-library/official-library.component.ts
  src/main/webapp/site/src/app/modules/library/personal-library/personal-library.component.spec.ts
  src/main/webapp/site/src/app/modules/library/personal-library/personal-library.component.ts
  src/main/webapp/site/src/app/modules/library/teacher-project-library/teacher-project-library.component.spec.ts
  src/main/webapp/site/src/app/services/library.service.ts
Labels: 0 points

#1481 Added the manage students page to the WISE4 classroom monitor
  src/main/webapp/vle/classroomMonitor.html
  src/main/webapp/vle/view/classroomMonitor/classroomMonitorView_main.js
Labels: 0 points

#1488 Fixed a bug where the personal project count would not be updated
  src/main/webapp/site/src/app/modules/library/personal-library/personal-library.component.ts
Labels: 0 points

#1487 Fixed a problem with a copied project not displaying the "Edit" and "Share" options
  src/main/java/org/wise/portal/domain/project/Project.java
  src/main/java/org/wise/portal/domain/project/impl/ProjectImpl.java
  src/main/java/org/wise/portal/presentation/web/controllers/ControllerUtil.java
  src/main/java/org/wise/portal/presentation/web/controllers/project/ProjectAPIController.java
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.ts
Labels: 0 points

#1491 Added projectMetadata when retrieving json for a run project
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
Labels: 0 points

#1493 Added a copy project confirmation dialog with a copying indicator. #1455
  src/main/webapp/site/src/app/modules/library/copy-project-dialog/copy-project-dialog.component.html
  src/main/webapp/site/src/app/modules/library/copy-project-dialog/copy-project-dialog.component.scss
  src/main/webapp/site/src/app/modules/library/copy-project-dialog/copy-project-dialog.component.spec.ts
  src/main/webapp/site/src/app/modules/library/copy-project-dialog/copy-project-dialog.component.ts
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.ts
  src/main/webapp/site/src/app/modules/library/library.module.ts
Labels: 0 points

#1495 Styled create run, share run, and share project dialogs
  src/main/webapp/site/src/app/modules/header/header-links/header-links.component.scss
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.html
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.ts
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.ts
  src/main/webapp/site/src/app/modules/library/library-project/library-project.component.ts
  src/main/webapp/site/src/app/modules/library/library.module.ts
  src/main/webapp/site/src/app/modules/library/share-item-dialog/share-item-dialog.component.ts
  src/main/webapp/site/src/app/modules/library/share-project-dialog/share-project-dialog.component.html
  src/main/webapp/site/src/app/modules/library/share-project-dialog/share-project-dialog.component.scss
  src/main/webapp/site/src/app/modules/library/share-project-dialog/share-project-dialog.component.spec.ts
  src/main/webapp/site/src/app/modules/library/share-project-dialog/share-project-dialog.component.ts
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.html
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.scss
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.ts
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.html
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.scss
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.ts
  src/main/webapp/site/src/app/teacher/teacher.module.ts
  src/main/webapp/site/src/style/abstracts/_mixins.scss
  src/main/webapp/site/src/style/components/_dialog.scss
  src/main/webapp/site/src/style/components/_inputs.scss
  src/main/webapp/site/src/style/themes/_dark.scss
  src/main/webapp/site/src/style/themes/_default.scss
Labels: 0 points

#1505 Added the ability for students to create choices in the Match component. #1498
  src/main/webapp/wise5/components/match/authoring.html
  src/main/webapp/wise5/components/match/i18n/i18n_en.json
  src/main/webapp/wise5/components/match/index.html
  src/main/webapp/wise5/components/match/matchController.es6
  src/main/webapp/wise5/components/match/matchController.js
  src/main/webapp/wise5/components/match/matchController.js.map
Labels: 0 points
