Repository WISE-Community/WISE, pull requests merged in 2018-04, with the labels that each got.

#1111 Added controller to handle direct access to routes in angular portal
  src/main/java/org/wise/portal/presentation/web/controllers/admin/SiteController.java
Labels: Improvement

#1143 Implemented the WISE4 MySystem to WISE5 Concept Map converter
  src/main/webapp/vle/view/authoring/authorview_convert.js
Labels: Feature Request

#1147 Export: Fixed a problem with student response values creating multiple cells if they contained a comma
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.es6
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.js
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.js.map
Labels: Bug

#1139 Issue 1132 add project as student
  src/main/java/org/wise/portal/presentation/web/controllers/run/RunAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentAPIController.java
  src/main/resources/configurations/applicationContexts.xml
  src/main/webapp/site/src/app/student/add-project-dialog/add-project-dialog.component.html
  src/main/webapp/site/src/app/student/add-project-dialog/add-project-dialog.component.scss
  src/main/webapp/site/src/app/student/add-project-dialog/add-project-dialog.component.spec.ts
  src/main/webapp/site/src/app/student/add-project-dialog/add-project-dialog.component.ts
  src/main/webapp/site/src/app/student/run-info.ts
  src/main/webapp/site/src/app/student/student-run-list-item/student-run-list-item.component.html
  src/main/webapp/site/src/app/student/student-run-list/student-run-list.component.html
  src/main/webapp/site/src/app/student/student-run-list/student-run-list.component.spec.ts
  src/main/webapp/site/src/app/student/student-run-list/student-run-list.component.ts
  src/main/webapp/site/src/app/student/student-run.ts
  src/main/webapp/site/src/app/student/student.service.ts
Labels: Feature Request

#1152 Revived tests in presentation/web/controller/student. Closes #1068
  .gitignore
  .idea/compiler.xml
  pom.xml
  src/main/java/org/wise/portal/presentation/web/controllers/student/AddProjectController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentIndexController.java
  src/test/java/org/wise/portal/presentation/web/controllers/AllTests.java
  src/test/java/org/wise/portal/presentation/web/controllers/student/AddProjectControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/student/AllTests.java
  src/test/java/org/wise/portal/presentation/web/controllers/student/StudentIndexControllerTest.java
Labels: Test

#1164 Added global translation entries for the 'Previous Step' and 'Next Step' buttons
  src/main/webapp/wise5/authoringTool/components/shared/stepTools/stepTools.es6
  src/main/webapp/wise5/authoringTool/components/shared/stepTools/stepTools.js
  src/main/webapp/wise5/authoringTool/components/shared/stepTools/stepTools.js.map
  src/main/webapp/wise5/authoringTool/i18n/i18n_el.json
  src/main/webapp/wise5/authoringTool/i18n/i18n_en.json
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/stepTools/stepTools.es6
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/stepTools/stepTools.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/stepTools/stepTools.js.map
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_el.json
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
  src/main/webapp/wise5/i18n/i18n_en.json
  src/main/webapp/wise5/themes/default/themeComponents/stepTools/stepTools.html
Labels: Bug

#1163 Fixed display name bug in discussion component
  src/main/webapp/wise5/components/discussion/discussionController.es6
  src/main/webapp/wise5/components/discussion/discussionController.js
  src/main/webapp/wise5/components/discussion/discussionController.js.map
Labels: Bug

#1173 Graph Component: Minor improvements to connected component merge fields
  src/main/webapp/wise5/components/graph/graphController.es6
  src/main/webapp/wise5/components/graph/graphController.js
  src/main/webapp/wise5/components/graph/graphController.js.map
Labels: Bug

#1165 Split project service into (vle/at/cm)ProjectService
  src/main/webapp/wise5/authoringTool/authoringToolProjectService.es6
  src/main/webapp/wise5/authoringTool/authoringToolProjectService.js
  src/main/webapp/wise5/authoringTool/authoringToolProjectService.js.map
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/classroomMonitor/.editorconfig
  src/main/webapp/wise5/classroomMonitor/classroomMonitorProjectService.es6
  src/main/webapp/wise5/classroomMonitor/classroomMonitorProjectService.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorProjectService.js.map
  src/main/webapp/wise5/classroomMonitor/main.es6
  src/main/webapp/wise5/classroomMonitor/main.js
  src/main/webapp/wise5/classroomMonitor/main.js.map
  src/main/webapp/wise5/services/projectService.es6
  src/main/webapp/wise5/services/projectService.js
  src/main/webapp/wise5/services/projectService.js.map
  src/main/webapp/wise5/test-unit/services/authoringToolProjectService.spec.es6
  src/main/webapp/wise5/test-unit/services/authoringToolProjectService.spec.js
  src/main/webapp/wise5/test-unit/services/authoringToolProjectService.spec.js.map
  src/main/webapp/wise5/test-unit/services/projectService.spec.es6
  src/main/webapp/wise5/test-unit/services/projectService.spec.js
  src/main/webapp/wise5/test-unit/services/projectService.spec.js.map
  src/main/webapp/wise5/vle/main.es6
  src/main/webapp/wise5/vle/main.js
  src/main/webapp/wise5/vle/main.js.map
  src/main/webapp/wise5/vle/vleProjectService.es6
  src/main/webapp/wise5/vle/vleProjectService.js
  src/main/webapp/wise5/vle/vleProjectService.js.map
Labels: Improvement

#1159 Added authoring for enabling/disabling the public space
  src/main/webapp/wise5/authoringTool/i18n/i18n_en.json
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/authoringTool/notebook/authorNotebookController.es6
  src/main/webapp/wise5/authoringTool/notebook/authorNotebookController.js
  src/main/webapp/wise5/authoringTool/notebook/authorNotebookController.js.map
  src/main/webapp/wise5/authoringTool/notebook/notebook.html
  src/main/webapp/wise5/components/draw/drawController.es6
  src/main/webapp/wise5/components/draw/drawController.js
  src/main/webapp/wise5/components/draw/drawController.js.map
  src/main/webapp/wise5/components/openResponse/openResponseController.es6
  src/main/webapp/wise5/components/openResponse/openResponseController.js
  src/main/webapp/wise5/components/openResponse/openResponseController.js.map
  src/main/webapp/wise5/services/projectService.es6
  src/main/webapp/wise5/services/projectService.js
  src/main/webapp/wise5/services/projectService.js.map
  src/main/webapp/wise5/services/spaceService.es6
  src/main/webapp/wise5/services/spaceService.js
  src/main/webapp/wise5/services/spaceService.js.map
  src/main/webapp/wise5/test-unit/sampleData/curriculum/DemoProject/project.json
  src/main/webapp/wise5/test-unit/sampleData/curriculum/SelfPropelledVehiclesChallenge/project.json
  src/main/webapp/wise5/test-unit/services/projectService.spec.es6
  src/main/webapp/wise5/test-unit/services/projectService.spec.js
  src/main/webapp/wise5/test-unit/services/projectService.spec.js.map
  src/main/webapp/wise5/themes/default/notebook/editNotebookItem.html
  src/main/webapp/wise5/themes/default/notebook/editNotebookItemController.es6
  src/main/webapp/wise5/themes/default/notebook/editNotebookItemController.js
  src/main/webapp/wise5/themes/default/notebook/editNotebookItemController.js.map
  src/main/webapp/wise5/themes/default/notebook/notebookItem/notebookItem.es6
  src/main/webapp/wise5/themes/default/notebook/notebookItem/notebookItem.js
  src/main/webapp/wise5/themes/default/notebook/notebookItem/notebookItem.js.map
  src/main/webapp/wise5/themes/default/notebook/notebookNotes/notebookNotes.es6
  src/main/webapp/wise5/themes/default/notebook/notebookNotes/notebookNotes.js
  src/main/webapp/wise5/themes/default/notebook/notebookNotes/notebookNotes.js.map
Labels: Feature Request

#1178 Moved planning functions out of the ProjectService and into the PlanningService
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.es6
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.js.map
  src/main/webapp/wise5/classroomMonitor/classroomMonitorProjectService.es6
  src/main/webapp/wise5/classroomMonitor/classroomMonitorProjectService.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorProjectService.js.map
  src/main/webapp/wise5/classroomMonitor/main.es6
  src/main/webapp/wise5/classroomMonitor/main.js
  src/main/webapp/wise5/classroomMonitor/main.js.map
  src/main/webapp/wise5/services/planningService.es6
  src/main/webapp/wise5/services/planningService.js
  src/main/webapp/wise5/services/planningService.js.map
  src/main/webapp/wise5/services/projectService.es6
  src/main/webapp/wise5/services/projectService.js
  src/main/webapp/wise5/services/projectService.js.map
  src/main/webapp/wise5/services/studentDataService.es6
  src/main/webapp/wise5/services/studentDataService.js
  src/main/webapp/wise5/services/studentDataService.js.map
  src/main/webapp/wise5/themes/default/themeComponents/navItem/navItemController.es6
  src/main/webapp/wise5/themes/default/themeComponents/navItem/navItemController.js
  src/main/webapp/wise5/themes/default/themeComponents/navItem/navItemController.js.map
  src/main/webapp/wise5/vle/main.es6
  src/main/webapp/wise5/vle/main.js
  src/main/webapp/wise5/vle/main.js.map
Labels: Improvement
