Repository WISE-Community/WISE, pull requests merged in 2018-05, with the labels that each got.

#1188 Fixed server caching problem by appending version numbers to the end of .js files
  src/main/webapp/portal/author.jsp
  src/main/webapp/portal/classroomMonitor.jsp
  src/main/webapp/portal/student.jsp
  src/main/webapp/wise5/config.js
Labels: Improvement

#1202 Draw Component: Fixed a problem with the background image causing the student work to be immediately dirty
  src/main/webapp/wise5/components/draw/drawController.es6
  src/main/webapp/wise5/components/draw/drawController.js
  src/main/webapp/wise5/components/draw/drawController.js.map
Labels: Bug

#1201 Removed the wiseBaseURL from wise.properties and also removed usage of wiseBaseURL from java files
  src/main/java/org/wise/portal/domain/admin/DailyAdminJob.java
  src/main/java/org/wise/portal/presentation/web/controllers/InformationController.java
  src/main/java/org/wise/portal/presentation/web/controllers/StatisticsController.java
  src/main/java/org/wise/portal/presentation/web/controllers/VLEController.java
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/AuthorProjectController.java
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/WISE5AuthorProjectController.java
  src/main/java/org/wise/portal/presentation/web/controllers/forgotaccount/teacher/ForgotAccountTeacherIndexController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StartProjectController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/TeamSignInController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAccountController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/grading/GradeWorkController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/run/UpdateRunController.java
  src/main/java/org/wise/portal/service/project/ProjectService.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/resources/wise_sample.properties
  src/main/resources/wise_sample_embedded_tomcat.properties
Labels: Improvement

#1189 Updated versionBump script
  versionBump.sh
Labels: Feature Request

#1204 Verify tests for admin controllers
  .idea/compiler.xml
  pom.xml
  src/main/java/org/wise/portal/presentation/web/controllers/admin/FindProjectRunsController.java
  src/main/java/org/wise/portal/presentation/web/controllers/admin/UserInfoController.java
  src/main/java/org/wise/portal/presentation/web/controllers/admin/ViewAllUsersController.java
  src/main/webapp/portal/admin/run/manageprojectruns.jsp
  src/test/java/org/wise/portal/presentation/web/controllers/admin/AllTests.java
  src/test/java/org/wise/portal/presentation/web/controllers/admin/FindProjectRunsControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/admin/UserInfoControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/admin/ViewAllUsersControllerTest.java
Labels: Improvement, Test

#1205 Concept Map: Fixed a problem where clicking on an energy type would not properly select the energy type if the student moved the mouse
  src/main/webapp/wise5/components/conceptMap/conceptMapController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js.map
  src/main/webapp/wise5/components/conceptMap/index.html
Labels: Bug

#1210 Fixed a problem with getWebSocketURL() not working because we removed wiseBaseURL
  src/main/webapp/wise5/services/configService.es6
  src/main/webapp/wise5/services/configService.js
  src/main/webapp/wise5/services/configService.js.map
Labels: Bug

#1199 Only students should be able to access /student
  src/main/webapp/site/src/app/app.module.ts
  src/main/webapp/site/src/app/login/login.component.spec.ts
  src/main/webapp/site/src/app/login/login.component.ts
  src/main/webapp/site/src/app/services/user.service.ts
  src/main/webapp/site/src/app/student/auth.guard.spec.ts
  src/main/webapp/site/src/app/student/auth.guard.ts
  src/main/webapp/site/src/app/student/student-routing.module.ts
  src/main/webapp/site/src/app/student/student.module.ts
Labels: Feature Request

#1216 Create parent component service
  src/main/webapp/wise5/authoringTool/main.es6
  src/main/webapp/wise5/authoringTool/main.js
  src/main/webapp/wise5/authoringTool/main.js.map
  src/main/webapp/wise5/classroomMonitor/main.es6
  src/main/webapp/wise5/classroomMonitor/main.js
  src/main/webapp/wise5/classroomMonitor/main.js.map
  src/main/webapp/wise5/components/animation/animationService.es6
  src/main/webapp/wise5/components/animation/animationService.js
  src/main/webapp/wise5/components/animation/animationService.js.map
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorService.es6
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorService.js
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorService.js.map
  src/main/webapp/wise5/components/componentService.es6
  src/main/webapp/wise5/components/componentService.js
  src/main/webapp/wise5/components/componentService.js.map
  src/main/webapp/wise5/components/conceptMap/conceptMapService.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapService.js
  src/main/webapp/wise5/components/conceptMap/conceptMapService.js.map
  src/main/webapp/wise5/components/discussion/discussionService.es6
  src/main/webapp/wise5/components/discussion/discussionService.js
  src/main/webapp/wise5/components/discussion/discussionService.js.map
  src/main/webapp/wise5/components/draw/drawService.es6
  src/main/webapp/wise5/components/draw/drawService.js
  src/main/webapp/wise5/components/draw/drawService.js.map
  src/main/webapp/wise5/components/embedded/embeddedService.es6
  src/main/webapp/wise5/components/embedded/embeddedService.js
  src/main/webapp/wise5/components/embedded/embeddedService.js.map
  src/main/webapp/wise5/components/graph/graphService.es6
  src/main/webapp/wise5/components/graph/graphService.js
  src/main/webapp/wise5/components/graph/graphService.js.map
  src/main/webapp/wise5/components/html/htmlService.es6
  src/main/webapp/wise5/components/html/htmlService.js
  src/main/webapp/wise5/components/html/htmlService.js.map
  src/main/webapp/wise5/components/label/labelService.es6
  src/main/webapp/wise5/components/label/labelService.js
  src/main/webapp/wise5/components/label/labelService.js.map
  src/main/webapp/wise5/components/match/matchService.es6
  src/main/webapp/wise5/components/match/matchService.js
  src/main/webapp/wise5/components/match/matchService.js.map
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceService.es6
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceService.js
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceService.js.map
  src/main/webapp/wise5/components/openResponse/openResponseController.es6
  src/main/webapp/wise5/components/openResponse/openResponseController.js
  src/main/webapp/wise5/components/openResponse/openResponseController.js.map
  src/main/webapp/wise5/components/openResponse/openResponseService.es6
  src/main/webapp/wise5/components/openResponse/openResponseService.js
  src/main/webapp/wise5/components/openResponse/openResponseService.js.map
  src/main/webapp/wise5/components/outsideURL/outsideURLService.es6
  src/main/webapp/wise5/components/outsideURL/outsideURLService.js
  src/main/webapp/wise5/components/outsideURL/outsideURLService.js.map
  src/main/webapp/wise5/components/table/tableService.es6
  src/main/webapp/wise5/components/table/tableService.js
  src/main/webapp/wise5/components/table/tableService.js.map
  src/main/webapp/wise5/vle/main.es6
  src/main/webapp/wise5/vle/main.js
  src/main/webapp/wise5/vle/main.js.map
  src/main/webapp/wise5/vle/vleProjectService.es6
  src/main/webapp/wise5/vle/vleProjectService.js
  src/main/webapp/wise5/vle/vleProjectService.js.map
Labels: Improvement

#1207 Improved the JSON authoring view
  src/main/webapp/wise5/authoringTool/authoringToolController.es6
  src/main/webapp/wise5/authoringTool/authoringToolController.js
  src/main/webapp/wise5/authoringTool/authoringToolController.js.map
  src/main/webapp/wise5/authoringTool/components/shared/toolbar/toolbar.es6
  src/main/webapp/wise5/authoringTool/components/shared/toolbar/toolbar.js
  src/main/webapp/wise5/authoringTool/components/shared/toolbar/toolbar.js.map
  src/main/webapp/wise5/authoringTool/i18n/i18n_en.json
  src/main/webapp/wise5/authoringTool/node/node.html
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.es6
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.js
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.js.map
  src/main/webapp/wise5/authoringTool/project/project.html
  src/main/webapp/wise5/authoringTool/project/projectController.es6
  src/main/webapp/wise5/authoringTool/project/projectController.js
  src/main/webapp/wise5/authoringTool/project/projectController.js.map
  src/main/webapp/wise5/components/discussion/discussionController.es6
  src/main/webapp/wise5/components/discussion/discussionController.js
  src/main/webapp/wise5/components/discussion/discussionController.js.map
  src/main/webapp/wise5/components/discussion/index.html
  src/main/webapp/wise5/services/utilService.es6
  src/main/webapp/wise5/services/utilService.js
  src/main/webapp/wise5/services/utilService.js.map
Labels: Improvement

#1214 Concept Map: Fixed a problem with the starter concept map not showing up in the component authoring preview
  src/main/webapp/wise5/components/conceptMap/conceptMapController.es6
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js
  src/main/webapp/wise5/components/conceptMap/conceptMapController.js.map
Labels: Bug

#1221 Fixed search bug in new Site homepage library after hitting reset
  src/main/webapp/site/src/app/modules/shared/search-bar/search-bar.component.ts
  src/main/webapp/site/src/app/modules/shared/select-menu/select-menu.component.ts
Labels: Bug

#1197 Issue 1180 project service reduce nesting
  src/main/webapp/curriculum/demo/project.json
  src/main/webapp/wise5/authoringTool/authoringToolProjectService.es6
  src/main/webapp/wise5/authoringTool/authoringToolProjectService.js
  src/main/webapp/wise5/authoringTool/authoringToolProjectService.js.map
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.es6
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.js
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.js.map
  src/main/webapp/wise5/directives/globalAnnotationsList/globalAnnotationsList.es6
  src/main/webapp/wise5/directives/globalAnnotationsList/globalAnnotationsList.js
  src/main/webapp/wise5/directives/globalAnnotationsList/globalAnnotationsList.js.map
  src/main/webapp/wise5/services/annotationService.es6
  src/main/webapp/wise5/services/annotationService.js
  src/main/webapp/wise5/services/annotationService.js.map
  src/main/webapp/wise5/services/nodeService.es6
  src/main/webapp/wise5/services/nodeService.js
  src/main/webapp/wise5/services/nodeService.js.map
  src/main/webapp/wise5/services/planningService.es6
  src/main/webapp/wise5/services/planningService.js
  src/main/webapp/wise5/services/planningService.js.map
  src/main/webapp/wise5/services/projectService.es6
  src/main/webapp/wise5/services/projectService.js
  src/main/webapp/wise5/services/projectService.js.map
  src/main/webapp/wise5/services/studentDataService.es6
  src/main/webapp/wise5/services/studentDataService.js
  src/main/webapp/wise5/services/studentDataService.js.map
  src/main/webapp/wise5/test-e2e/vle/previewProject.spec.es6
  src/main/webapp/wise5/test-e2e/vle/previewProject.spec.js
  src/main/webapp/wise5/test-e2e/vle/previewProject.spec.js.map
  src/main/webapp/wise5/test-e2e/vlePage.es6
  src/main/webapp/wise5/test-e2e/vlePage.js
  src/main/webapp/wise5/test-e2e/vlePage.js.map
  src/main/webapp/wise5/test-unit/sampleData/curriculum/DemoProject/project.json
  src/main/webapp/wise5/test-unit/services/authoringToolProjectService.spec.es6
  src/main/webapp/wise5/test-unit/services/authoringToolProjectService.spec.js
  src/main/webapp/wise5/test-unit/services/authoringToolProjectService.spec.js.map
  src/main/webapp/wise5/test-unit/services/projectService.spec.es6
  src/main/webapp/wise5/test-unit/services/projectService.spec.js
  src/main/webapp/wise5/test-unit/services/projectService.spec.js.map
  src/main/webapp/wise5/themes/default/templates/topbar.html
Labels: Improvement

#1230 Styled the new Site login
  src/main/webapp/site/src/app/app-routing.module.ts
  src/main/webapp/site/src/app/app.component.html
  src/main/webapp/site/src/app/app.component.spec.ts
  src/main/webapp/site/src/app/app.component.ts
  src/main/webapp/site/src/app/app.module.ts
  src/main/webapp/site/src/app/login/login-routing.module.ts
  src/main/webapp/site/src/app/login/login.component.html
  src/main/webapp/site/src/app/login/login.component.scss
  src/main/webapp/site/src/app/login/login.component.spec.ts
  src/main/webapp/site/src/app/login/login.component.ts
  src/main/webapp/site/src/app/login/login.module.ts
  src/main/webapp/site/src/app/services/user.service.ts
  src/main/webapp/site/src/app/student/student.service.spec.ts
  src/main/webapp/site/src/assets/img/wise-web-logo-full.png
Labels: Feature Request

#1233 Issue 1218 add student names to export if owner
  src/main/java/org/wise/portal/presentation/web/controllers/InformationController.java
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExport.html
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.es6
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.js
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.js.map
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
Labels: Feature Request

#1226 Fixed an error that was thrown when a teacher tries to download an export
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.es6
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.js
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.js.map
Labels: Bug
