Repository WISE-Community/WISE, pull requests merged in 2019-04, with the labels that each got.

#1854 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: Improvement, Low

#1882 Fixed bug where teacher could not see change student password form fr…
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/management/ChangeStudentPeriodController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/management/ChangeUserPasswordController.java
  src/main/webapp/portal/teacher/management/changestudentpassword.jsp
  src/main/webapp/portal/teacher/management/viewmystudents.jsp
Labels: High

#1833 implemented warning when users choose to edit a project with a run unit
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.html
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.spec.ts
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.ts
  src/main/webapp/site/src/app/teacher/edit-run-warning-dialog/edit-run-warning-dialog.component.html
  src/main/webapp/site/src/app/teacher/edit-run-warning-dialog/edit-run-warning-dialog.component.scss
  src/main/webapp/site/src/app/teacher/edit-run-warning-dialog/edit-run-warning-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/edit-run-warning-dialog/edit-run-warning-dialog.component.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.html
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.ts
  src/main/webapp/site/src/app/teacher/teacher.module.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
  src/main/webapp/site/src/app/teacher/use-with-class-warning-dialog/use-with-class-warning-dialog.component.ts
  src/main/webapp/site/src/messages.xlf
Labels: 1 point

#1884 Add license and authors info to project metadata
  src/main/java/org/wise/portal/domain/project/ProjectMetadata.java
  src/main/java/org/wise/portal/domain/project/impl/ProjectMetadataImpl.java
  src/main/java/org/wise/portal/domain/project/impl/ProjectParameters.java
  src/main/java/org/wise/portal/presentation/web/controllers/InformationController.java
  src/main/java/org/wise/portal/presentation/web/controllers/admin/ImportProjectController.java
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/WISE5AuthorProjectController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/project/ExportProjectController.java
  src/main/java/org/wise/portal/service/project/ProjectService.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/resources/wise_sample.properties
  src/main/webapp/wise5/authoringTool/components/shared/topBar/topBar.es6
  src/main/webapp/wise5/authoringTool/components/shared/topBar/topBar.js
  src/main/webapp/wise5/authoringTool/components/shared/topBar/topBar.js.map
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/topBar/topBar.es6
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/topBar/topBar.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/topBar/topBar.js.map
  src/main/webapp/wise5/services/projectService.es6
  src/main/webapp/wise5/services/projectService.js
  src/main/webapp/wise5/services/projectService.js.map
  src/main/webapp/wise5/themes/default/templates/teacherAccountMenu.html
Labels: 0 points

#1892 adding messages.xlf to git on pre-commit hook
  .travis.yml
  package-lock.json
  package.json
  pre-commit
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.spec.ts
Labels: 0 points

#1901 Discussion Component: Fixed a problem with student input text being cleared if they were typing a reply and received a classmate reply on the same thread.
  src/main/webapp/wise5/components/discussion/classResponse.es6
  src/main/webapp/wise5/components/discussion/classResponse.js
  src/main/webapp/wise5/components/discussion/classResponse.js.map
Labels: 0 points

#1900 Audio Oscillator Component: Defaulted the stopAfterGoodDraw field to true and removed the authoring for it
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorService.es6
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorService.js
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorService.js.map
  src/main/webapp/wise5/components/audioOscillator/authoring.html
  src/main/webapp/wise5/components/audioOscillator/i18n/i18n_en.json
Labels: 0 points
