Repository WISE-Community/WISE, pull requests merged in 2019-12, with the labels that each got.

#2140 Summary for Multiple Choice with correct answer should highlight correct answer in Classroom Monitor
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/nodeInfo/nodeInfo.js
Labels: 1 point

#2142 Refactored GradeWorkController to use Authentication object
  src/main/java/org/wise/portal/domain/authentication/MutableUserDetails.java
  src/main/java/org/wise/portal/domain/authentication/impl/PersistentUserDetails.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/grading/GradeWorkController.java
  src/main/java/org/wise/portal/service/acl/AclService.java
  src/main/java/org/wise/portal/service/acl/impl/AclServiceImpl.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/java/org/wise/portal/service/run/RunService.java
  src/main/java/org/wise/portal/service/run/impl/RunServiceImpl.java
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.ts
  src/test/java/org/wise/portal/presentation/web/controllers/teacher/grading/GradeWorkControllerTest.java
Labels: 1 point

#2143 fix the bug when trying to instantly add a component after deleting a component
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.js
Labels: 1 point

#2144 Revived [Acl,User,UserDetails]Service tests
  .classpath
  pom.xml
  src/main/java/org/wise/portal/service/acl/impl/AclServiceImpl.java
  src/main/java/org/wise/portal/service/authentication/impl/UserDetailsServiceImpl.java
  src/main/java/org/wise/portal/service/user/impl/UserServiceImpl.java
  src/main/java/org/wise/portal/spring/impl/ACLContext.java
  src/test/java/org/wise/portal/service/authentication/impl/UserDetailsServiceImplTest.java
  src/test/java/org/wise/portal/service/impl/AclServiceImplTest.java
  src/test/java/org/wise/portal/service/impl/AllTests.java
  src/test/java/org/wise/portal/service/impl/UserServiceImplTest.java
  src/test/webapp/curriculum/1/project.json
Labels: 1 point

#2147 Revived RunServiceImplTest and WorkgroupServiceImplTest
  .classpath
  pom.xml
  src/main/java/org/wise/portal/domain/run/impl/RunImpl.java
  src/main/java/org/wise/portal/service/run/impl/RunServiceImpl.java
  src/main/java/org/wise/portal/service/workgroup/impl/WorkgroupServiceImpl.java
  src/test/java/org/wise/portal/service/module/impl/AllTests.java
  src/test/java/org/wise/portal/service/module/impl/CurnitServiceImplTest.java
  src/test/java/org/wise/portal/service/module/impl/ModuleServiceImplTest.java
  src/test/java/org/wise/portal/service/run/impl/AllTests.java
  src/test/java/org/wise/portal/service/run/impl/OfferingServiceImplTest.java
  src/test/java/org/wise/portal/service/run/impl/RunServiceImplTest.java
  src/test/java/org/wise/portal/service/workgroup/impl/WorkgroupServiceImplTest.java
Labels: 1 point

#2130 OER OutsideURL OER component
  src/main/webapp/wise5/components/embedded/authoring.html
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.js
  src/main/webapp/wise5/components/embedded/embeddedController.js
  src/main/webapp/wise5/components/embedded/i18n/i18n_en.json
  src/main/webapp/wise5/components/outsideURL/authoring.html
  src/main/webapp/wise5/components/outsideURL/i18n/i18n_en.json
  src/main/webapp/wise5/components/outsideURL/index.html
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringController.js
  src/main/webapp/wise5/components/outsideURL/outsideURLController.js
  src/main/webapp/wise5/components/outsideURL/outsideURLService.js
  src/main/webapp/wise5/components/outsideURL/resources.json
  src/main/webapp/wise5/test-unit/components/embedded/embeddedAuthoringController.spec.js
  src/main/webapp/wise5/test-unit/components/outsideURL/outsideURLController.spec.js
  src/main/webapp/wise5/themes/default/style/angular-material.css
  src/main/webapp/wise5/themes/default/style/angular-material.css.map
  src/main/webapp/wise5/themes/default/style/angular-material.scss
  src/main/webapp/wise5/themes/default/style/author.css
  src/main/webapp/wise5/themes/default/style/author.css.map
  src/main/webapp/wise5/themes/default/style/author.scss
  src/main/webapp/wise5/themes/default/style/modules/_component--outside.scss
  src/main/webapp/wise5/themes/default/style/monitor.css
  src/main/webapp/wise5/themes/default/style/monitor.css.map
  src/main/webapp/wise5/themes/default/style/monitor.scss
  src/main/webapp/wise5/themes/default/style/vle.css
  src/main/webapp/wise5/themes/default/style/vle.css.map
  src/main/webapp/wise5/themes/default/style/vle.scss
Labels: 4 points

#2152 Added support for jacoco
  pom.xml
Labels: 1 point

#2159 [Teacher/Student/User]APIController refactor and test
  .classpath
  .gitignore
  pom.xml
  src/main/java/org/wise/portal/domain/AccountQuestion.java
  src/main/java/org/wise/portal/domain/authentication/impl/PersistentUserDetails.java
  src/main/java/org/wise/portal/domain/run/Run.java
  src/main/java/org/wise/portal/domain/run/impl/RunImpl.java
  src/main/java/org/wise/portal/domain/user/User.java
  src/main/java/org/wise/portal/domain/user/impl/UserImpl.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/java/org/wise/portal/presentation/web/response/ErrorResponse.java
  src/main/java/org/wise/portal/presentation/web/response/LaunchRunErrorResponse.java
  src/main/java/org/wise/portal/presentation/web/response/SimpleResponse.java
  src/main/java/org/wise/portal/service/authentication/UserDetailsService.java
  src/main/java/org/wise/portal/service/project/ProjectService.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/java/org/wise/portal/service/user/impl/UserServiceImpl.java
  src/main/java/org/wise/portal/spring/impl/WebConfig.java
  src/main/webapp/site/src/app/app.module.ts
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.ts
  src/main/webapp/site/src/app/modules/shared/edit-password/edit-password.component.ts
  src/main/webapp/site/src/app/services/config.service.ts
  src/main/webapp/site/src/app/services/user.service.ts
  src/main/webapp/site/src/app/student/account/edit-profile/edit-profile.component.ts
  src/main/webapp/site/src/app/student/add-project-dialog/add-project-dialog.component.ts
  src/main/webapp/site/src/app/student/student-run.ts
  src/main/webapp/site/src/app/student/student.service.ts
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.ts
  src/main/webapp/site/src/app/teacher/run-settings-dialog/run-settings-dialog.component.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
  src/test/java/org/wise/portal/presentation/web/controllers/APIControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/AllTests.java
  src/test/java/org/wise/portal/presentation/web/controllers/ModelAndViewTests.java
  src/test/java/org/wise/portal/presentation/web/controllers/student/StudentAPIControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/user/UserAPIControllerTest.java
  src/test/webapp/curriculum/1/project.json
Labels: 2 points

#2158 Implement data explorer tool
  package-lock.json
  package.json
  src/main/webapp/wise5/components/componentController.js
  src/main/webapp/wise5/components/graph/graphController.js
  src/main/webapp/wise5/components/table/authoring.html
  src/main/webapp/wise5/components/table/i18n/i18n_en.json
  src/main/webapp/wise5/components/table/index.html
  src/main/webapp/wise5/components/table/tableAuthoringController.js
  src/main/webapp/wise5/components/table/tableController.js
  src/main/webapp/wise5/services/utilService.js
  src/main/webapp/wise5/test-unit/components/graph/graphController.spec.js
  src/main/webapp/wise5/test-unit/components/table/tableAuthoringController.spec.js
  src/main/webapp/wise5/test-unit/components/table/tableController.spec.js
  src/main/webapp/wise5/test-unit/services/utilService.spec.js
  src/main/webapp/wise5/vle/src/polyfills.ts
Labels: 4 points
