Repository WISE-Community/WISE, pull requests merged in 2019-11, with the labels that each got.

#2084 Write tests for HibernateUserDao
  .classpath
  pom.xml
  src/test/java/org/wise/portal/dao/user/impl/HibernateUserDaoTest.java
Labels: 1 point

#2096 Added a "default" satisfy criteria function for milestone report templates
  src/main/webapp/wise5/classroomMonitor/milestones/milestonesController.js
Labels: 1 point

#2087 Spring-Boot 2.2
  pom.xml
  src/main/java/org/wise/portal/presentation/web/config/GoogleOpenIdConnectConfig.java
  src/main/java/org/wise/portal/spring/impl/ACLContext.java
  src/main/java/org/wise/portal/spring/impl/WebConfig.java
  src/main/resources/application_sample.properties
  src/test/resources/application.properties
Labels: 4 points

#2092 Updated UI for milestone reports: split report content and recommendations, added tabs
  gulpfile.js
  package-lock.json
  package.json
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneDetails/milestoneDetails.js
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
  src/main/webapp/wise5/classroomMonitor/milestones/milestonesController.js
  src/main/webapp/wise5/directives/milestoneReportGraph/milestoneReportGraph.js
  src/main/webapp/wise5/style/fonts/roboto/fonts/sass/roboto.css.map
  src/main/webapp/wise5/themes/default/style/angular-material.css
  src/main/webapp/wise5/themes/default/style/angular-material.css.map
  src/main/webapp/wise5/themes/default/style/author.css
  src/main/webapp/wise5/themes/default/style/author.css.map
  src/main/webapp/wise5/themes/default/style/modules/_milestones.scss
  src/main/webapp/wise5/themes/default/style/monitor.css
  src/main/webapp/wise5/themes/default/style/monitor.css.map
  src/main/webapp/wise5/themes/default/style/vle.css
  src/main/webapp/wise5/themes/default/style/vle.css.map
Labels: 2 points

#2098 Write tests for HibernateUserDetailsDao
  .classpath
  pom.xml
  src/main/java/org/wise/portal/dao/authentication/impl/HibernateUserDetailsDao.java
  src/main/java/org/wise/portal/dao/user/impl/HibernateUserDao.java
  src/test/java/org/wise/portal/dao/authentication/impl/HibernateUserDetailsDaoTest.java
  src/test/java/org/wise/portal/dao/run/impl/HibernateRunDaoTest.java
  src/test/java/org/wise/portal/dao/user/impl/HibernateUserDaoTest.java
  src/test/java/org/wise/portal/junit/AbstractTransactionalDbTests.java
Labels: 1 point

#2099 Wrote Tests for HibernateRunStatusDao.java
  src/main/java/org/wise/portal/dao/status/RunStatusDao.java
  src/main/java/org/wise/portal/dao/status/impl/HibernateRunStatusDao.java
  src/main/java/org/wise/portal/service/vle/VLEService.java
  src/main/java/org/wise/portal/service/vle/impl/VLEServiceImpl.java
  src/test/java/org/wise/portal/dao/status/impl/HibernateRunStatusDaoTest.java
Labels: 1 point

#2103 Setting StudentDataType default to Responses in Summary Component
  package-lock.json
  package.json
  src/main/webapp/wise5/components/summary/authoring.html
Labels: 1 point

#2101 Write tests for HibernateEventDao
  src/test/java/org/wise/portal/dao/run/impl/HibernateRunDaoTest.java
  src/test/java/org/wise/portal/dao/work/impl/HibernateEventDaoTest.java
  src/test/java/org/wise/portal/junit/AbstractTransactionalDbTests.java
Labels: 1 point

#2054 Implement Notebook and Notification export on the client side like the other exports
  src/main/java/org/wise/portal/dao/achievement/HibernateAchievementDao.java
  src/main/java/org/wise/portal/dao/annotation/wise5/impl/HibernateAnnotationDao.java
  src/main/java/org/wise/portal/dao/attendance/impl/HibernateStudentAttendanceDao.java
  src/main/java/org/wise/portal/dao/crater/impl/HibernateCRaterRequestDao.java
  src/main/java/org/wise/portal/dao/newsitem/impl/HibernateNewsItemDao.java
  src/main/java/org/wise/portal/dao/notification/NotificationDao.java
  src/main/java/org/wise/portal/dao/notification/impl/HibernateNotificationDao.java
  src/main/java/org/wise/portal/dao/portal/impl/HibernatePortalStatisticsDao.java
  src/main/java/org/wise/portal/dao/project/impl/HibernateProjectDao.java
  src/main/java/org/wise/portal/dao/run/impl/HibernateRunDao.java
  src/main/java/org/wise/portal/dao/status/impl/HibernateStudentStatusDao.java
  src/main/java/org/wise/portal/dao/user/impl/HibernateUserDao.java
  src/main/java/org/wise/portal/dao/work/NotebookItemDao.java
  src/main/java/org/wise/portal/dao/work/impl/HibernateEventDao.java
  src/main/java/org/wise/portal/dao/work/impl/HibernateNotebookItemDao.java
  src/main/java/org/wise/portal/dao/work/impl/HibernateStudentAssetDao.java
  src/main/java/org/wise/portal/dao/work/impl/HibernateStudentWorkDao.java
  src/main/java/org/wise/portal/dao/workgroup/impl/HibernateWorkgroupDao.java
  src/main/java/org/wise/portal/service/vle/wise5/VLEService.java
  src/main/java/org/wise/portal/service/vle/wise5/impl/VLEServiceImpl.java
  src/main/java/org/wise/vle/web/wise5/TeacherDataController.java
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.js
Labels: 1 point

#2106 Issue 2064 allow admins to switch back to original user #2086
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.html
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.scss
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.ts
  src/main/webapp/site/src/messages.xlf
Labels: 1 point

#2111 Revert "Issue 2064 allow admins to switch back to original user #2086"
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.html
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.scss
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.ts
  src/main/webapp/site/src/messages.xlf
Labels: 1 point

#2110 Write tests for HibernateStudentWorkDao
  src/main/java/org/wise/portal/dao/work/impl/HibernateStudentWorkDao.java
  src/test/java/org/wise/portal/dao/work/impl/HibernateStudentWorkDaoTest.java
Labels: 1 point

#2118 Write tests for HibernateNotificationDao
  src/main/java/org/wise/portal/dao/notification/impl/HibernateNotificationDao.java
  src/test/java/org/wise/portal/dao/notification/impl/HibernateNotificationDaoTest.java
Labels: 1 point

#2108 Write tests for HibernateStudentStatusDao
  src/main/java/org/wise/portal/dao/status/StudentStatusDao.java
  src/main/java/org/wise/portal/dao/status/impl/HibernateStudentStatusDao.java
  src/main/java/org/wise/portal/service/vle/VLEService.java
  src/main/java/org/wise/portal/service/vle/impl/VLEServiceImpl.java
  src/test/java/org/wise/portal/dao/status/impl/HibernateStudentStatusDaoTest.java
Labels: 1 point

#2122 Wrote tests in HibernateStudentAssetDaoTest.java. #2121
  src/main/java/org/wise/portal/dao/work/impl/HibernateStudentAssetDao.java
  src/test/java/org/wise/portal/dao/work/impl/HibernateStudentAssetDaoTest.java
Labels: 1 point

#2120 Write tests for HibernateWorkgroupDao
  .classpath
  pom.xml
  src/test/java/org/wise/portal/dao/workgroup/impl/AllTests.java
  src/test/java/org/wise/portal/dao/workgroup/impl/HibernateWorkgroupDaoAnotherTest.java
  src/test/java/org/wise/portal/dao/workgroup/impl/HibernateWorkgroupDaoTest.java
Labels: 1 point

#2124 Implemented some HibernateDao tests. #2123
  .classpath
  pom.xml
  src/main/java/org/wise/portal/dao/portal/impl/HibernatePortalStatisticsDao.java
  src/main/java/org/wise/portal/dao/statistics/impl/HibernateVLEStatisticsDao.java
  src/test/java/org/wise/portal/dao/achievement/HibernateAchievementDaoTest.java
  src/test/java/org/wise/portal/dao/attendance/HibernateStudentAttendanceDaoTest.java
  src/test/java/org/wise/portal/dao/authentication/impl/AllTests.java
  src/test/java/org/wise/portal/dao/group/impl/AllTests.java
  src/test/java/org/wise/portal/dao/newsitem/impl/AllTests.java
  src/test/java/org/wise/portal/dao/newsitem/impl/HibernateNewsItemDaoTest.java
  src/test/java/org/wise/portal/dao/newsitem/impl/HibernateNewsItemTest.java
  src/test/java/org/wise/portal/dao/premadecomment/impl/AllTests.java
  src/test/java/org/wise/portal/dao/run/impl/HibernateRunDaoTest.java
  src/test/java/org/wise/portal/dao/statistics/impl/HibernatePortalStatisticsDaoTest.java
  src/test/java/org/wise/portal/dao/statistics/impl/HibernateVLEStatisticsDaoTest.java
  src/test/java/org/wise/portal/dao/user/impl/AllTests.java
  src/test/java/org/wise/portal/dao/user/impl/HibernateUserDaoTest.java
  src/test/java/org/wise/portal/junit/AbstractTransactionalDbTests.java
Labels: 1 point

#2114 Allow admins to switch back to original user
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.html
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.scss
  src/main/webapp/site/src/app/modules/header/header-account-menu/header-account-menu.component.ts
  src/main/webapp/site/src/messages.xlf
Labels: 1 point

#2127 Issue 851 update hibernate criteria
  .classpath
  pom.xml
  src/main/java/org/wise/portal/dao/portal/impl/HibernatePortalStatisticsDao.java
  src/main/java/org/wise/portal/dao/statistics/impl/HibernateVLEStatisticsDao.java
  src/test/java/org/wise/portal/dao/achievement/HibernateAchievementDaoTest.java
  src/test/java/org/wise/portal/dao/attendance/HibernateStudentAttendanceDaoTest.java
  src/test/java/org/wise/portal/dao/authentication/impl/AllTests.java
  src/test/java/org/wise/portal/dao/group/impl/AllTests.java
  src/test/java/org/wise/portal/dao/newsitem/impl/AllTests.java
  src/test/java/org/wise/portal/dao/newsitem/impl/HibernateNewsItemDaoTest.java
  src/test/java/org/wise/portal/dao/newsitem/impl/HibernateNewsItemTest.java
  src/test/java/org/wise/portal/dao/premadecomment/impl/AllTests.java
  src/test/java/org/wise/portal/dao/run/impl/HibernateRunDaoTest.java
  src/test/java/org/wise/portal/dao/statistics/impl/HibernatePortalStatisticsDaoTest.java
  src/test/java/org/wise/portal/dao/statistics/impl/HibernateVLEStatisticsDaoTest.java
  src/test/java/org/wise/portal/dao/user/impl/AllTests.java
  src/test/java/org/wise/portal/dao/user/impl/HibernateUserDaoTest.java
  src/test/java/org/wise/portal/junit/AbstractTransactionalDbTests.java
Labels: 1 point

#2097 Upgrade AngularJS 1.5.11 -> 1.7.8
  package-lock.json
  package.json
  src/main/java/org/wise/portal/presentation/web/controllers/VLEController.java
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/AuthorProjectController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/grading/GradeWorkController.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.ts
  src/main/webapp/vle/view/authoring/authorview_convert.js
  src/main/webapp/wise5/authoringTool/main/authoringToolMainController.js
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.js
  src/main/webapp/wise5/authoringTool/project/projectController.js
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.js
  src/main/webapp/wise5/components/conceptMap/index.html
  src/main/webapp/wise5/components/draw/index.html
  src/main/webapp/wise5/test-e2e/authoringTool/info/info.spec.js
  src/main/webapp/wise5/test-e2e/authoringTool/node/node.spec.js
  src/main/webapp/wise5/test-e2e/authoringTool/notebook/notebook.spec.js
  src/main/webapp/wise5/test-e2e/authoringTool/project/project.spec.js
  src/main/webapp/wise5/test-e2e/authoringTool/projectList/projectList.spec.js
  src/main/webapp/wise5/test-e2e/classroomMonitor/classroomMonitor.spec.js
Labels: 2 points

#2132 Show access denied page if user doesn't have access to run2
  .classpath
  pom.xml
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/grading/GradeWorkController.java
  src/main/java/org/wise/portal/service/run/RunService.java
  src/main/java/org/wise/portal/service/run/impl/RunServiceImpl.java
  src/test/java/org/wise/portal/presentation/web/controllers/teacher/grading/GradeWorkControllerTest.java
Labels: 2 points

#2134 Revived group newsitem premadecomment project student service tests
  .classpath
  pom.xml
  src/main/java/org/wise/portal/domain/premadecomment/impl/PremadeCommentImpl.java
  src/main/java/org/wise/portal/service/group/impl/GroupServiceImpl.java
  src/main/java/org/wise/portal/service/newsitem/NewsItemService.java
  src/main/java/org/wise/portal/service/newsitem/impl/NewsItemServiceImpl.java
  src/main/java/org/wise/portal/service/premadecomment/impl/PremadeCommentServiceImpl.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/java/org/wise/portal/service/run/impl/RunServiceImpl.java
  src/test/java/org/wise/portal/service/group/impl/GroupServiceImplTest.java
  src/test/java/org/wise/portal/service/newsitem/impl/AllTests.java
  src/test/java/org/wise/portal/service/newsitem/impl/NewsItemServiceImplTest.java
  src/test/java/org/wise/portal/service/premadecomment/impl/PremadeCommentServiceImplTest.java
  src/test/java/org/wise/portal/service/project/impl/AllTests.java
  src/test/java/org/wise/portal/service/project/impl/ProjectServiceImplTest.java
  src/test/java/org/wise/portal/service/student/impl/StudentServiceImplTest.java
  src/test/java/org/wise/vle/utils/FileManagerTest.java
  src/test/resources/application.properties
  src/test/webapp/curriculum/1/license.txt
  src/test/webapp/curriculum/1/project.json
Labels: 2 points

#2126 Issue 1947 add link to translation tool in footer
  src/main/webapp/site/src/app/modules/footer/footer.component.html
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.html
  src/main/webapp/site/src/messages.xlf
Labels: 1 point
