Repository WISE-Community/WISE, pull requests merged in 2020-09, with the labels that each got.

#2587 Period names with a space do not work properly in manage students view
  src/main/webapp/portal/teacher/management/viewmystudents.jsp
Labels: 1 point

#2579 Reverted node-id attribute to AngularJS notation
  src/main/webapp/wise5/themes/default/themeComponents/navItem/navItem.html
  src/main/webapp/wise5/themes/default/themeComponents/stepTools/stepTools.html
Labels: 1 point

#2575 Remove componentAdvancedButtonClicked event
  src/main/webapp/wise5/authoringTool/node/node.html
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/components/componentController.ts
Labels: 1 point

#2573 Admin sees zero workgroups in periods when viewing Classroom Monitor
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/run/TeacherRunAPIController.java
Labels: 1 point

#2590 Fixed style conflict that was causing invisible cells in table component
  src/main/webapp/wise5/themes/default/style/author.css
  src/main/webapp/wise5/themes/default/style/author.css.map
  src/main/webapp/wise5/themes/default/style/modules/_table.scss
  src/main/webapp/wise5/themes/default/style/monitor.css
  src/main/webapp/wise5/themes/default/style/monitor.css.map
  src/main/webapp/wise5/themes/default/style/vle.css
  src/main/webapp/wise5/themes/default/style/vle.css.map
Labels: 1 point

#2586 Fixed issue where component revision dialog showed blank
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentRevisions/workgroupComponentRevisions.ts
Labels: 1 point

#2592 Classroom Monitor select All Periods label bug
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/periodSelect/periodSelect.ts
Labels: 1 point

#2577 Refactored code in projectController
  src/main/webapp/wise5/authoringTool/project/project.html
  src/main/webapp/wise5/authoringTool/project/projectController.ts
Labels: 1 point

#2594 Removed events: componentCompleted, nodeSaveClicked, showRevisions
  src/main/webapp/wise5/components/animation/animationController.ts
  src/main/webapp/wise5/components/animation/authoring.html
  src/main/webapp/wise5/components/animation/index.html
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/conceptMap/authoring.html
  src/main/webapp/wise5/components/conceptMap/index.html
  src/main/webapp/wise5/components/draw/authoring.html
  src/main/webapp/wise5/components/draw/index.html
  src/main/webapp/wise5/components/openResponse/authoring.html
  src/main/webapp/wise5/components/openResponse/i18n/i18n_ar.json
  src/main/webapp/wise5/components/openResponse/i18n/i18n_el.json
  src/main/webapp/wise5/components/openResponse/i18n/i18n_en.json
  src/main/webapp/wise5/components/openResponse/i18n/i18n_zh_CN.json
  src/main/webapp/wise5/components/openResponse/i18n/i18n_zh_TW.json
  src/main/webapp/wise5/components/openResponse/index.html
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/themes/default/templates/componentRevisions.html
  src/main/webapp/wise5/themes/default/themeController.js
  src/main/webapp/wise5/vle/node/nodeController.ts
Labels: 1 point

#2600 Import graph doesn't display imported graph in Graphing Stories project
  src/main/webapp/wise5/components/graph/graphController.ts
Labels: 1 point

#2603 Merged student gating feature from SCORE
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/run/TeacherRunAPIController.java
  src/main/java/org/wise/portal/spring/data/redis/RedisMessageSubscriber.java
  src/main/webapp/site/src/app/services/sampleData/curriculum/TeacherProjectServiceSpec.project.json
  src/main/webapp/site/src/app/services/teacherProjectService.spec.ts
  src/main/webapp/wise5/authoringTool/i18n/i18n_en.json
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/pauseScreensMenu/pauseScreensMenu.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/topBar/topBar.ts
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
  src/main/webapp/wise5/services/projectService.ts
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/services/studentWebSocketService.ts
  src/main/webapp/wise5/services/teacherProjectService.ts
  src/main/webapp/wise5/services/teacherWebSocketService.ts
  src/main/webapp/wise5/themes/default/themeController.js
  src/main/webapp/wise5/vle/i18n/i18n_en.json
  src/main/webapp/wise5/vle/vleController.ts
Labels: 2 points, 4 points

#2597 Converted componentStudentDataChanged event to observable
  src/main/webapp/wise5/components/animation/animationController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/discussion/discussionController.ts
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/vle/node/nodeController.ts
  src/main/webapp/wise5/vle/vleController.ts
Labels: 1 point

#2601 Extracted AT import component feature
  src/main/webapp/site/src/app/hybrid-module.ts
  src/main/webapp/wise5/authoringTool/importComponent/choose-component-location.component.html
  src/main/webapp/wise5/authoringTool/importComponent/choose-component-location.component.ts
  src/main/webapp/wise5/authoringTool/importComponent/choose-component.component.html
  src/main/webapp/wise5/authoringTool/importComponent/choose-component.component.ts
  src/main/webapp/wise5/authoringTool/importComponent/importComponentModule.ts
  src/main/webapp/wise5/authoringTool/node/node.html
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/teacher/teacher-angular-js-module.ts
Labels: 2 points

#2595 Implement Match component latest revision export
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExport.html
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.ts
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
Labels: 1 point

#2604 Issue 2581 replace logout event with observables
  .project
  src/main/webapp/site/src/app/services/animationService.spec.ts
  src/main/webapp/site/src/app/services/audioOscillatorService.spec.ts
  src/main/webapp/site/src/app/services/conceptMapService.spec.ts
  src/main/webapp/site/src/app/services/discussionService.spec.ts
  src/main/webapp/site/src/app/services/drawService.spec.ts
  src/main/webapp/site/src/app/services/embeddedService.spec.ts
  src/main/webapp/site/src/app/services/graphService.spec.ts
  src/main/webapp/site/src/app/services/htmlService.spec.ts
  src/main/webapp/site/src/app/services/labelService.spec.ts
  src/main/webapp/site/src/app/services/matchService.spec.ts
  src/main/webapp/site/src/app/services/milestoneService.spec.ts
  src/main/webapp/site/src/app/services/multipleChoiceService.spec.ts
  src/main/webapp/site/src/app/services/notebookService.spec.ts
  src/main/webapp/site/src/app/services/notificationService.spec.ts
  src/main/webapp/site/src/app/services/openResponseService.spec.ts
  src/main/webapp/site/src/app/services/outsideURLService.spec.ts
  src/main/webapp/site/src/app/services/projectAssetService.spec.ts
  src/main/webapp/site/src/app/services/projectService.spec.ts
  src/main/webapp/site/src/app/services/spaceService.spec.ts
  src/main/webapp/site/src/app/services/studentDataService.spec.ts
  src/main/webapp/site/src/app/services/studentStatusService.spec.ts
  src/main/webapp/site/src/app/services/summaryService.spec.ts
  src/main/webapp/site/src/app/services/tableService.spec.ts
  src/main/webapp/site/src/app/services/tagService.spec.ts
  src/main/webapp/site/src/app/services/teacherProjectService.spec.ts
  src/main/webapp/site/src/app/services/vleProjectService.spec.ts
  src/main/webapp/wise5/authoringTool/authoringToolController.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorController.ts
  src/main/webapp/wise5/services/projectService.ts
  src/main/webapp/wise5/services/sessionService.ts
  src/main/webapp/wise5/services/teacherProjectService.ts
  src/main/webapp/wise5/teacher/teacher-angular-js-module.ts
  src/main/webapp/wise5/vle/student-angular-js-module.ts
  src/main/webapp/wise5/vle/studentAsset/studentAssetController.ts
  src/main/webapp/wise5/vle/vleController.ts
  src/main/webapp/wise5/vle/vleProjectService.ts
Labels: 1 point

#2582 Limit first name and last name to English alphabet characters when creating an account
  src/main/java/org/wise/portal/domain/authentication/impl/StudentUserDetails.java
  src/main/java/org/wise/portal/domain/authentication/impl/TeacherUserDetails.java
  src/main/java/org/wise/portal/presentation/web/controllers/InformationController.java
  src/main/java/org/wise/portal/presentation/web/controllers/student/StudentAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/java/org/wise/portal/presentation/web/error/CustomGlobalExceptionHandler.java
  src/main/java/org/wise/portal/presentation/web/exception/InvalidNameException.java
  src/main/webapp/site/src/app/http-error.interceptor.ts
  src/main/webapp/site/src/app/register/register-student-form/register-student-form.component.html
  src/main/webapp/site/src/app/register/register-student-form/register-student-form.component.spec.ts
  src/main/webapp/site/src/app/register/register-student-form/register-student-form.component.ts
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.html
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.spec.ts
  src/main/webapp/site/src/app/register/register-teacher-form/register-teacher-form.component.ts
  src/main/webapp/site/src/app/register/register-user-form/register-user-form-spec-helpers.ts
  src/main/webapp/site/src/app/register/register-user-form/register-user-form.component.ts
  src/main/webapp/site/src/app/services/user.service.ts
  src/main/webapp/site/src/app/student/student.service.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.ts
  src/test/java/org/wise/portal/presentation/web/controllers/student/StudentAPIControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/user/UserAPIControllerTest.java
Labels: 1 point

#2607 Extracted add component feature into its own route.
  src/main/webapp/wise5/authoringTool/addComponent/addComponentModule.ts
  src/main/webapp/wise5/authoringTool/addComponent/choose-new-component-location.component.html
  src/main/webapp/wise5/authoringTool/addComponent/choose-new-component-location.component.ts
  src/main/webapp/wise5/authoringTool/addComponent/choose-new-component.component.html
  src/main/webapp/wise5/authoringTool/addComponent/choose-new-component.component.ts
  src/main/webapp/wise5/authoringTool/node/node.html
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#2609 Removed unused events, studentsOnline, timeSpent columns
  src/main/resources/i18n/i18n_ar.properties
  src/main/webapp/site/src/app/services/sampleData/i18n/common/i18n_en.json
  src/main/webapp/site/src/app/services/sampleData/i18n/common/i18n_ja.json
  src/main/webapp/site/src/app/services/sampleData/sample_i18n_common_en.json
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/workgroupsOnNode/workgroupsOnNode.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/workgroupsOnNode/workgroupsOnNodeDialog.html
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_ar.json
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_el.json
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_zh_CN.json
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_zh_TW.json
  src/main/webapp/wise5/classroomMonitor/studentProgress/studentProgress.html
  src/main/webapp/wise5/classroomMonitor/studentProgress/studentProgressController.ts
  src/main/webapp/wise5/components/graph/i18n/i18n_ar.json
  src/main/webapp/wise5/i18n/i18n_ar.json
  src/main/webapp/wise5/services/studentStatusService.ts
  src/main/webapp/wise5/services/teacherDataService.ts
  src/main/webapp/wise5/services/teacherWebSocketService.ts
  src/main/webapp/wise5/test-unit/sampleData/i18n/common/i18n_en.json
  src/main/webapp/wise5/test-unit/sampleData/i18n/common/i18n_ja.json
  src/main/webapp/wise5/vle/i18n/i18n_ar.json
Labels: 1 point

#2611 Extracted edit node rubric feature
  src/main/webapp/wise5/authoringTool/authoringToolController.ts
  src/main/webapp/wise5/authoringTool/node/editRubric/edit-rubric.component.html
  src/main/webapp/wise5/authoringTool/node/editRubric/edit-rubric.component.ts
  src/main/webapp/wise5/authoringTool/node/editRubric/editRubricModule.ts
  src/main/webapp/wise5/authoringTool/node/node.html
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#2613 Update OER thumbnail urls
  src/main/webapp/wise5/components/outsideURL/resources.json
Labels: 1 point

#2615 Replace openAssetChooser and assetSelected events
  src/main/webapp/site/src/app/services/projectAssetService.ts
  src/main/webapp/wise5/authoringTool/advanced/advancedAuthoringController.ts
  src/main/webapp/wise5/authoringTool/asset/projectAssetController.ts
  src/main/webapp/wise5/authoringTool/authoringToolController.ts
  src/main/webapp/wise5/authoringTool/info/projectInfoController.ts
  src/main/webapp/wise5/authoringTool/node/editRubric/edit-rubric.component.ts
  src/main/webapp/wise5/authoringTool/notebook/authorNotebookController.ts
  src/main/webapp/wise5/authoringTool/notebook/notebookAuthoring.html
  src/main/webapp/wise5/authoringTool/rubric/rubricAuthoringController.ts
  src/main/webapp/wise5/components/animation/animationAuthoringController.ts
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.ts
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.ts
  src/main/webapp/wise5/components/draw/drawAuthoringController.ts
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.ts
  src/main/webapp/wise5/components/graph/graphAuthoringController.ts
  src/main/webapp/wise5/components/html/htmlAuthoringController.ts
  src/main/webapp/wise5/components/label/labelAuthoringController.ts
  src/main/webapp/wise5/components/match/matchAuthoringController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.ts
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.ts
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringController.ts
  src/main/webapp/wise5/components/table/tableAuthoringController.ts
  src/main/webapp/wise5/services/utilService.ts
Labels: 1 point

#2619 Replace currentNodeChanged and currentStepChanged events with an observable
  src/main/webapp/wise5/authoringTool/components/shared/stepTools/stepTools.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/stepTools/stepTools.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nodeProgressView/nodeProgressView.ts
  src/main/webapp/wise5/directives/wiselink/wiselink.js
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/services/teacherDataService.ts
  src/main/webapp/wise5/themes/default/themeComponents/stepTools/stepToolsController.js
  src/main/webapp/wise5/themes/default/themeController.js
  src/main/webapp/wise5/vle/vleController.ts
Labels: 1 point

#2617 Replace currentPeriodChanged event with observables
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneDetails/milestoneDetails.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/periodSelect/periodSelect.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupSelect/workgroupSelect.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/studentGrading/studentGradingTools/studentGradingTools.ts
  src/main/webapp/wise5/classroomMonitor/milestones/milestonesController.ts
  src/main/webapp/wise5/classroomMonitor/studentGrading/studentGradingController.ts
  src/main/webapp/wise5/services/teacherDataService.ts
Labels: 1 point

#2623 Replace openWISELinkChooser and createWISELink events
  src/main/webapp/wise5/authoringTool/authoringToolController.ts
  src/main/webapp/wise5/authoringTool/wiseLink/wiseLinkAuthoringController.ts
  src/main/webapp/wise5/components/html/htmlAuthoringController.ts
  src/main/webapp/wise5/services/utilService.ts
Labels: 1 point

#2625 Extract common methods to parent [Student/Teacher]DataService
  src/main/webapp/site/src/app/services/data.service.spec.ts
  src/main/webapp/site/src/app/services/data.service.ts
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/services/teacherDataService.ts
Labels: 1 point

#2627 Refactor createWISELinkLinkElement and createWISELinkButtonElement functions
  src/main/webapp/wise5/authoringTool/wiseLink/wiseLinkAuthoring.html
  src/main/webapp/wise5/components/html/htmlAuthoringController.ts
Labels: 1 point

#2629 JS error after wise link/button click
  src/main/webapp/wise5/directives/wiselink/wiselink.js
Labels: 1 point

#2644 Replace achievementCompleted, newStudentAchievement, and studentWorkSavedToServer events
  src/main/webapp/wise5/classroomMonitor/milestones/milestonesController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/discussion/discussionController.ts
  src/main/webapp/wise5/components/draw/drawController.ts
  src/main/webapp/wise5/components/embedded/embeddedController.ts
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/components/summary/summaryController.ts
  src/main/webapp/wise5/components/table/tableController.ts
  src/main/webapp/wise5/directives/componentAnnotations/componentAnnotations.js
  src/main/webapp/wise5/directives/summaryDisplay/summaryDisplay.js
  src/main/webapp/wise5/services/achievementService.ts
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/services/teacherWebSocketService.ts
Labels: 1 point

#2642 Replace serverConnected, serverDisconnected, showSessionWarning, viewCurrentAmbientNotification events
  src/main/webapp/wise5/authoringTool/authoringToolController.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorController.ts
  src/main/webapp/wise5/services/httpInterceptor.js
  src/main/webapp/wise5/services/notificationService.ts
  src/main/webapp/wise5/services/sessionService.ts
  src/main/webapp/wise5/themes/default/themeController.js
  src/main/webapp/wise5/vle/vleController.ts
Labels: 1 point

#2636 Replace notebook events with observables
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapController.ts
  src/main/webapp/wise5/components/draw/drawController.ts
  src/main/webapp/wise5/components/embedded/embeddedController.ts
  src/main/webapp/wise5/components/graph/graphController.ts
  src/main/webapp/wise5/components/label/labelController.ts
  src/main/webapp/wise5/components/match/matchController.ts
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/components/table/tableController.ts
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/services/notebookService.ts
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/themes/default/notebook/notebook/notebook.js
  src/main/webapp/wise5/themes/default/notebook/notebookItem/notebookItem.js
  src/main/webapp/wise5/themes/default/notebook/notebookNotes/notebookNotes.js
  src/main/webapp/wise5/themes/default/notebook/notebookReport/notebookReport.js
  src/main/webapp/wise5/vle/vleController.ts
Labels: 1 point

#2638 Replace siblingComponentStudentDataChanged event with an observable
  src/main/webapp/wise5/components/embedded/embeddedController.ts
  src/main/webapp/wise5/services/nodeService.ts
  src/main/webapp/wise5/vle/node/nodeController.ts
Labels: 1 point

#2640 Replace setGlobalMessage and setIsJSONValid events
  src/main/webapp/wise5/authoringTool/advanced/advancedAuthoringController.ts
  src/main/webapp/wise5/authoringTool/authoringToolController.ts
  src/main/webapp/wise5/authoringTool/components/shared/toolbar/toolbar.ts
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/components/animation/animationAuthoringController.ts
  src/main/webapp/wise5/components/animation/animationController.ts
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.ts
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapController.ts
  src/main/webapp/wise5/components/discussion/discussionController.ts
  src/main/webapp/wise5/components/draw/drawAuthoringController.ts
  src/main/webapp/wise5/components/draw/drawController.ts
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.ts
  src/main/webapp/wise5/components/embedded/embeddedController.ts
  src/main/webapp/wise5/components/graph/graphAuthoringController.ts
  src/main/webapp/wise5/components/graph/graphController.ts
  src/main/webapp/wise5/components/html/htmlAuthoringController.ts
  src/main/webapp/wise5/components/html/htmlController.ts
  src/main/webapp/wise5/components/label/labelAuthoringController.ts
  src/main/webapp/wise5/components/label/labelController.ts
  src/main/webapp/wise5/components/match/matchAuthoringController.ts
  src/main/webapp/wise5/components/match/matchController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.ts
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringController.ts
  src/main/webapp/wise5/components/outsideURL/outsideURLController.ts
  src/main/webapp/wise5/components/summary/summaryAuthoringController.ts
  src/main/webapp/wise5/components/summary/summaryController.ts
  src/main/webapp/wise5/components/table/tableAuthoringController.ts
  src/main/webapp/wise5/components/table/tableController.ts
  src/main/webapp/wise5/services/notificationService.ts
  src/main/webapp/wise5/services/utilService.ts
Labels: 1 point

#2662 Replace savingProject, errorSavingProject, and projectSaved events
  src/main/webapp/wise5/authoringTool/authoringToolController.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.ts
  src/main/webapp/wise5/classroomMonitor/studentGrading/studentGradingController.ts
  src/main/webapp/wise5/services/projectService.ts
Labels: 1 point

#2660 Replace componentDirty, componentSubmitDirty, componentSaveTriggered, and componentSubmitTriggered events
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/discussion/discussionController.ts
  src/main/webapp/wise5/components/embedded/embeddedController.ts
  src/main/webapp/wise5/components/match/matchController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.ts
  src/main/webapp/wise5/components/table/tableController.ts
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/vle/node/nodeController.ts
Labels: 1 point

#2657 Replace nodeClickLocked and showStudentAssets events
  src/main/webapp/wise5/services/studentAssetService.ts
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/themes/default/themeController.js
  src/main/webapp/wise5/vle/node/nodeController.ts
  src/main/webapp/wise5/vle/studentAsset/studentAssetController.ts
Labels: 1 point

#2655 Replace exit and exitNode events
  src/main/webapp/site/src/app/services/data.service.ts
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/discussion/discussionController.ts
  src/main/webapp/wise5/components/embedded/embeddedController.ts
  src/main/webapp/wise5/components/graph/graphController.ts
  src/main/webapp/wise5/components/label/labelController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.ts
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/components/table/tableController.ts
  src/main/webapp/wise5/services/sessionService.ts
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/services/teacherDataService.ts
  src/main/webapp/wise5/vle/node/nodeController.ts
  src/main/webapp/wise5/vle/vleController.ts
Labels: 1 point

#2672 EmbeddedController ngOnDestroy() duplication
  src/main/webapp/wise5/components/embedded/embeddedController.ts
  src/main/webapp/wise5/components/match/matchController.ts
Labels: 1 point

#2664 Remove unused events
  src/main/webapp/site/src/app/services/studentDataService.spec.ts
  src/main/webapp/wise5/authoringTool/authoringToolController.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorController.ts
  src/main/webapp/wise5/services/milestoneService.ts
  src/main/webapp/wise5/services/projectService.ts
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/themes/default/themeController.js
Labels: 1 point

#2669 Replace projectChanged and componentShowSubmitButtonValueChanged events
  src/main/webapp/wise5/authoringTool/components/shared/stepTools/stepTools.ts
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/services/nodeService.ts
  src/main/webapp/wise5/services/projectService.ts
Labels: 1 point

#2652 Replace currentWorkgroupChanged and notificationChanged events
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nodeProgressView/nodeProgressView.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/topBar/topBar.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupSelect/workgroupSelect.ts
  src/main/webapp/wise5/classroomMonitor/studentGrading/studentGradingController.ts
  src/main/webapp/wise5/classroomMonitor/studentProgress/studentProgressController.ts
  src/main/webapp/wise5/services/notificationService.ts
  src/main/webapp/wise5/services/teacherDataService.ts
  src/main/webapp/wise5/vle/vleController.ts
Labels: 1 point

#2671 Replace displayGlobalAnnotations and studentStatusReceived events
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.ts
  src/main/webapp/wise5/classroomMonitor/studentProgress/studentProgressController.ts
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/directives/globalAnnotations/globalAnnotations.js
  src/main/webapp/wise5/services/annotationService.ts
  src/main/webapp/wise5/services/studentStatusService.ts
  src/main/webapp/wise5/services/teacherWebSocketService.ts
Labels: 1 point

#2633 Replace doneRenderingComponent and componentDoneUnloading events
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/components/animation/animationAuthoringController.ts
  src/main/webapp/wise5/components/animation/animationController.ts
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.ts
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapController.ts
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.ts
  src/main/webapp/wise5/components/discussion/discussionController.ts
  src/main/webapp/wise5/components/draw/drawController.ts
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.ts
  src/main/webapp/wise5/components/embedded/embeddedController.ts
  src/main/webapp/wise5/components/graph/graphAuthoringController.ts
  src/main/webapp/wise5/components/graph/graphController.ts
  src/main/webapp/wise5/components/html/htmlAuthoringController.ts
  src/main/webapp/wise5/components/html/htmlController.ts
  src/main/webapp/wise5/components/label/labelAuthoringController.ts
  src/main/webapp/wise5/components/label/labelController.ts
  src/main/webapp/wise5/components/match/matchAuthoringController.ts
  src/main/webapp/wise5/components/match/matchController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.ts
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.ts
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringController.ts
  src/main/webapp/wise5/components/outsideURL/outsideURLController.ts
  src/main/webapp/wise5/components/summary/summaryAuthoringController.ts
  src/main/webapp/wise5/components/summary/summaryController.ts
  src/main/webapp/wise5/components/table/tableAuthoringController.ts
  src/main/webapp/wise5/components/table/tableController.ts
  src/main/webapp/wise5/services/nodeService.ts
  src/main/webapp/wise5/services/utilService.ts
  src/main/webapp/wise5/vle/studentAsset/studentAssetController.ts
Labels: 1 point

#2667 Replace notAllowedToEditThisProject and notLoggedInProjectNotSaved events
  src/main/webapp/site/src/app/services/projectService.spec.ts
  src/main/webapp/wise5/authoringTool/authoringToolController.ts
  src/main/webapp/wise5/services/projectService.ts
Labels: 1 point

#2646 Replace studentWorkReceived and newStudentWorkReceived events
  src/main/webapp/site/src/app/services/data.service.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.ts
  src/main/webapp/wise5/classroomMonitor/studentGrading/studentGradingController.ts
  src/main/webapp/wise5/components/discussion/discussionController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.ts
  src/main/webapp/wise5/services/studentWebSocketService.ts
  src/main/webapp/wise5/services/teacherDataService.ts
  src/main/webapp/wise5/services/teacherWebSocketService.ts
Labels: 1 point

#2674 Replace audioRecorded and deleteKeyPressed events
  src/main/webapp/wise5/components/animation/animationAuthoringController.ts
  src/main/webapp/wise5/components/animation/animationController.ts
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringController.ts
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringController.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapController.ts
  src/main/webapp/wise5/components/discussion/discussionAuthoringController.ts
  src/main/webapp/wise5/components/discussion/discussionController.ts
  src/main/webapp/wise5/components/draw/drawAuthoringController.ts
  src/main/webapp/wise5/components/draw/drawController.ts
  src/main/webapp/wise5/components/embedded/embeddedAuthoringController.ts
  src/main/webapp/wise5/components/embedded/embeddedController.ts
  src/main/webapp/wise5/components/graph/graphAuthoringController.ts
  src/main/webapp/wise5/components/graph/graphController.ts
  src/main/webapp/wise5/components/html/htmlAuthoringController.ts
  src/main/webapp/wise5/components/html/htmlController.ts
  src/main/webapp/wise5/components/label/labelAuthoringController.ts
  src/main/webapp/wise5/components/label/labelController.ts
  src/main/webapp/wise5/components/match/matchAuthoringController.ts
  src/main/webapp/wise5/components/match/matchController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.ts
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringController.ts
  src/main/webapp/wise5/components/outsideURL/outsideURLController.ts
  src/main/webapp/wise5/components/summary/summaryAuthoringController.ts
  src/main/webapp/wise5/components/summary/summaryController.ts
  src/main/webapp/wise5/components/table/tableAuthoringController.ts
  src/main/webapp/wise5/components/table/tableController.ts
  src/main/webapp/wise5/directives/listenForDeleteKeypress/listenForDeleteKeypress.js
  src/main/webapp/wise5/services/audioRecorderService.ts
  src/main/webapp/wise5/services/studentDataService.ts
Labels: 1 point

#2650 Replace nodeStatusesChanged and nodeSubmitClicked events
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/directives/globalAnnotations/globalAnnotations.js
  src/main/webapp/wise5/directives/globalAnnotationsList/globalAnnotationsList.js
  src/main/webapp/wise5/services/nodeService.ts
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/themes/default/themeComponents/stepTools/stepToolsController.js
  src/main/webapp/wise5/vle/node/nodeController.ts
Labels: 1 point

#2648 Replace annotationReceived and annotationSavedToServer events
  src/main/webapp/site/src/app/services/studentDataService.spec.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/notebook/notebookItemGrading/notebookItemGrading.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/componentNewWorkBadge/componentNewWorkBadge.ts
  src/main/webapp/wise5/classroomMonitor/milestones/milestonesController.ts
  src/main/webapp/wise5/classroomMonitor/studentGrading/studentGradingController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/directives/globalAnnotations/globalAnnotations.js
  src/main/webapp/wise5/directives/globalAnnotationsList/globalAnnotationsList.js
  src/main/webapp/wise5/services/annotationService.ts
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/services/studentWebSocketService.ts
  src/main/webapp/wise5/services/teacherDataService.ts
Labels: 1 point

#2677 Replace snipImage event
  src/main/webapp/wise5/directives/compile/compile.js
  src/main/webapp/wise5/directives/component/component.js
  src/main/webapp/wise5/services/projectService.ts
Labels: 1 point

#2681 Replace newAnnotationReceived and remove doneEditing and nodeCompleted events
  src/main/webapp/wise5/services/studentDataService.ts
  src/main/webapp/wise5/services/teacherDataService.ts
  src/main/webapp/wise5/services/teacherWebSocketService.ts
  src/main/webapp/wise5/vle/node/nodeController.ts
Labels: 1 point
