Repository WISE-Community/WISE, pull requests merged in 2020-01, with the labels that each got.

#2171 Refactoring code in UserService
  src/main/java/org/wise/portal/dao/user/UserDao.java
  src/main/java/org/wise/portal/dao/user/impl/HibernateUserDao.java
  src/main/java/org/wise/portal/presentation/web/controllers/admin/LookupUserController.java
  src/main/java/org/wise/portal/presentation/web/controllers/admin/UserInfoController.java
  src/main/java/org/wise/portal/service/user/UserService.java
  src/main/java/org/wise/portal/service/user/impl/UserServiceImpl.java
  src/main/java/org/wise/portal/spring/impl/WebSecurityConfig.java
  src/test/java/org/wise/portal/dao/user/impl/HibernateUserDaoTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/APIControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/admin/UserInfoControllerTest.java
Labels: 2 points

#2172 Fixed bug where highcharts-ng was adding new categories.
  package-lock.json
  package.json
  src/main/webapp/wise5/authoringTool/authoringTool.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.js
  src/main/webapp/wise5/lib/highcharts/highcharts-ng.js
  src/main/webapp/wise5/vle/vle.js
Labels: 1 point

#2175 Draw tool does not repopulate student drawing if they used the arrow line tool
  src/main/webapp/wise5/lib/drawingTool/drawing-tool.js
Labels: 1 point

#2179 Draw Tool: Typing backspace when using the Text tool deletes the whole text element instead of deleting a character
  src/main/webapp/wise5/lib/drawingTool/drawing-tool.js
Labels: 1 point

#2181 Fix create branch bugs
  src/main/webapp/wise5/authoringTool/node/node.html
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.js
Labels: 1 point

#2173 Add student scores + work (component grading) to milestone reports
  package-lock.json
  package.json
  src/main/webapp/wise5/authoringTool/authoringToolController.js
  src/main/webapp/wise5/authoringTool/project/projectController.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneDetails/milestoneDetails.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGrading.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/workgroupItem/workgroupItem.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nodeProgress.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nodeProgressView/nodeProgressView.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nodeProgressView/nodeProgressView.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/componentRevisionsInfo/componentRevisionsInfo.js
  src/main/webapp/wise5/classroomMonitor/classroomMonitorController.js
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
  src/main/webapp/wise5/classroomMonitor/milestones/milestonesController.js
  src/main/webapp/wise5/classroomMonitor/nodeGrading/nodeGrading.html
  src/main/webapp/wise5/classroomMonitor/studentGrading/studentGrading.html
  src/main/webapp/wise5/themes/default/style/modules/_milestones.scss
  src/main/webapp/wise5/vle/navigation/navigationController.js
  src/main/webapp/wise5/vle/vleController.js
Labels: 1 point, 2 points

#2183 Make sure the Authoring Tool logs out when the user session has timed out
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/WISE5AuthorProjectController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/java/org/wise/portal/presentation/web/response/ErrorResponse.java
  src/main/java/org/wise/portal/presentation/web/response/LaunchRunErrorResponse.java
  src/main/java/org/wise/portal/presentation/web/response/SimpleResponse.java
  src/main/java/org/wise/portal/presentation/web/response/SuccessResponse.java
  src/main/java/org/wise/portal/service/project/ProjectService.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/webapp/site/src/app/modules/shared/edit-password/edit-password.component.spec.ts
  src/main/webapp/site/src/app/modules/shared/edit-password/edit-password.component.ts
  src/main/webapp/wise5/authoringTool/authoringToolController.js
  src/main/webapp/wise5/authoringTool/authoringToolProjectService.js
  src/main/webapp/wise5/authoringTool/components/shared/toolbar/toolbar.js
  src/main/webapp/wise5/authoringTool/i18n/i18n_en.json
  src/main/webapp/wise5/services/projectService.js
  src/main/webapp/wise5/services/sessionService.js
  src/main/webapp/wise5/test-unit/controllers/authoringToolController.spec.js
  src/main/webapp/wise5/test-unit/services/projectService.spec.js
  src/test/java/org/wise/portal/presentation/web/controllers/author/project/WISE5AuthorProjectControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/user/UserAPIControllerTest.java
  src/test/java/org/wise/portal/presentation/web/response/ErrorResponseTest.java
  src/test/java/org/wise/portal/presentation/web/response/SimpleResponseTest.java
  src/test/java/org/wise/portal/presentation/web/response/SuccessResponseTest.java
  src/test/java/org/wise/portal/service/project/impl/ProjectServiceImplTest.java
Labels: 1 point

#2186 Fix discussion component slowdown after 20 responses
  src/main/webapp/wise5/components/discussion/classResponse.html
  src/main/webapp/wise5/components/discussion/classResponse.js
  src/main/webapp/wise5/components/discussion/discussionController.js
  src/main/webapp/wise5/components/discussion/index.html
  src/main/webapp/wise5/directives/componentAnnotations/componentAnnotations.js
  src/main/webapp/wise5/services/configService.js
  src/main/webapp/wise5/test-unit/components/discussion/discussionController.spec.js
  src/main/webapp/wise5/themes/default/style/author.css
  src/main/webapp/wise5/themes/default/style/author.css.map
  src/main/webapp/wise5/themes/default/style/modules/_component--discussion.scss
  src/main/webapp/wise5/themes/default/style/monitor.css
  src/main/webapp/wise5/themes/default/style/monitor.css.map
  src/main/webapp/wise5/themes/default/style/vle.css
  src/main/webapp/wise5/themes/default/style/vle.css.map
  src/main/webapp/wise5/themes/default/templates/notificationMenu.html
  src/main/webapp/wise5/vle/vleController.js
Labels: 1 point

#2193 Fixed issue showing unit info dialog from run listing
  src/main/java/org/wise/portal/domain/project/impl/ProjectMetadataImpl.java
  src/main/webapp/site/src/app/domain/project.ts
Labels: 1 point

#2185 AuthorProjectController refactor and test
  pom.xml
  src/main/java/org/wise/portal/domain/authentication/impl/PersistentUserDetails.java
  src/main/java/org/wise/portal/presentation/web/controllers/VLEController.java
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/AuthorAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/JGitUtils.java
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/ProjectAssetAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/WISE5AuthorProjectController.java
  src/main/java/org/wise/portal/presentation/web/controllers/project/ProjectAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/java/org/wise/portal/service/project/ProjectService.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/java/org/wise/portal/service/run/RunService.java
  src/main/java/org/wise/portal/service/run/impl/RunServiceImpl.java
  src/main/java/org/wise/portal/service/session/SessionService.java
  src/main/java/org/wise/portal/service/session/impl/SessionServiceImpl.java
  src/main/java/org/wise/vle/utils/FileManager.java
  src/main/webapp/wise5/authoringTool/asset/asset.html
  src/main/webapp/wise5/authoringTool/asset/projectAssetController.js
  src/main/webapp/wise5/authoringTool/authoringTool.js
  src/main/webapp/wise5/authoringTool/authoringToolController.js
  src/main/webapp/wise5/authoringTool/authoringToolProjectService.js
  src/main/webapp/wise5/authoringTool/history/history.html
  src/main/webapp/wise5/authoringTool/history/projectHistoryController.js
  src/main/webapp/wise5/authoringTool/i18n/i18n_en.json
  src/main/webapp/wise5/authoringTool/info/projectInfoController.js
  src/main/webapp/wise5/authoringTool/main/authoringToolMainController.js
  src/main/webapp/wise5/authoringTool/main/authoringToolNewProjectController.js
  src/main/webapp/wise5/authoringTool/main/main.html
  src/main/webapp/wise5/authoringTool/main/new.html
  src/main/webapp/wise5/authoringTool/project/project.html
  src/main/webapp/wise5/authoringTool/project/projectController.js
  src/main/webapp/wise5/authoringTool/webpack.dev.js
  src/main/webapp/wise5/classroomMonitor/webpack.dev.js
  src/main/webapp/wise5/services/projectAssetService.js
  src/main/webapp/wise5/services/projectService.js
  src/main/webapp/wise5/test-unit/services/authoringToolProjectService.spec.js
  src/main/webapp/wise5/test-unit/services/projectService.spec.js
  src/test/java/org/wise/portal/presentation/web/controllers/author/project/AuthorAPIControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/author/project/WISE5AuthorProjectControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIControllerTest.java
  src/test/java/org/wise/portal/service/project/impl/ProjectServiceImplTest.java
Labels: 4 points

#2146 Show submit message without feedback information when no feedback exists
  src/main/webapp/wise5/components/openResponse/i18n/i18n_en.json
  src/main/webapp/wise5/components/openResponse/openResponseController.js
  src/main/webapp/wise5/services/cRaterService.js
Labels: 2 points

#2192 create the test for RunHasEndedException
  src/main/java/org/wise/portal/domain/RunHasEndedException.java
  src/test/java/org/wise/portal/service/student/impl/StudentServiceImplTest.java
Labels: 1 point
