Repository WISE-Community/WISE, pull requests merged in 2020-05, with the labels that each got.

#2321 Removed watchers in match grading view to improve performance
  src/main/webapp/wise5/components/match/index.html
Labels: 1 point

#2323 Fixed issue where summernote dropdown was not showing.
  angular.json
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/site/src/polyfills.ts
  src/main/webapp/wise5/authoringTool/authoringTool.html
  src/main/webapp/wise5/authoringTool/authoringTool.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.ts
  src/main/webapp/wise5/themes/default/vle.html
  src/main/webapp/wise5/vle/vle.ts
Labels: 1 point

#2319 Upgraded Angular to 8.2.x.
  gulpfile.js
  package-lock.json
  package.json
  src/main/webapp/site/src/app/app.module.ts
  src/main/webapp/wise5/authoringTool/src/environments/environment.prod.ts
  src/main/webapp/wise5/authoringTool/src/environments/environment.ts
  src/main/webapp/wise5/authoringTool/src/test.ts
  src/main/webapp/wise5/authoringTool/src/tsconfig.app.json
  src/main/webapp/wise5/authoringTool/src/tsconfig.json
  src/main/webapp/wise5/authoringTool/src/tsconfig.spec.json
  src/main/webapp/wise5/classroomMonitor/src/environments/environment.prod.ts
  src/main/webapp/wise5/classroomMonitor/src/environments/environment.ts
  src/main/webapp/wise5/classroomMonitor/src/test.ts
  src/main/webapp/wise5/classroomMonitor/src/tsconfig.app.json
  src/main/webapp/wise5/classroomMonitor/src/tsconfig.json
  src/main/webapp/wise5/classroomMonitor/src/tsconfig.spec.json
  src/main/webapp/wise5/vle/src/environments/environment.prod.ts
  src/main/webapp/wise5/vle/src/environments/environment.ts
  src/main/webapp/wise5/vle/src/tsconfig.app.json
  src/main/webapp/wise5/vle/src/tsconfig.json
  src/main/webapp/wise5/vle/src/tsconfig.spec.json
Labels: 1 point

#2334 Importing a step that contains a lot of content fails
  src/main/webapp/wise5/authoringTool/authoringToolProjectService.ts
Labels: 1 point

#2325 Fixed issue where shared teacher could not switch from AT -> CM
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/AuthorAPIController.java
  src/test/java/org/wise/portal/presentation/web/controllers/APIControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/author/project/AuthorAPIControllerTest.java
Labels: 1 point

#2329 Fixed bug adding link/video with summernote
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/authoringTool/notebook/authorNotebookController.ts
  src/main/webapp/wise5/authoringTool/rubric/rubricAuthoringController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/html/htmlAuthoringController.ts
  src/main/webapp/wise5/themes/default/notebook/notebookReport/notebookReport.js
Labels: 1 point

#2336 Removed watchers in graph grading view to improve performance
  src/main/webapp/wise5/components/graph/index.html
Labels: 1 point

#2308 Removed Legacy Footer Link
  src/main/webapp/site/src/app/modules/footer/footer.component.html
Labels: 1 point

#2337 Export select steps checkbox bug
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExport.html
Labels: 1 point

#2326 Add messages for run end date
  .classpath
  pom.xml
  src/main/java/org/wise/portal/domain/run/Run.java
  src/main/java/org/wise/portal/domain/run/impl/RunImpl.java
  src/main/java/org/wise/portal/domain/run/impl/RunParameters.java
  src/main/java/org/wise/portal/presentation/web/controllers/InformationController.java
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/java/org/wise/portal/service/run/RunService.java
  src/main/java/org/wise/portal/service/run/impl/RunServiceImpl.java
  src/main/webapp/site/src/app/domain/run.ts
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.html
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.scss
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.ts
  src/main/webapp/site/src/app/teacher/run-settings-dialog/run-settings-dialog.component.html
  src/main/webapp/site/src/app/teacher/run-settings-dialog/run-settings-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/run-settings-dialog/run-settings-dialog.component.ts
  src/main/webapp/site/src/app/teacher/teacher.service.spec.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/services/configService.js
  src/main/webapp/wise5/test-unit/services/configService.spec.js
  src/main/webapp/wise5/themes/default/node/node.html
  src/main/webapp/wise5/themes/default/style/author.css
  src/main/webapp/wise5/themes/default/style/author.css.map
  src/main/webapp/wise5/themes/default/style/author.scss
  src/main/webapp/wise5/themes/default/style/modules/_node.scss
  src/main/webapp/wise5/themes/default/style/modules/_notice.scss
  src/main/webapp/wise5/themes/default/style/monitor.css
  src/main/webapp/wise5/themes/default/style/monitor.css.map
  src/main/webapp/wise5/themes/default/style/monitor.scss
  src/main/webapp/wise5/themes/default/style/vle.css
  src/main/webapp/wise5/themes/default/style/vle.css.map
  src/main/webapp/wise5/themes/default/style/vle.scss
  src/main/webapp/wise5/themes/default/themeController.js
  src/main/webapp/wise5/themes/default/vle.html
  src/main/webapp/wise5/vle/i18n/i18n_en.json
  src/main/webapp/wise5/vle/node/nodeController.ts
  src/test/java/org/wise/portal/domain/impl/ProjectcodeTest.java
  src/test/java/org/wise/portal/domain/impl/RunImplTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIControllerTest.java
  src/test/java/org/wise/portal/service/run/impl/RunServiceImplTest.java
Labels: 1 point

#2306 Refactored student data service
  src/main/webapp/wise5/components/discussion/discussionController.ts
  src/main/webapp/wise5/components/outsideURL/outsideURLController.ts
  src/main/webapp/wise5/services/projectService.ts
  src/main/webapp/wise5/services/studentDataService.js
  src/main/webapp/wise5/services/utilService.js
  src/main/webapp/wise5/test-unit/controllers/nodeController.spec.js
  src/main/webapp/wise5/test-unit/services/studentDataService.spec.js
  src/main/webapp/wise5/themes/default/themeController.js
  src/main/webapp/wise5/vle/node/nodeController.ts
Labels: 4 points

#2344 Draw component drag line error
  src/main/webapp/wise5/lib/drawingTool/drawing-tool.js
Labels: 1 point

#2346 Submitting OR response throws js error
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/test-unit/components/openResponse/openResponseController.spec.js
Labels: 1 point

#2350 Refactored StudentStatusController.getStudentStatus
  .classpath
  pom.xml
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/run/TeacherRunAPIController.java
  src/main/java/org/wise/vle/web/StudentStatusController.java
  src/main/webapp/wise5/services/studentStatusService.js
  src/main/webapp/wise5/test-unit/services/studentStatusService.spec.js
  src/test/java/org/wise/portal/presentation/web/controllers/APIControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/teacher/run/AllTests.java
  src/test/java/org/wise/portal/presentation/web/controllers/teacher/run/TeacherRunAPIControllerTest.java
Labels: 1 point

#2342 Fixed issue where css sourcemap was not working
  angular.json
  src/main/java/org/wise/portal/spring/impl/WebConfig.java
Labels: 1 point

#2347 Fixed issue where discussion posts were not displaying in CM.
  src/main/webapp/wise5/components/discussion/authoring.html
  src/main/webapp/wise5/components/discussion/discussionAuthoringComponentModule.ts
Labels: 1 point

#2353 Removed grading from component authoring.html files
  src/main/webapp/wise5/components/animation/authoring.html
  src/main/webapp/wise5/components/audioOscillator/authoring.html
  src/main/webapp/wise5/components/conceptMap/authoring.html
  src/main/webapp/wise5/components/discussion/authoring.html
  src/main/webapp/wise5/components/draw/authoring.html
  src/main/webapp/wise5/components/embedded/authoring.html
  src/main/webapp/wise5/components/graph/authoring.html
  src/main/webapp/wise5/components/label/authoring.html
  src/main/webapp/wise5/components/match/authoring.html
  src/main/webapp/wise5/components/multipleChoice/authoring.html
  src/main/webapp/wise5/components/openResponse/authoring.html
  src/main/webapp/wise5/components/table/authoring.html
Labels: 1 point

#2356 When a student clicks the Go Home button, save a nodeExited event
  src/main/webapp/wise5/services/sessionService.js
Labels: 1 point

#2361 Resize images before uploading as student assets
  src/main/webapp/wise5/themes/default/notebook/editNotebookItem.html
  src/main/webapp/wise5/themes/default/studentAsset/studentAsset.html
Labels: 1 point

#2360 Transfer run ownership throws an error
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherRunPermissionsAPIController.java
  src/main/webapp/site/src/app/teacher/teacher.service.ts
Labels: 1 point

#2363 Save a node exit event when the student refreshes the VLE
  src/main/webapp/wise5/services/sessionService.js
  src/main/webapp/wise5/vle/vleController.ts
Labels: 1 point

#2354 Implement revisit export
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.ts
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExport.html
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.ts
  src/main/webapp/wise5/classroomMonitor/dataExport/exportController.ts
  src/main/webapp/wise5/classroomMonitor/dataExport/exportVisits.html
  src/main/webapp/wise5/classroomMonitor/dataExport/exportVisitsController.ts
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
  src/main/webapp/wise5/services/configService.js
  src/main/webapp/wise5/teacher/teacher.ts
  src/main/webapp/wise5/test-unit/controllers/dataExport/exportController.spec.js
  src/main/webapp/wise5/test-unit/controllers/dataExport/exportVisitsController.spec.js
Labels: 1 point

#2358 Refactored NotificationController.getNotifications().
  src/main/java/org/wise/portal/service/vle/wise5/VLEService.java
  src/main/java/org/wise/portal/service/vle/wise5/impl/VLEServiceImpl.java
  src/main/java/org/wise/vle/domain/notification/Notification.java
  src/main/java/org/wise/vle/web/wise5/NotificationController.java
  src/main/resources/wise_db_init.sql
  src/main/webapp/wise5/services/notificationService.js
  src/main/webapp/wise5/test-unit/services/notificationService.spec.js
  src/main/webapp/wise5/themes/default/templates/notificationMenu.html
  src/main/webapp/wise5/vle/preview.ts
  src/test/java/org/wise/portal/dao/notification/impl/HibernateNotificationDaoTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/APIControllerTest.java
  src/test/java/org/wise/vle/web/wise5/NotificationControllerTest.java
Labels: 1 point

#2348 Notebook grading redesign
  gulpfile.js
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/nodeProgressView/nodeProgressView.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/notebook/notebook.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/notebook/notebookItemGrading/notebookItemGrading.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/notebook/notebookItemGrading/notebookItemGrading.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/notebook/notebookWorkgroupGrading/notebookWorkgroupGrading.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/notebook/notebookWorkgroupGrading/notebookWorkgroupGrading.ts
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
  src/main/webapp/wise5/classroomMonitor/notebook/notebookGrading.html
  src/main/webapp/wise5/classroomMonitor/notebook/notebookGradingController.ts
  src/main/webapp/wise5/classroomMonitor/notebook/notebookItemGrading/notebookItemGrading.html
  src/main/webapp/wise5/classroomMonitor/studentGrading/studentGrading.html
  src/main/webapp/wise5/classroomMonitor/studentGrading/studentGradingController.ts
  src/main/webapp/wise5/classroomMonitor/studentProgress/studentProgress.html
  src/main/webapp/wise5/classroomMonitor/studentProgress/studentProgressController.ts
  src/main/webapp/wise5/directives/wiselink/wiselink.html
  src/main/webapp/wise5/directives/wiselink/wiselink.js
  src/main/webapp/wise5/services/teacherDataService.js
  src/main/webapp/wise5/themes/default/notebook/editNotebookItem.html
  src/main/webapp/wise5/themes/default/notebook/notebook/notebook.js
  src/main/webapp/wise5/themes/default/notebook/notebookNotes/notebookNotes.js
  src/main/webapp/wise5/themes/default/notebook/notebookReport/notebookReport.js
  src/main/webapp/wise5/themes/default/style/angular-material.css
  src/main/webapp/wise5/themes/default/style/angular-material.css.map
  src/main/webapp/wise5/themes/default/style/author.css
  src/main/webapp/wise5/themes/default/style/author.css.map
  src/main/webapp/wise5/themes/default/style/material/_custom.scss
  src/main/webapp/wise5/themes/default/style/modules/_annotations--grading.scss
  src/main/webapp/wise5/themes/default/style/modules/_component--grading.scss
  src/main/webapp/wise5/themes/default/style/modules/_grading.scss
  src/main/webapp/wise5/themes/default/style/modules/_list.scss
  src/main/webapp/wise5/themes/default/style/modules/_node.scss
  src/main/webapp/wise5/themes/default/style/modules/_notebook.scss
  src/main/webapp/wise5/themes/default/style/modules/_table.scss
  src/main/webapp/wise5/themes/default/style/monitor.css
  src/main/webapp/wise5/themes/default/style/monitor.css.map
  src/main/webapp/wise5/themes/default/style/vle.css
  src/main/webapp/wise5/themes/default/style/vle.css.map
Labels: 1 point

#2365 Refactored structured authoring by moving JSON strings from js to files
  src/main/webapp/wise5/authoringTool/structure/configureStructureController.ts
  src/main/webapp/wise5/authoringTool/structure/guidanceChoice/groups.json
  src/main/webapp/wise5/authoringTool/structure/guidanceChoice/guidanceChoiceController.ts
  src/main/webapp/wise5/authoringTool/structure/guidanceChoice/nodes.json
  src/main/webapp/wise5/authoringTool/structure/jigsaw/groups-2.json
  src/main/webapp/wise5/authoringTool/structure/jigsaw/groups-3.json
  src/main/webapp/wise5/authoringTool/structure/jigsaw/groups-4.json
  src/main/webapp/wise5/authoringTool/structure/jigsaw/jigsawController.ts
  src/main/webapp/wise5/authoringTool/structure/jigsaw/nodes-2.json
  src/main/webapp/wise5/authoringTool/structure/jigsaw/nodes-3.json
  src/main/webapp/wise5/authoringTool/structure/jigsaw/nodes-4.json
  src/main/webapp/wise5/authoringTool/structure/kiCycleUsingOER/groups.json
  src/main/webapp/wise5/authoringTool/structure/kiCycleUsingOER/kiCycleUsingOERController.ts
  src/main/webapp/wise5/authoringTool/structure/kiCycleUsingOER/nodes.json
  src/main/webapp/wise5/authoringTool/structure/peerReviewAndRevision/groups.json
  src/main/webapp/wise5/authoringTool/structure/peerReviewAndRevision/nodes.json
  src/main/webapp/wise5/authoringTool/structure/peerReviewAndRevision/peerReviewAndRevisionController.ts
  src/main/webapp/wise5/authoringTool/structure/selfDirectedInvestigation/groups.json
  src/main/webapp/wise5/authoringTool/structure/selfDirectedInvestigation/nodes.json
  src/main/webapp/wise5/authoringTool/structure/selfDirectedInvestigation/selfDirectedInvestigationController.ts
Labels: 1 point

#2370 WISE4 unit preview and links to WISE4 teacher tools broken
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/AuthorAPIController.java
  src/main/java/org/wise/portal/service/project/impl/ProjectServiceImpl.java
  src/main/webapp/portal/admin/project/manageallprojects.jsp
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.ts
Labels: 1 point

#2375 Prevent extra nodeExited event from saving when a student enters a step
  src/main/webapp/wise5/vle/navigation/navigationController.ts
Labels: 1 point

#2369 Added Google Analytics pageview tracking on route changes
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/webapp/site/src/app/app.component.spec.ts
  src/main/webapp/site/src/app/app.component.ts
  src/main/webapp/site/src/app/domain/config.ts
  src/main/webapp/site/src/app/services/config.service.ts
  src/test/java/org/wise/portal/presentation/web/controllers/user/UserAPIControllerTest.java
Labels: 1 point

#2379 Handle extra node exited event in export step visits
  src/main/webapp/wise5/classroomMonitor/dataExport/exportVisits.html
  src/main/webapp/wise5/classroomMonitor/dataExport/exportVisitsController.ts
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
  src/main/webapp/wise5/test-unit/controllers/dataExport/exportVisitsController.spec.js
Labels: 1 point

#2382 Refactored nodeAuthoringController
  src/main/webapp/wise5/authoringTool/node/node.html
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
Labels: 1 point

#2377 Converted UtilService to Angular
  .travis.yml
  package-lock.json
  package.json
  src/main/resources/wise_db_init.sql
  src/main/webapp/site/src/app/preview/preview-angular-js-module.ts
  src/main/webapp/site/src/app/services/utilService.spec.ts
  src/main/webapp/site/src/app/student/student-angular-js-module.ts
  src/main/webapp/site/src/app/teacher/teacher-angular-js-module.ts
  src/main/webapp/site/src/tsconfig.app.json
  src/main/webapp/site/src/tsconfig.spec.json
  src/main/webapp/wise5/authoringTool/asset/projectAssetController.ts
  src/main/webapp/wise5/authoringTool/authoringTool.ts
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/authoringTool/notebook/authorNotebookController.ts
  src/main/webapp/wise5/authoringTool/rubric/rubricAuthoringController.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/embedded/embeddedController.ts
  src/main/webapp/wise5/components/embedded/embeddedService.ts
  src/main/webapp/wise5/components/html/htmlAuthoringController.ts
  src/main/webapp/wise5/services/utilService.ts
  src/main/webapp/wise5/vle/preview.ts
  src/main/webapp/wise5/vle/vle.ts
Labels: 2 points

#2378 Moved sample library groups json into a JSON file
  src/main/webapp/site/src/app/modules/library/sampleLibraryGroups.json
Labels: 1 point
