Repository WISE-Community/WISE, pull requests merged in 2020-11, with the labels that each got.

#2778 Removed OnlyShowWork mode and removed $rootScope from NodeController
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapController.ts
  src/main/webapp/wise5/components/draw/drawController.ts
  src/main/webapp/wise5/components/graph/graphController.ts
  src/main/webapp/wise5/components/label/labelController.ts
  src/main/webapp/wise5/components/match/matchController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.ts
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/components/table/tableController.ts
  src/main/webapp/wise5/vle/node/nodeController.ts
Labels: 1 point

#2781 Upgraded HelpIcon component to Angular
  src/main/webapp/site/src/app/hybrid-module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/site/src/tsconfig.app.json
  src/main/webapp/wise5/services/nodeService.ts
  src/main/webapp/wise5/themes/default/node/node.html
  src/main/webapp/wise5/themes/default/themeComponents.ts
  src/main/webapp/wise5/themes/default/themeComponents/helpIcon/help-icon.component.html
  src/main/webapp/wise5/themes/default/themeComponents/helpIcon/help-icon.component.scss
  src/main/webapp/wise5/themes/default/themeComponents/helpIcon/help-icon.component.ts
  src/main/webapp/wise5/themes/default/themeComponents/helpIcon/helpIcon.js
  src/main/webapp/wise5/vle/node/nodeController.ts
Labels: 1 point

#2784 Upgraded NodeAdvancedJSONAuthoring component to Angular
  src/main/webapp/site/src/app/hybrid-module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/authoringTool/node/advanced/json/node-advanced-json-authoring.component.html
  src/main/webapp/wise5/authoringTool/node/advanced/json/node-advanced-json-authoring.component.ts
  src/main/webapp/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#2792 Teacher (and student) homepage and unit library UI/UX changes
  src/main/webapp/site/src/app/help/getting-started/getting-started.component.html
  src/main/webapp/site/src/app/help/teacher-faq/teacher-faq.component.html
  src/main/webapp/site/src/app/modules/library/library-project-details/library-project-details.component.html
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.html
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.scss
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.ts
  src/main/webapp/site/src/app/modules/library/libraryPaginatorIntl.ts
  src/main/webapp/site/src/app/student/student-run-list/student-run-list.component.html
  src/main/webapp/site/src/app/student/student-run-list/student-run-list.component.spec.ts
  src/main/webapp/site/src/app/teacher/edit-run-warning-dialog/edit-run-warning-dialog.component.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.html
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.scss
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list/teacher-run-list.component.html
  src/main/webapp/site/src/messages-code.xlf
  src/main/webapp/site/src/messages.xlf
Labels: 1 point

#2789 Separated hybrid angular bundle into teacher and student
  src/main/webapp/site/src/app/common-hybrid-angular.module.ts
  src/main/webapp/site/src/app/preview/preview.module.ts
  src/main/webapp/site/src/app/student-hybrid-angular.module.ts
  src/main/webapp/site/src/app/student/student-routing.module.ts
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/app/teacher/teacher-routing.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/common-angular-js-module.ts
  src/main/webapp/wise5/teacher/teacher-angular-js-module.ts
  src/main/webapp/wise5/vle/student-angular-js-module.ts
Labels: 2 points

#2793 Combined CM and AT's sideMenu components into one
  src/main/webapp/wise5/authoringTool/authoringTool.html
  src/main/webapp/wise5/authoringTool/components/authoringToolComponents.ts
  src/main/webapp/wise5/authoringTool/components/shared/shared.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/shared.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/sideMenu/sideMenu.ts
  src/main/webapp/wise5/common-angular-js-module.ts
  src/main/webapp/wise5/common/sideMenuComponent.ts
Labels: 1 point

#2795 Upgraded NodeStatusIcon to Angular
  src/main/webapp/site/src/app/common-hybrid-angular.module.ts
  src/main/webapp/wise5/authoringTool/node/advanced/branch/node-advanced-branch-authoring.component.html
  src/main/webapp/wise5/authoringTool/node/advanced/constraint/node-advanced-constraint-authoring.component.html
  src/main/webapp/wise5/authoringTool/node/advanced/path/node-advanced-path-authoring.component.html
  src/main/webapp/wise5/authoringTool/wiseLink/wiseLinkAuthoring.html
  src/main/webapp/wise5/themes/default/themeComponents.ts
  src/main/webapp/wise5/themes/default/themeComponents/navItem/navItem.html
  src/main/webapp/wise5/themes/default/themeComponents/nodeStatusIcon/node-status-icon.component.html
  src/main/webapp/wise5/themes/default/themeComponents/nodeStatusIcon/node-status-icon.component.scss
  src/main/webapp/wise5/themes/default/themeComponents/nodeStatusIcon/node-status-icon.component.ts
  src/main/webapp/wise5/themes/default/themeComponents/nodeStatusIcon/nodeStatusIcon.html
  src/main/webapp/wise5/themes/default/themeComponents/nodeStatusIcon/nodeStatusIconController.js
  src/main/webapp/wise5/themes/default/themeComponents/stepTools/stepTools.html
Labels: 1 point

#2800 Disabled run and unit sharing from admin pages
  src/main/webapp/portal/admin/index.jsp
  src/main/webapp/portal/admin/project/manageallprojects.jsp
  src/main/webapp/portal/admin/run/manageprojectruns.jsp
  src/main/webapp/portal/admin/run/stats.jsp
Labels: 1 point

#2804 Add ETS logo to site footer
  src/main/webapp/site/src/app/app.component.ts
  src/main/webapp/site/src/app/modules/footer/footer.component.html
  src/main/webapp/site/src/assets/img/footer/ETS-Logo-navy-gold.svg
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/themes/default/themeComponents/nodeStatusIcon/node-status-icon.component.html
Labels: 1 point

#2799 Upgraded WorkgroupInfo to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGrading.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/workgroupInfo/workgroup-info.component.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/workgroupInfo/workgroup-info.component.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/workgroupInfo/workgroupInfo.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/workgroupItem/workgroupItem.ts
  src/main/webapp/wise5/themes/default/themeComponents/nodeStatusIcon/node-status-icon.component.html
Labels: 1 point

#2774 Upgraded NodeAdvancedGeneralAuthoring component to Angular
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/authoringTool/node/advanced/general/node-advanced-general-authoring.component.html
  src/main/webapp/wise5/authoringTool/node/advanced/general/node-advanced-general-authoring.component.ts
  src/main/webapp/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#2808 Allow teachers to copy and share run signup link with students
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/webapp/site/src/app/domain/config.ts
  src/main/webapp/site/src/app/services/config.service.ts
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.html
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.ts
  src/main/webapp/site/src/app/teacher/share-run-code-dialog/share-run-code-dialog.component.html
  src/main/webapp/site/src/app/teacher/share-run-code-dialog/share-run-code-dialog.component.scss
  src/main/webapp/site/src/app/teacher/share-run-code-dialog/share-run-code-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/share-run-code-dialog/share-run-code-dialog.component.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.html
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-run-list-item/teacher-run-list-item.component.ts
  src/main/webapp/site/src/app/teacher/teacher.module.ts
  src/main/webapp/site/src/assets/img/icons/google-classroom.svg
  src/main/webapp/site/src/messages-code.xlf
  src/main/webapp/site/src/messages.xlf
  src/test/java/org/wise/portal/presentation/web/controllers/user/UserAPIControllerTest.java
Labels: 1 point

#2802 Clarify difference between sharing runs and units
  src/main/webapp/site/src/app/features/features.component.scss
  src/main/webapp/site/src/app/modules/library/copy-project-dialog/copy-project-dialog.component.ts
  src/main/webapp/site/src/app/modules/library/library-project-menu/library-project-menu.component.ts
  src/main/webapp/site/src/app/modules/library/library/library.component.scss
  src/main/webapp/site/src/app/modules/library/personal-library/personal-library.component.ts
  src/main/webapp/site/src/app/modules/library/share-project-dialog/share-project-dialog.component.html
  src/main/webapp/site/src/app/student/team-sign-in-dialog/team-sign-in-dialog.component.html
  src/main/webapp/site/src/app/student/team-sign-in-dialog/team-sign-in-dialog.component.scss
  src/main/webapp/site/src/app/teacher/create-run-dialog/create-run-dialog.component.scss
  src/main/webapp/site/src/app/teacher/list-classroom-courses-dialog/list-classroom-courses-dialog.component.scss
  src/main/webapp/site/src/app/teacher/run-menu/run-menu.component.html
  src/main/webapp/site/src/app/teacher/run-settings-dialog/run-settings-dialog.component.scss
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.html
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.scss
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.spec.ts
  src/main/webapp/site/src/app/teacher/share-run-dialog/share-run-dialog.component.ts
  src/main/webapp/site/src/app/teacher/teacher.service.spec.ts
  src/main/webapp/site/src/app/teacher/teacher.service.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/site/src/style/abstracts/_mixins.scss
  src/main/webapp/site/src/style/components/_dialog.scss
  src/main/webapp/site/src/style/components/_menu.scss
Labels: 1 point

#2812 Upgraded ComponentAnnotations to Angular
  src/main/webapp/site/src/app/common-hybrid-angular.module.ts
  src/main/webapp/site/src/app/student-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/components/animation/index.html
  src/main/webapp/wise5/components/audioOscillator/index.html
  src/main/webapp/wise5/components/conceptMap/index.html
  src/main/webapp/wise5/components/discussion/index.html
  src/main/webapp/wise5/components/draw/index.html
  src/main/webapp/wise5/components/embedded/index.html
  src/main/webapp/wise5/components/graph/index.html
  src/main/webapp/wise5/components/label/index.html
  src/main/webapp/wise5/components/match/index.html
  src/main/webapp/wise5/components/multipleChoice/index.html
  src/main/webapp/wise5/components/openResponse/index.html
  src/main/webapp/wise5/components/table/index.html
  src/main/webapp/wise5/directives/componentAnnotations/component-annotations.component.html
  src/main/webapp/wise5/directives/componentAnnotations/component-annotations.component.scss
  src/main/webapp/wise5/directives/componentAnnotations/component-annotations.component.ts
  src/main/webapp/wise5/directives/componentAnnotations/componentAnnotations.html
  src/main/webapp/wise5/directives/componentAnnotations/componentAnnotations.js
  src/main/webapp/wise5/directives/components.ts
  src/main/webapp/wise5/vle/student-angular-js-module.ts
Labels: 1 point

#2814 Changed StudentAssetController to return StudentAsset object
  src/main/java/org/wise/portal/service/vle/wise5/VLEService.java
  src/main/java/org/wise/portal/service/vle/wise5/impl/VLEServiceImpl.java
  src/main/java/org/wise/portal/service/work/StudentAssetJsonModule.java
  src/main/java/org/wise/vle/domain/work/StudentAsset.java
  src/main/java/org/wise/vle/domain/work/StudentAssetSerializer.java
  src/main/java/org/wise/vle/web/wise5/StudentAssetController.java
  src/main/webapp/site/src/app/services/studentAssetService.spec.ts
  src/main/webapp/wise5/services/studentAssetService.ts
  src/test/java/org/wise/portal/domain/studentAsset/StudentAssetTest.java
Labels: 1 point

#2807 Show posts from Discourse in teacher homepage
  src/main/java/org/wise/portal/presentation/web/controllers/DiscourseSSOController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/java/org/wise/portal/spring/impl/WebSecurityConfig.java
  src/main/webapp/site/src/app/domain/config.ts
  src/main/webapp/site/src/app/services/config.service.ts
  src/main/webapp/site/src/app/teacher/discourse-recent-activity/discourse-recent-activity.component.html
  src/main/webapp/site/src/app/teacher/discourse-recent-activity/discourse-recent-activity.component.scss
  src/main/webapp/site/src/app/teacher/discourse-recent-activity/discourse-recent-activity.component.spec.ts
  src/main/webapp/site/src/app/teacher/discourse-recent-activity/discourse-recent-activity.component.ts
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.html
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.scss
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.spec.ts
  src/main/webapp/site/src/app/teacher/teacher-home/teacher-home.component.ts
  src/main/webapp/site/src/app/teacher/teacher.module.ts
  src/main/webapp/site/src/messages.xlf
  src/test/java/org/wise/portal/presentation/web/controllers/DiscourseSSOControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/user/UserAPIControllerTest.java
Labels: 8 points

#2816 Added Serializer for Achievement
  src/main/java/org/wise/portal/service/work/AchievementJsonModule.java
  src/main/java/org/wise/vle/domain/achievement/Achievement.java
  src/main/java/org/wise/vle/domain/achievement/AchievementSerializer.java
  src/main/java/org/wise/vle/web/wise5/AchievementController.java
  src/main/java/org/wise/vle/web/wise5/StudentDataController.java
  src/test/java/org/wise/portal/domain/work/AchievementTest.java
Labels: 1 point

#2820 Fixed bug causing blank screen after teacher login
  src/main/webapp/site/src/app/app.component.html
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/site/src/style/layout/_standalone.scss
Labels: 1 point
