Repository WISE-Community/WISE, pull requests merged in 2020-06, with the labels that each got.

#2386 Ensure text remains visible during webfont load
  src/main/webapp/site/src/index.html
Labels: 1 point

#2388 Build prod error
  src/main/webapp/site/src/app/preview/preview-angular-js-module.ts
  src/main/webapp/site/src/app/services/utilService.spec.ts
  src/main/webapp/site/src/app/student/student-angular-js-module.ts
  src/main/webapp/site/src/app/teacher/teacher-angular-js-module.ts
  src/main/webapp/wise5/authoringTool/advanced/advancedAuthoringController.ts
  src/main/webapp/wise5/authoringTool/asset/projectAssetController.ts
  src/main/webapp/wise5/authoringTool/authoringTool.ts
  src/main/webapp/wise5/authoringTool/main/authoringToolMainController.ts
  src/main/webapp/wise5/authoringTool/milestones/milestonesAuthoringController.ts
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/authoringTool/notebook/authorNotebookController.ts
  src/main/webapp/wise5/authoringTool/project/projectController.ts
  src/main/webapp/wise5/authoringTool/rubric/rubricAuthoringController.ts
  src/main/webapp/wise5/authoringTool/structure/configureStructureController.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneEdit/milestoneEdit.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/componentSelect/componentSelect.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/notebook/notebookItemGrading/notebookItemGrading.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/nodeInfo/nodeInfo.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupNodeGrading/workgroupNodeGrading.ts
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.ts
  src/main/webapp/wise5/classroomMonitor/dataExport/exportVisitsController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/services/milestoneService.ts
  src/main/webapp/wise5/services/projectService.ts
  src/main/webapp/wise5/services/utilService.ts
  src/main/webapp/wise5/vle/node/nodeController.ts
  src/main/webapp/wise5/vle/preview.ts
  src/main/webapp/wise5/vle/vle.ts
Labels: 1 point

#2390 Upgraded ConfigService to Angular
  package-lock.json
  src/main/webapp/site/src/app/preview/preview-angular-js-module.ts
  src/main/webapp/site/src/app/services/configService.spec.ts
  src/main/webapp/site/src/app/services/sampleData/sample_config_1.json
  src/main/webapp/site/src/app/services/sampleData/sample_config_2.json
  src/main/webapp/site/src/app/services/sampleData/sample_i18n_common_en.json
  src/main/webapp/site/src/app/services/sampleData/sample_i18n_vle_en.json
  src/main/webapp/site/src/app/services/utilService.spec.ts
  src/main/webapp/site/src/app/student/student-angular-js-module.ts
  src/main/webapp/site/src/app/teacher/teacher-angular-js-module.ts
  src/main/webapp/site/tsconfig.json
  src/main/webapp/wise5/authoringTool/advanced/advancedAuthoringController.ts
  src/main/webapp/wise5/authoringTool/asset/projectAssetController.ts
  src/main/webapp/wise5/authoringTool/authoringTool.ts
  src/main/webapp/wise5/authoringTool/authoringToolController.ts
  src/main/webapp/wise5/authoringTool/components/shared/stepTools/stepTools.ts
  src/main/webapp/wise5/authoringTool/components/shared/topBar/topBar.ts
  src/main/webapp/wise5/authoringTool/importStep/chooseStepController.ts
  src/main/webapp/wise5/authoringTool/info/projectInfoController.ts
  src/main/webapp/wise5/authoringTool/main/authoringToolMainController.ts
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/authoringTool/notebook/authorNotebookController.ts
  src/main/webapp/wise5/authoringTool/project/projectController.ts
  src/main/webapp/wise5/authoringTool/rubric/rubricAuthoringController.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/milestones/milestoneDetails/milestoneDetails.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/workgroupInfo/workgroupInfo.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/notebook/notebookItemGrading/notebookItemGrading.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/componentGrading/componentGrading.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/componentRevisionsInfo/componentRevisionsInfo.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/topBar/topBar.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentRevisions/workgroupComponentRevisions.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupNodeGrading/workgroupNodeGrading.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupSelect/workgroupSelect.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/studentGrading/studentGradingTools/studentGradingTools.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorController.ts
  src/main/webapp/wise5/classroomMonitor/dataExport/dataExportController.ts
  src/main/webapp/wise5/classroomMonitor/dataExport/exportVisitsController.ts
  src/main/webapp/wise5/classroomMonitor/notebook/notebookGradingController.ts
  src/main/webapp/wise5/classroomMonitor/studentGrading/studentGradingController.ts
  src/main/webapp/wise5/classroomMonitor/studentProgress/studentProgressController.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapService.ts
  src/main/webapp/wise5/components/discussion/classResponseController.ts
  src/main/webapp/wise5/components/discussion/discussionService.ts
  src/main/webapp/wise5/services/configService.ts
  src/main/webapp/wise5/services/milestoneService.ts
  src/main/webapp/wise5/services/projectService.ts
  src/main/webapp/wise5/test-unit/services/configService.spec.js
  src/main/webapp/wise5/vle/node/nodeController.ts
  src/main/webapp/wise5/vle/preview.ts
  src/main/webapp/wise5/vle/studentAsset/studentAssetController.ts
  src/main/webapp/wise5/vle/vle.ts
  src/main/webapp/wise5/vle/vleController.ts
Labels: 1 point

#2395 Resize and compress images uploaded in the AT.
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/ProjectAssetAPIController.java
  src/main/webapp/wise5/authoringTool/asset/asset.html
Labels: 1 point

#2401 Upgraded MilestoneReportData component to Angular
  src/main/webapp/site/src/app/teacher/milestone/milestone-report-data/milestone-report-data.component.spec.ts
  src/main/webapp/site/src/app/teacher/milestone/milestone-report-data/milestone-report-data.component.ts
  src/main/webapp/site/src/app/teacher/teacher-angular-js-module.ts
  src/main/webapp/wise5/directives/components.ts
  src/main/webapp/wise5/directives/milestoneReportData/milestoneReportData.html
Labels: 1 point

#2392 Implement Summary for Table component
  src/main/webapp/wise5/components/summary/authoring.html
  src/main/webapp/wise5/components/summary/i18n/i18n_en.json
  src/main/webapp/wise5/components/summary/index.html
  src/main/webapp/wise5/components/summary/summaryAuthoringController.ts
  src/main/webapp/wise5/components/summary/summaryController.ts
  src/main/webapp/wise5/components/summary/summaryService.ts
  src/main/webapp/wise5/directives/summaryDisplay/summaryDisplay.html
  src/main/webapp/wise5/directives/summaryDisplay/summaryDisplay.js
Labels: 2 points

#2405 Implemented authoring automated assessment structure
  src/main/java/org/wise/portal/domain/portal/Portal.java
  src/main/java/org/wise/portal/domain/portal/impl/PortalImpl.java
  src/main/java/org/wise/portal/presentation/web/controllers/author/project/AuthorAPIController.java
  src/main/resources/wise_db_init.sql
  src/main/webapp/wise5/authoringTool/authoringToolProjectService.ts
  src/main/webapp/wise5/authoringTool/i18n/i18n_en.json
  src/main/webapp/wise5/authoringTool/importStep/chooseLocation.html
  src/main/webapp/wise5/authoringTool/structure/automatedAssessment/automatedAssessmentChooseItemController.ts
  src/main/webapp/wise5/authoringTool/structure/automatedAssessment/automatedAssessmentConfigureController.ts
  src/main/webapp/wise5/authoringTool/structure/automatedAssessment/choose-item.html
  src/main/webapp/wise5/authoringTool/structure/automatedAssessment/configure-item.html
  src/main/webapp/wise5/authoringTool/structure/chooseStructureController.ts
  src/main/webapp/wise5/authoringTool/structure/structureAuthoringModule.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/nodeInfo/nodeInfo.ts
Labels: 4 points

#2407 Update lesson structures in the Authoring Tool
  src/main/webapp/wise5/authoringTool/structure/jigsaw/groups-2.json
  src/main/webapp/wise5/authoringTool/structure/jigsaw/groups-3.json
  src/main/webapp/wise5/authoringTool/structure/jigsaw/groups-4.json
  src/main/webapp/wise5/authoringTool/structure/jigsaw/nodes-2.json
  src/main/webapp/wise5/authoringTool/structure/jigsaw/nodes-3.json
  src/main/webapp/wise5/authoringTool/structure/jigsaw/nodes-4.json
  src/main/webapp/wise5/authoringTool/structure/kiCycleUsingOER/groups.json
  src/main/webapp/wise5/authoringTool/structure/kiCycleUsingOER/nodes.json
  src/main/webapp/wise5/authoringTool/structure/peerReviewAndRevision/groups.json
  src/main/webapp/wise5/authoringTool/structure/peerReviewAndRevision/nodes.json
  src/main/webapp/wise5/authoringTool/structure/selfDirectedInvestigation/groups.json
  src/main/webapp/wise5/authoringTool/structure/selfDirectedInvestigation/nodes.json
Labels: 1 point

#2409 Add scroll while dragging to match components
  package-lock.json
  package.json
  src/main/webapp/site/src/tsconfig.app.json
  src/main/webapp/wise5/components/match/matchController.ts
Labels: 1 point

#2410 Moved getOnlyLatest filter when getting student work from db to code
  src/main/java/org/wise/portal/dao/work/StudentWorkDao.java
  src/main/java/org/wise/portal/dao/work/impl/HibernateStudentWorkDao.java
  src/main/java/org/wise/portal/domain/workgroup/Workgroup.java
  src/main/java/org/wise/portal/service/vle/wise5/impl/VLEServiceImpl.java
  src/test/java/org/wise/portal/dao/work/impl/HibernateStudentWorkDaoTest.java
  src/test/java/org/wise/portal/service/vle/wise5/impl/VLEServiceImplTest.java
Labels: 1 point

#2413 One Workgroup Per Row export contains empty columns
  src/main/webapp/wise5/services/projectService.ts
Labels: 1 point

#2417 Implemented audio recording for open response component
  package-lock.json
  package.json
  src/main/java/org/wise/vle/web/wise5/StudentAssetController.java
  src/main/resources/application_sample.properties
  src/main/webapp/site/src/tsconfig.app.json
  src/main/webapp/site/src/tsconfig.spec.json
  src/main/webapp/wise5/authoringTool/authoringTool.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/openResponse/authoring.html
  src/main/webapp/wise5/components/openResponse/i18n/i18n_en.json
  src/main/webapp/wise5/components/openResponse/index.html
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringController.ts
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/components/openResponse/openResponseService.ts
  src/main/webapp/wise5/services/audioRecorderService.ts
  src/main/webapp/wise5/services/studentAssetService.js
  src/main/webapp/wise5/vle/preview.ts
  src/main/webapp/wise5/vle/vle.ts
Labels: 2 points

#2415 CRaterService: Upgrade from AngularJS -> Angular
  package.json
  src/main/webapp/site/src/app/preview/preview-angular-js-module.ts
  src/main/webapp/site/src/app/services/cRaterService.spec.ts
  src/main/webapp/site/src/app/student/student-angular-js-module.ts
  src/main/webapp/site/src/app/teacher/teacher-angular-js-module.ts
  src/main/webapp/wise5/authoringTool/authoringTool.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.ts
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/services/cRaterService.ts
  src/main/webapp/wise5/vle/preview.ts
  src/main/webapp/wise5/vle/vle.ts
Labels: 1 point

#2422 Delete activity with a branch bug
  src/main/webapp/site/src/app/services/projectService.spec.ts
  src/main/webapp/site/src/app/services/sampleData/curriculum/Demo.project.json
  src/main/webapp/wise5/services/projectService.ts
Labels: 1 point

#2421 Upgraded StudentAssetService to Angular
  src/main/java/org/wise/vle/web/wise5/StudentAssetController.java
  src/main/webapp/site/src/app/preview/preview-angular-js-module.ts
  src/main/webapp/site/src/app/services/studentAssetService.spec.ts
  src/main/webapp/site/src/app/student/student-angular-js-module.ts
  src/main/webapp/site/src/app/teacher/teacher-angular-js-module.ts
  src/main/webapp/wise5/authoringTool/authoringTool.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.ts
  src/main/webapp/wise5/components/componentController.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapService.ts
  src/main/webapp/wise5/components/draw/drawService.ts
  src/main/webapp/wise5/components/embedded/embeddedService.ts
  src/main/webapp/wise5/components/label/labelService.ts
  src/main/webapp/wise5/components/table/tableService.ts
  src/main/webapp/wise5/services/studentAssetService.js
  src/main/webapp/wise5/services/studentAssetService.ts
  src/main/webapp/wise5/vle/preview.ts
  src/main/webapp/wise5/vle/studentAsset/studentAssetController.ts
  src/main/webapp/wise5/vle/vle.ts
Labels: 1 point

#2423 Removed planning service and planning functionality
  src/main/webapp/wise5/authoringTool/authoringTool.ts
  src/main/webapp/wise5/authoringTool/i18n/i18n_ar.json
  src/main/webapp/wise5/authoringTool/i18n/i18n_el.json
  src/main/webapp/wise5/authoringTool/i18n/i18n_en.json
  src/main/webapp/wise5/authoringTool/i18n/i18n_zh_CN.json
  src/main/webapp/wise5/authoringTool/i18n/i18n_zh_TW.json
  src/main/webapp/wise5/authoringTool/node/nodeAuthoringController.ts
  src/main/webapp/wise5/authoringTool/structure/automatedAssessment/choose-item.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.ts
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_ar.json
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_el.json
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_en.json
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_zh_CN.json
  src/main/webapp/wise5/classroomMonitor/i18n/i18n_zh_TW.json
  src/main/webapp/wise5/services/planningService.js
  src/main/webapp/wise5/services/projectService.ts
  src/main/webapp/wise5/services/studentDataService.js
  src/main/webapp/wise5/themes/default/navigation/navigation.html
  src/main/webapp/wise5/themes/default/style/modules/_nav.scss
  src/main/webapp/wise5/themes/default/themeComponents/navItem/choosePlanningItem.html
  src/main/webapp/wise5/themes/default/themeComponents/navItem/navItem.html
  src/main/webapp/wise5/themes/default/themeComponents/navItem/navItemController.js
  src/main/webapp/wise5/themes/default/themeController.js
  src/main/webapp/wise5/vle/i18n/i18n_ar.json
  src/main/webapp/wise5/vle/i18n/i18n_el.json
  src/main/webapp/wise5/vle/i18n/i18n_en.json
  src/main/webapp/wise5/vle/i18n/i18n_zh_CN.json
  src/main/webapp/wise5/vle/i18n/i18n_zh_TW.json
  src/main/webapp/wise5/vle/preview.ts
  src/main/webapp/wise5/vle/vle.ts
Labels: 1 point

#2425 Upgraded SessionService to Angular
  src/main/webapp/site/src/app/preview/preview-angular-js-module.ts
  src/main/webapp/site/src/app/services/sessionService.spec.ts
  src/main/webapp/site/src/app/student/student-angular-js-module.ts
  src/main/webapp/site/src/app/teacher/teacher-angular-js-module.ts
  src/main/webapp/wise5/authoringTool/authoringTool.ts
  src/main/webapp/wise5/authoringTool/authoringToolController.ts
  src/main/webapp/wise5/authoringTool/components/shared/topBar/topBar.ts
  src/main/webapp/wise5/authoringTool/main/authoringToolMainController.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitor.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/topBar/topBar.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorController.ts
  src/main/webapp/wise5/services/sessionService.js
  src/main/webapp/wise5/services/sessionService.ts
  src/main/webapp/wise5/services/studentDataService.js
  src/main/webapp/wise5/test-unit/services/sessionService.spec.js
  src/main/webapp/wise5/themes/default/templates/accountMenu.html
  src/main/webapp/wise5/themes/default/themeController.js
  src/main/webapp/wise5/vle/preview.ts
  src/main/webapp/wise5/vle/vle.ts
  src/main/webapp/wise5/vle/vleController.ts
Labels: 1 point
