Repository WISE-Community/WISE, pull requests merged in 2021-01, with the labels that each got.

#2857 Upgrade OpenResponseAuthoring to Angular
  src/main/webapp/site/src/app/authoring-tool/edit-advanced-component/editAdvancedComponentAngularJSController.ts
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/authoringTool/components/component-authoring.component.ts
  src/main/webapp/wise5/authoringTool/components/editComponentController.ts
  src/main/webapp/wise5/authoringTool/components/preview-component/previewComponent.ts
  src/main/webapp/wise5/authoringTool/node/node.html
  src/main/webapp/wise5/components/animation/authoring.html
  src/main/webapp/wise5/components/audioOscillator/authoring.html
  src/main/webapp/wise5/components/conceptMap/authoring.html
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoring.ts
  src/main/webapp/wise5/components/conceptMap/edit-concept-map-advanced/edit-concept-map-advanced.component.ts
  src/main/webapp/wise5/components/discussion/authoring.html
  src/main/webapp/wise5/components/discussion/discussionAuthoring.ts
  src/main/webapp/wise5/components/discussion/edit-discussion-advanced/edit-discussion-advanced.component.ts
  src/main/webapp/wise5/components/draw/authoring.html
  src/main/webapp/wise5/components/draw/drawAuthoring.ts
  src/main/webapp/wise5/components/draw/edit-draw-advanced/edit-draw-advanced.component.ts
  src/main/webapp/wise5/components/embedded/authoring.html
  src/main/webapp/wise5/components/graph/authoring.html
  src/main/webapp/wise5/components/graph/edit-graph-advanced/edit-graph-advanced.component.html
  src/main/webapp/wise5/components/graph/edit-graph-advanced/edit-graph-advanced.component.ts
  src/main/webapp/wise5/components/graph/graphAuthoring.ts
  src/main/webapp/wise5/components/label/authoring.html
  src/main/webapp/wise5/components/label/edit-label-advanced/edit-label-advanced.component.ts
  src/main/webapp/wise5/components/label/labelAuthoring.ts
  src/main/webapp/wise5/components/match/authoring.html
  src/main/webapp/wise5/components/multipleChoice/edit-multiple-choice-advanced/edit-multiple-choice-advanced.component.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoring.ts
  src/main/webapp/wise5/components/openResponse/authoring.html
  src/main/webapp/wise5/components/openResponse/open-response-authoring/open-response-authoring.component.html
  src/main/webapp/wise5/components/openResponse/open-response-authoring/open-response-authoring.component.ts
  src/main/webapp/wise5/components/openResponse/openResponseAuthoring.ts
  src/main/webapp/wise5/components/openResponse/openResponseAuthoringComponentModule.ts
  src/main/webapp/wise5/components/outsideURL/authoring.html
  src/main/webapp/wise5/components/summary/authoring.html
  src/main/webapp/wise5/components/table/authoring.html
Labels: 1 point

#2858 Constraint without Removal Criteria Name breaks preview project
  src/main/webapp/wise5/services/studentDataService.ts
Labels: 1 point

#2863 Change authoringViewComponentChanged() to componentChanged()
  src/main/webapp/site/src/app/authoring-tool/edit-advanced-component/editAdvancedComponentAngularJSController.ts
  src/main/webapp/wise5/authoringTool/components/component-authoring.component.ts
  src/main/webapp/wise5/authoringTool/components/editComponentController.ts
  src/main/webapp/wise5/authoringTool/notebook/authorNotebookController.ts
  src/main/webapp/wise5/authoringTool/notebook/notebookAuthoring.html
  src/main/webapp/wise5/components/animation/animationAuthoring.ts
  src/main/webapp/wise5/components/animation/authoring.html
  src/main/webapp/wise5/components/animation/edit-animation-advanced/edit-animation-advanced.component.html
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoring.ts
  src/main/webapp/wise5/components/audioOscillator/authoring.html
  src/main/webapp/wise5/components/audioOscillator/edit-audio-oscillator-advanced/edit-audio-oscillator-advanced.component.html
  src/main/webapp/wise5/components/conceptMap/authoring.html
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoring.ts
  src/main/webapp/wise5/components/conceptMap/edit-concept-map-advanced/edit-concept-map-advanced.component.html
  src/main/webapp/wise5/components/conceptMap/edit-concept-map-advanced/edit-concept-map-advanced.component.ts
  src/main/webapp/wise5/components/discussion/authoring.html
  src/main/webapp/wise5/components/draw/authoring.html
  src/main/webapp/wise5/components/draw/drawAuthoring.ts
  src/main/webapp/wise5/components/draw/edit-draw-advanced/edit-draw-advanced.component.html
  src/main/webapp/wise5/components/draw/edit-draw-advanced/edit-draw-advanced.component.ts
  src/main/webapp/wise5/components/embedded/authoring.html
  src/main/webapp/wise5/components/embedded/edit-embedded-advanced/edit-embedded-advanced.component.html
  src/main/webapp/wise5/components/embedded/embeddedAuthoring.ts
  src/main/webapp/wise5/components/graph/authoring.html
  src/main/webapp/wise5/components/graph/edit-graph-advanced/edit-graph-advanced.component.html
  src/main/webapp/wise5/components/graph/edit-graph-advanced/edit-graph-advanced.component.ts
  src/main/webapp/wise5/components/graph/graphAuthoring.ts
  src/main/webapp/wise5/components/html/htmlAuthoring.ts
  src/main/webapp/wise5/components/label/authoring.html
  src/main/webapp/wise5/components/label/edit-label-advanced/edit-label-advanced.component.html
  src/main/webapp/wise5/components/label/edit-label-advanced/edit-label-advanced.component.ts
  src/main/webapp/wise5/components/label/labelAuthoring.ts
  src/main/webapp/wise5/components/match/authoring.html
  src/main/webapp/wise5/components/match/edit-match-advanced/edit-match-advanced.component.html
  src/main/webapp/wise5/components/match/matchAuthoring.ts
  src/main/webapp/wise5/components/multipleChoice/authoring.html
  src/main/webapp/wise5/components/multipleChoice/edit-multiple-choice-advanced/edit-multiple-choice-advanced.component.html
  src/main/webapp/wise5/components/multipleChoice/edit-multiple-choice-advanced/edit-multiple-choice-advanced.component.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoring.ts
  src/main/webapp/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.html
  src/main/webapp/wise5/components/openResponse/edit-open-response-advanced/edit-open-response-advanced.component.ts
  src/main/webapp/wise5/components/outsideURL/authoring.html
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoring.ts
  src/main/webapp/wise5/components/summary/authoring.html
  src/main/webapp/wise5/components/summary/edit-summary-advanced/edit-summary-advanced.component.html
  src/main/webapp/wise5/components/summary/summaryAuthoring.ts
  src/main/webapp/wise5/components/table/authoring.html
  src/main/webapp/wise5/components/table/edit-table-advanced/edit-table-advanced.component.html
  src/main/webapp/wise5/components/table/edit-table-advanced/edit-table-advanced.component.ts
  src/main/webapp/wise5/components/table/tableAuthoring.ts
  src/main/webapp/wise5/test-unit/components/animation/animationAuthoringController.spec.js
  src/main/webapp/wise5/test-unit/components/conceptMap/conceptMapAuthoringController.spec.js
  src/main/webapp/wise5/test-unit/components/discussion/discussionAuthoringController.spec.js
  src/main/webapp/wise5/test-unit/components/draw/drawAuthoringController.spec.js
  src/main/webapp/wise5/test-unit/components/embedded/embeddedAuthoringController.spec.js
  src/main/webapp/wise5/test-unit/components/graph/graphAuthoringController.spec.js
  src/main/webapp/wise5/test-unit/components/summary/summaryAuthoringController.spec.js
  src/main/webapp/wise5/test-unit/components/table/tableAuthoringController.spec.js
Labels: 1 point

#2865 Upgrade HTMLAuthoring to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/wise5/components/html/authoring.html
  src/main/webapp/wise5/components/html/html-authoring/html-authoring.component.html
  src/main/webapp/wise5/components/html/html-authoring/html-authoring.component.ts
  src/main/webapp/wise5/components/html/htmlAuthoring.ts
  src/main/webapp/wise5/components/html/htmlAuthoringComponentModule.ts
Labels: 1 point

#2864 Upgraded AlertStatusCorner to Angular component
  src/main/webapp/site/src/app/classroom-monitor/alert-status-corner/alert-status-corner.component.html
  src/main/webapp/site/src/app/classroom-monitor/alert-status-corner/alert-status-corner.component.ts
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeProgress/navItem/navItem.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/alertStatusCorner/alertStatusCorner.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/alertStatusIcon/alertStatusIcon.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/shared.ts
Labels: 1 point

#2849 Upgraded WorkgroupSelect to Angular
  src/main/webapp/site/src/app/classroom-monitor/workgroup-select/workgroup-select-autocomplete/workgroup-select-autocomplete.component.html
  src/main/webapp/site/src/app/classroom-monitor/workgroup-select/workgroup-select-autocomplete/workgroup-select-autocomplete.component.scss
  src/main/webapp/site/src/app/classroom-monitor/workgroup-select/workgroup-select-autocomplete/workgroup-select-autocomplete.component.ts
  src/main/webapp/site/src/app/classroom-monitor/workgroup-select/workgroup-select-dropdown/workgroup-select-dropdown.component.html
  src/main/webapp/site/src/app/classroom-monitor/workgroup-select/workgroup-select-dropdown/workgroup-select-dropdown.component.scss
  src/main/webapp/site/src/app/classroom-monitor/workgroup-select/workgroup-select-dropdown/workgroup-select-dropdown.component.ts
  src/main/webapp/site/src/app/classroom-monitor/workgroup-select/workgroup-select.component.ts
  src/main/webapp/site/src/app/common-hybrid-angular.module.ts
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/site/src/style/abstracts/_mixins.scss
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/nodeGrading/nodeGradingView/nodeGradingView.html
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/shared.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupSelect/workgroupSelect.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/studentGrading/studentGradingTools/studentGradingTools.ts
  src/main/webapp/wise5/classroomMonitor/notebook/notebookGrading.html
  src/main/webapp/wise5/classroomMonitor/studentProgress/studentProgress.html
Labels: 8 points

#2866 Added support to format TypeScript files with Prettier
  .prettierignore
  .prettierrc
  .prettierrc.json
  package-lock.json
  package.json
Labels: 1 point

#2867 Upgraded Spring-Boot to 2.3.2 for WISE4
  pom.xml
  src/main/java/org/wise/portal/domain/group/impl/PersistentGroup.java
  src/main/java/org/wise/vle/domain/work/NotebookItem.java
  src/main/resources/wise_db_init.sql
Labels: 1 point

#2868 Refactored ProjectService.getAllPaths()
  src/main/webapp/site/src/app/services/projectService.spec.ts
  src/main/webapp/site/src/app/services/sampleData/curriculum/OneBranchTwoPaths.project.json
  src/main/webapp/site/src/app/services/sampleData/curriculum/TwoSteps.project.json
  src/main/webapp/wise5/services/projectService.ts
Labels: 1 point

#2873 Refactored MilestoneService and tests
  src/main/webapp/site/src/app/services/milestoneService.spec.ts
  src/main/webapp/wise5/services/milestoneService.ts
  src/main/webapp/wise5/services/utilService.ts
Labels: 1 point

#2871 Upgrade OutsideURLAuthoring to Angular component
  src/main/webapp/site/src/app/common-hybrid-angular.module.ts
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/components/outsideURL/authoring.html
  src/main/webapp/wise5/components/outsideURL/index.html
  src/main/webapp/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.html
  src/main/webapp/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.scss
  src/main/webapp/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.ts
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoring.ts
  src/main/webapp/wise5/components/outsideURL/outsideURLAuthoringComponentModule.ts
Labels: 1 point

#2874 ProjectService: extract teacher-related code to TeacherProjectService
  src/main/webapp/site/src/app/authoring-tool/add-component/choose-new-component-location/choose-new-component-location.component.spec.ts
  src/main/webapp/site/src/app/authoring-tool/add-component/choose-new-component-location/choose-new-component-location.component.ts
  src/main/webapp/site/src/app/preview/modules/choose-branch-path-dialog/choose-branch-path-dialog.component.ts
  src/main/webapp/site/src/app/services/projectService.spec.ts
  src/main/webapp/site/src/app/services/spaceService.spec.ts
  src/main/webapp/site/src/app/services/teacherProjectService.spec.ts
  src/main/webapp/wise5/authoringTool/node/editRubric/edit-rubric.component.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapService.ts
  src/main/webapp/wise5/components/label/labelService.ts
  src/main/webapp/wise5/services/projectService.ts
  src/main/webapp/wise5/services/spaceService.ts
  src/main/webapp/wise5/services/teacherProjectService.ts
Labels: 1 point

#2882 Moved AlertStatusCorner styles to component
  src/main/webapp/site/src/app/classroom-monitor/alert-status-corner/alert-status-corner.component.html
  src/main/webapp/site/src/app/classroom-monitor/alert-status-corner/alert-status-corner.component.ts
  src/main/webapp/site/src/app/classroom-monitor/alert-status-corner/alert-status-corner.scss
  src/main/webapp/wise5/themes/default/style/author.css
  src/main/webapp/wise5/themes/default/style/author.css.map
  src/main/webapp/wise5/themes/default/style/modules/_alerts.scss
  src/main/webapp/wise5/themes/default/style/modules/_nav--grading.scss
  src/main/webapp/wise5/themes/default/style/monitor.css
  src/main/webapp/wise5/themes/default/style/monitor.css.map
  src/main/webapp/wise5/themes/default/style/vle.css
  src/main/webapp/wise5/themes/default/style/vle.css.map
Labels: 1 point

#2884 Upgrade Multiple Choice authoring to Angular component
  src/main/webapp/site/src/app/common-hybrid-angular.module.ts
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/site/src/style/themes/_apps.scss
  src/main/webapp/wise5/authoringTool/components/component-authoring.component.ts
  src/main/webapp/wise5/components/html/html-authoring/html-authoring.component.ts
  src/main/webapp/wise5/components/multipleChoice/authoring.html
  src/main/webapp/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.html
  src/main/webapp/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.scss
  src/main/webapp/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoring.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceAuthoringComponentModule.ts
  src/main/webapp/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.html
  src/main/webapp/wise5/components/outsideURL/outside-url-authoring/outside-url-authoring.component.ts
Labels: 1 point

#2892 Draw advanced JSON authoring displays null
  src/main/webapp/wise5/components/draw/edit-draw-advanced/edit-draw-advanced.component.html
Labels: 1 point

#2888 Upgrade Concept Map authoring to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/authoringTool/node/node.html
  src/main/webapp/wise5/authoringTool/project/project.html
  src/main/webapp/wise5/components/conceptMap/authoring.html
  src/main/webapp/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.component.html
  src/main/webapp/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.component.scss
  src/main/webapp/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.component.ts
  src/main/webapp/wise5/components/conceptMap/conceptMapAuthoringComponentModule.ts
Labels: 1 point

#2890 Upgrade Draw authoring to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/components/draw/authoring.html
  src/main/webapp/wise5/components/draw/draw-authoring/draw-authoring.component.html
  src/main/webapp/wise5/components/draw/draw-authoring/draw-authoring.component.scss
  src/main/webapp/wise5/components/draw/draw-authoring/draw-authoring.component.ts
  src/main/webapp/wise5/components/draw/drawAuthoring.ts
  src/main/webapp/wise5/components/draw/drawAuthoringComponentModule.ts
Labels: 1 point

#2894 Upgrade Match authoring to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/components/match/authoring.html
  src/main/webapp/wise5/components/match/match-authoring/match-authoring.component.html
  src/main/webapp/wise5/components/match/match-authoring/match-authoring.component.scss
  src/main/webapp/wise5/components/match/match-authoring/match-authoring.component.ts
  src/main/webapp/wise5/components/match/matchAuthoring.ts
  src/main/webapp/wise5/components/match/matchAuthoringComponentModule.ts
Labels: 1 point

#2901 Upgrade Label authoring to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/authoringTool/components/component-authoring.component.ts
  src/main/webapp/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.component.ts
  src/main/webapp/wise5/components/draw/draw-authoring/draw-authoring.component.ts
  src/main/webapp/wise5/components/label/authoring.html
  src/main/webapp/wise5/components/label/label-authoring/label-authoring.component.html
  src/main/webapp/wise5/components/label/label-authoring/label-authoring.component.scss
  src/main/webapp/wise5/components/label/label-authoring/label-authoring.component.ts
  src/main/webapp/wise5/components/label/labelAuthoring.ts
  src/main/webapp/wise5/components/label/labelAuthoringComponentModule.ts
Labels: 1 point

#2909 Upgrade Discussion authoring to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/components/discussion/authoring.html
  src/main/webapp/wise5/components/discussion/discussion-authoring/discussion-authoring.component.html
  src/main/webapp/wise5/components/discussion/discussion-authoring/discussion-authoring.component.scss
  src/main/webapp/wise5/components/discussion/discussion-authoring/discussion-authoring.component.ts
  src/main/webapp/wise5/components/discussion/discussionAuthoring.ts
  src/main/webapp/wise5/components/discussion/discussionAuthoringComponentModule.ts
  src/main/webapp/wise5/components/discussion/discussionService.ts
Labels: 1 point

#2903 Unlinking Google account for teachers and students
  src/main/java/org/wise/portal/presentation/web/controllers/teacher/TeacherAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/GoogleUserAPIController.java
  src/main/java/org/wise/portal/presentation/web/controllers/user/UserAPIController.java
  src/main/java/org/wise/portal/presentation/web/exception/InvalidPasswordExcpetion.java
  src/main/resources/i18n/i18n.properties
  src/main/webapp/site/src/app/modules/library/copy-project-dialog/copy-project-dialog.component.ts
  src/main/webapp/site/src/app/modules/shared/edit-password/edit-password.component.html
  src/main/webapp/site/src/app/modules/shared/edit-password/edit-password.component.scss
  src/main/webapp/site/src/app/modules/shared/edit-password/edit-password.component.spec.ts
  src/main/webapp/site/src/app/modules/shared/edit-password/edit-password.component.ts
  src/main/webapp/site/src/app/modules/shared/shared.module.ts
  src/main/webapp/site/src/app/modules/shared/unlink-google-account-confirm/unlink-google-account-confirm.component.html
  src/main/webapp/site/src/app/modules/shared/unlink-google-account-confirm/unlink-google-account-confirm.component.scss
  src/main/webapp/site/src/app/modules/shared/unlink-google-account-confirm/unlink-google-account-confirm.component.spec.ts
  src/main/webapp/site/src/app/modules/shared/unlink-google-account-confirm/unlink-google-account-confirm.component.ts
  src/main/webapp/site/src/app/modules/shared/unlink-google-account-password/unlink-google-account-password.component.html
  src/main/webapp/site/src/app/modules/shared/unlink-google-account-password/unlink-google-account-password.component.scss
  src/main/webapp/site/src/app/modules/shared/unlink-google-account-password/unlink-google-account-password.component.spec.ts
  src/main/webapp/site/src/app/modules/shared/unlink-google-account-password/unlink-google-account-password.component.ts
  src/main/webapp/site/src/app/modules/shared/unlink-google-account-success/unlink-google-account-success.component.html
  src/main/webapp/site/src/app/modules/shared/unlink-google-account-success/unlink-google-account-success.component.scss
  src/main/webapp/site/src/app/modules/shared/unlink-google-account-success/unlink-google-account-success.component.ts
  src/main/webapp/site/src/app/modules/shared/validators/password-match.validator.ts
  src/main/webapp/site/src/app/services/user.service.spec.ts
  src/main/webapp/site/src/app/services/user.service.ts
  src/main/webapp/site/src/app/student/account/edit-profile/edit-profile.component.html
  src/main/webapp/site/src/app/student/account/edit-profile/edit-profile.component.scss
  src/main/webapp/site/src/app/student/account/edit-profile/edit-profile.component.spec.ts
  src/main/webapp/site/src/app/student/account/edit-profile/edit-profile.component.ts
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.html
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.scss
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.spec.ts
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.ts
  src/main/webapp/site/src/app/teacher/edit-run-warning-dialog/edit-run-warning-dialog.component.html
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/site/src/style/layout/_section.scss
  src/test/java/org/wise/portal/presentation/web/controllers/user/GoogleUserAPIControllerTest.java
  src/test/java/org/wise/portal/presentation/web/controllers/user/UserAPIControllerTest.java
Labels: 4 points

#2907 Upgrade Table authoring to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/components/table/authoring.html
  src/main/webapp/wise5/components/table/table-authoring/table-authoring.component.html
  src/main/webapp/wise5/components/table/table-authoring/table-authoring.component.scss
  src/main/webapp/wise5/components/table/table-authoring/table-authoring.component.ts
  src/main/webapp/wise5/components/table/tableAuthoring.ts
  src/main/webapp/wise5/components/table/tableAuthoringComponentModule.ts
Labels: 1 point
