Repository WISE-Community/WISE, pull requests merged in 2021-02, with the labels that each got.

#2913 Upgrade Embedded authoring to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/authoringTool/components/component-authoring.component.ts
  src/main/webapp/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.component.html
  src/main/webapp/wise5/components/conceptMap/concept-map-authoring/concept-map-authoring.component.ts
  src/main/webapp/wise5/components/draw/draw-authoring/draw-authoring.component.html
  src/main/webapp/wise5/components/embedded/authoring.html
  src/main/webapp/wise5/components/embedded/embedded-authoring/embedded-authoring.component.html
  src/main/webapp/wise5/components/embedded/embedded-authoring/embedded-authoring.component.scss
  src/main/webapp/wise5/components/embedded/embedded-authoring/embedded-authoring.component.ts
  src/main/webapp/wise5/components/embedded/embeddedAuthoring.ts
  src/main/webapp/wise5/components/embedded/embeddedAuthoringComponentModule.ts
  src/main/webapp/wise5/components/label/label-authoring/label-authoring.component.html
  src/main/webapp/wise5/components/multipleChoice/multiple-choice-authoring/multiple-choice-authoring.component.ts
Labels: 1 point

#2911 Upgrade Summary authoring to Angular component
  src/main/webapp/site/src/app/services/discussionService.spec.ts
  src/main/webapp/site/src/app/services/teacherProjectService.spec.ts
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/components/match/matchService.ts
  src/main/webapp/wise5/components/summary/authoring.html
  src/main/webapp/wise5/components/summary/summary-authoring/summary-authoring.component.html
  src/main/webapp/wise5/components/summary/summary-authoring/summary-authoring.component.scss
  src/main/webapp/wise5/components/summary/summary-authoring/summary-authoring.component.ts
  src/main/webapp/wise5/components/summary/summaryAuthoringComponentModule.ts
  src/main/webapp/wise5/services/projectService.ts
  src/main/webapp/wise5/services/teacherProjectService.ts
Labels: 1 point

#2919 Upgrade Graph authoring to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/components/graph/authoring.html
  src/main/webapp/wise5/components/graph/graph-authoring/graph-authoring.component.html
  src/main/webapp/wise5/components/graph/graph-authoring/graph-authoring.component.scss
  src/main/webapp/wise5/components/graph/graph-authoring/graph-authoring.component.ts
  src/main/webapp/wise5/components/graph/graphAuthoringComponentModule.ts
Labels: 1 point

#2922 Upgrade AudioOscillator authoring to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/components/audioOscillator/audio-oscillator-authoring/audio-oscillator-authoring.component.html
  src/main/webapp/wise5/components/audioOscillator/audio-oscillator-authoring/audio-oscillator-authoring.component.scss
  src/main/webapp/wise5/components/audioOscillator/audio-oscillator-authoring/audio-oscillator-authoring.component.ts
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoring.ts
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorAuthoringComponentModule.ts
  src/main/webapp/wise5/components/audioOscillator/audioOscillatorController.ts
  src/main/webapp/wise5/components/audioOscillator/authoring.html
Labels: 1 point

#2925 Upgrade Animation authoring to Angular component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/authoringTool/components/component-authoring.component.ts
  src/main/webapp/wise5/components/animation/animation-authoring/animation-authoring.component.html
  src/main/webapp/wise5/components/animation/animation-authoring/animation-authoring.component.scss
  src/main/webapp/wise5/components/animation/animation-authoring/animation-authoring.component.ts
  src/main/webapp/wise5/components/animation/animationAuthoring.ts
  src/main/webapp/wise5/components/animation/animationAuthoringComponentModule.ts
  src/main/webapp/wise5/components/animation/authoring.html
Labels: 1 point

#2927 Teacher edit profile UI changes
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.html
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.spec.ts
  src/main/webapp/site/src/app/teacher/account/edit-profile/edit-profile.component.ts
  src/main/webapp/site/src/messages.xlf
Labels: 1 point

#2930 Branching based on CRater sub-score
  src/main/webapp/wise5/authoringTool/i18n/i18n_en.json
  src/main/webapp/wise5/authoringTool/node/advanced/branch/node-advanced-branch-authoring.component.html
  src/main/webapp/wise5/authoringTool/node/advanced/branch/node-advanced-branch-authoring.component.ts
  src/main/webapp/wise5/authoringTool/node/advanced/path/node-advanced-path-authoring.component.html
  src/main/webapp/wise5/authoringTool/node/advanced/path/node-advanced-path-authoring.component.ts
  src/main/webapp/wise5/services/annotationService.ts
  src/main/webapp/wise5/services/studentDataService.ts
Labels: 1 point

#2933 Extract grading view from Open Response component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/component-grading.component.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupNodeGrading/workgroupNodeGrading.ts
  src/main/webapp/wise5/components/openResponse/index.html
  src/main/webapp/wise5/components/openResponse/open-response-grading/open-response-grading.component.html
  src/main/webapp/wise5/components/openResponse/open-response-grading/open-response-grading.component.ts
  src/main/webapp/wise5/components/openResponse/openResponseController.ts
  src/main/webapp/wise5/components/openResponse/openResponseGradingComponentModule.ts
  src/main/webapp/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#2934 Changing max score for a component in the Grading Tool for a project with a milestone fails
  src/main/webapp/wise5/services/achievementService.ts
Labels: 1 point

#2924 Combine milestone reports
  src/main/webapp/site/src/app/services/milestoneService.spec.ts
  src/main/webapp/site/src/app/services/utilService.spec.ts
  src/main/webapp/site/src/app/teacher/milestone/milestone-report-data/milestone-report-data.component.spec.ts
  src/main/webapp/site/src/app/teacher/milestone/milestone-report-data/milestone-report-data.component.ts
  src/main/webapp/wise5/directives/milestoneReportGraph/milestoneReportGraph.js
  src/main/webapp/wise5/services/milestoneService.ts
  src/main/webapp/wise5/services/utilService.ts
Labels: 2 points

#2936 Extract grading view from Multiple Choice component
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/site/src/messages.xlf
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/component-grading.component.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/componentRevisionsInfo/componentRevisionsInfo.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentRevisions/workgroupComponentRevisions.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupNodeGrading/workgroupNodeGrading.ts
  src/main/webapp/wise5/components/multipleChoice/index.html
  src/main/webapp/wise5/components/multipleChoice/multiple-choice-grading/multiple-choice-grading.component.html
  src/main/webapp/wise5/components/multipleChoice/multiple-choice-grading/multiple-choice-grading.component.scss
  src/main/webapp/wise5/components/multipleChoice/multiple-choice-grading/multiple-choice-grading.component.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceController.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceGradingComponentModule.ts
  src/main/webapp/wise5/components/multipleChoice/multipleChoiceService.ts
  src/main/webapp/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point

#2939 Add Match advanced authoring options back
  src/main/webapp/wise5/components/match/edit-match-advanced/edit-match-advanced.component.html
  src/main/webapp/wise5/components/match/edit-match-advanced/edit-match-advanced.component.ts
Labels: 1 point

#2942 Extract grading view from Match component
  src/main/webapp/site/src/app/common-hybrid-angular.module.ts
  src/main/webapp/site/src/app/teacher-hybrid-angular.module.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupComponentRevisions/workgroupComponentRevisions.ts
  src/main/webapp/wise5/classroomMonitor/classroomMonitorComponents/shared/workgroupNodeGrading/workgroupNodeGrading.ts
  src/main/webapp/wise5/components/match/index.html
  src/main/webapp/wise5/components/match/match-grading/match-grading.component.html
  src/main/webapp/wise5/components/match/match-grading/match-grading.component.scss
  src/main/webapp/wise5/components/match/match-grading/match-grading.component.ts
  src/main/webapp/wise5/components/match/matchController.ts
  src/main/webapp/wise5/components/match/matchGradingComponentModule.ts
  src/main/webapp/wise5/teacher/teacher-angular-js-module.ts
Labels: 1 point, 2 points

#2950 Added interval for compiling component preview on changes.
  src/main/webapp/wise5/authoringTool/components/preview-component/previewComponent.ts
Labels: 1 point

#2951 GoogleUserNotFound page now displays again.
  src/main/webapp/site/src/app/login/login-google-user-not-found/login-google-user-not-found.component.ts
  src/main/webapp/site/src/app/login/login-routing.module.ts
  src/main/webapp/site/src/messages.xlf
Labels: 1 point
